### ISSUE TITLE
Remover dependência do embed.js

### ISSUE THREAD

**Issue by arkye** [ejplatform/ej-server#1]
Para remover o Pol.is do projeto **ejplatform**, a dependência do`embed.js` deve ser removida.

**Comment by luanguimaraesla** [comment]
Testando

**Comment by rodrigocam** [comment]
Atualmente a dependência do `embed.js` foi removida, juntamente com a total remoção das referências ao Pol.is, tanto no back-end quanto no front-end.

**Comment by luanguimaraesla** [comment]
Boa manos! Vou só ver qual é o erro com os nossos IPs externos e subir uma versão de desenvolvimento. Em breve disponível em https://ej.dev.lappis.rocks

**Comment by rodrigocam** [comment]
Aee, é bom fazer os pull-requests pra branch development já?
