### ISSUE TITLE
Implementação da home comercial do ej genérico a partir dos layouts

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#101]
Wireframes foram implementados a partir dos layouts indicados na issue #100 (da qual essa depende).

Aqui estão: https://projects.invisionapp.com/d/main#/console/13863876/302456109/preview

**Comment by ricardopoppi** [comment]
Vamos aguardar o update das telas que virão a partir da issue #167

**Comment by ricardopoppi** [comment]
@caiosba importante que essa implementação siga a lógica de fragments pra manter compatibilidade com o mecanismo de build/deploy

**Comment by fabiommendes** [comment]
Acho que a primeira versão poderia ser hardcoded mesmo e depois implementamos fragments. Lembrando que o tema permite dar override em assets arbitrários como as imagens e ícones que aparecem na tela. Se algum cliente precisar mudar os textos, a gente muda isso depois ;)

**Comment by ricardopoppi** [comment]
@caiosba essa aqui avançou?

**Comment by caiosba** [comment]
Sim @ricardopoppi , quase concluído... até amanhã está pronto.

**Comment by ricardopoppi** [comment]
Coisa linda @caiosba!!!

**Comment by caiosba** [comment]
Home comercial concluída! Além disso, agora os temas podem definir o caminho para sua página inicial. O EJ define "home" e o CPA define "conversations". Em anexo, um screenshot da implementação. Já disponível no `master`.
![screencapture-localhost-8000-home-2018-08-08-13_40_34](https://user-images.githubusercontent.com/117518/43851415-022700d6-9b11-11e8-9a09-4bb3d0b909f5.png)
