### ISSUE TITLE
Ativar PWA web app no EJ genérico

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#107]
Ativar no EJ genérico aquela opção de PWA que permite add o link da página na tela inicial do android ou IOS e a partir daí ele cria uma máscara no browser mobile pra simular o uso como se fosse aplicativo instalado

**Comment by caiosba** [comment]
Feito! O PWA está com base no tema. Ver em anexo o screenshot de como aparece o ícone no EJ e no CPA.
![photo5059901598939064285](https://user-images.githubusercontent.com/117518/42612980-c5771f4c-8574-11e8-97da-5c1ca6d0e7d9.jpg)
