### ISSUE TITLE
Ajustar a tela de "Lista de Conversas" No Django e React

### ISSUE THREAD

**Issue by leandronunes** [ejplatform/ej-server#114]

**Comment by caiosba** [comment]
Feito, conforme screenshot em anexo.
![screencapture-localhost-8000-conversations-2018-06-12-00_18_19](https://user-images.githubusercontent.com/117518/41268382-2c508be2-6dd6-11e8-8d1e-00f8b68563df.png)

**Comment by caiosba** [comment]
Atribuindo a @ricardopoppi para revisão.
