### ISSUE TITLE
Adicionar número de compartilhamentos nas contribuições 

### ISSUE THREAD

**Issue by leandronunes** [ejplatform/ej-server#119]

**Comment by leandronunes** [comment]
Atualmente esta informação do número de compartilhamentos não existe no sistema a ideia é que cada vez que a pessoa clique no botão compartilhar seja incrementado o valor de número de compartilhamentos em +1?

**Comment by ricardopoppi** [comment]
@leandronunes não achei no protótipo onde isso aparece. pode me indicar?

**Comment by leandronunes** [comment]
https://projects.invisionapp.com/d/main#/console/13863876/300670645/preview

Quantidade de compartilhamentos

**Comment by ricardopoppi** [comment]
ahh. Não teremos nesse milestone. Pode eliminar dessa tela tanto o numero de compartilhamentos quanto o numero de quests. E onde está "opinadas" muda pra "comentários" de acordo com a nomenclatura final. Fechando essa issue.
