### ISSUE TITLE
Adicionar visualização da conversa na lista de conversas favoritas

### ISSUE THREAD

**Issue by leandronunes** [ejplatform/ej-server#121]
Adicionar o novo layout de visualizar uma conversa na lista de conversas favoritas, conforme wireframe: https://projects.invisionapp.com/d/main#/console/13863876/300670644/preview

observe o togle

**Comment by ricardopoppi** [comment]
Creio que já é possível realizar essa issue já que a #222 já foi fechada. @leandronunes segue com essa?
