### ISSUE TITLE
Segundo comentário de um usuário dá erro de permissão

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#124]
Será que tem relação com o nudge? Na configuração da conversa não tem opção de nudge, mas suspeito que a lógica pode estar presente no código.

Trace do erro: http://dpaste.com/3CY57CY

**Comment by ricardopoppi** [comment]
Notei que se você recarregar a página, ele aceita o próximo comentário. O erro se repete sempre no segundo comentário feito em sequencia

**Comment by ricardopoppi** [comment]
sim, de acordo. com global baixo, tanto faz o comentário. mas acho que não precisamos priorizar nenhuma mudança na lógica agora, pois sempre é possível colocar um intervalo grande. A questão é: abro uma issue pra incluir no admin da conversa (mesmo que seja apenas no django admin) a configuração do nudge? Atualmente isso é parametrizado em algum local no django admin?

**Comment by fabiommendes** [comment]
Por enquanto a configuração é global e está no settings do django. Acho que a gente tem 3 opções:
1. Fazer config (via admin) por conversa
2. Fazer config no constance que deixa uma opção no admin para todas as conversas
3. Tirar a lógica de intervalo mínimo entre comentários

De todo jeito, é bom deixar o padrão de 0s para desabilitar a opção enquanto não temos solução no front.

**Comment by ricardopoppi** [comment]
Gostei! Tería uma quarta possibilidade:
(4) Fazer config por usuário, ou seja, todas as conversas de uma mesma timeline de usuário teriam o mesmo parametro. Isso não onera a criação de conversas com parametrizações extensas (mantem o custo baixo) e ao mesmo tempo permite flexibilidade por usuário/tipo de apropriação.

Sobre deixar atualmente o valor default como 0s default e o backend entender isso com "disable" é uma ótima opção!

O que achou dessa solução (4) @fabiommendes ?

**Comment by fabiommendes** [comment]
Eu prefiro manter as configs. globais até aparecer um caso de uso onde faz sentido ter configurações específicas por conversa. Você consegue pensar em uma necessidade concreta para isso?

**Comment by ricardopoppi** [comment]
Pode ser também. A necessidade concreta que pensei é baseada na tese de que diferentes pilotos podem requerer diferentes tunagens ao longo da experimentação. Ajustar apenas no global pode ter um impacto diferente em cada piloto.
