### ISSUE TITLE
Permitir a definição da TAG da conversa na tela de admin de criação de conversa

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#125]
Hj o admin só permite title e text. Seria legal permitir a configuração da tag, considerando que a página que lista conversas vai exibi-las para os usuários

**Comment by pablodiegoss** [comment]
O campo tag foi criado, sendo elas adicionadas separando por vírgula cada tag.
A exibição das tags nos cards de conversa está mostrando apenas a primeira tag, precisamos definir como será essa exibição posteriormente.
