### ISSUE TITLE
Inserir ícone no link de logout na barra lateral

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#131]
@luizapeixe pode propor esse ícone com base no EJ-Genérico? Aí o @leandronunes aplica

Como está atualmente:

![captura de tela de 2018-06-12 09-09-37](https://user-images.githubusercontent.com/1162183/41289633-ce1bc352-6e20-11e8-838d-e2206c79a56a.png)

**Comment by lucasssm** [comment]
Feito!

**Comment by lucasssm** [comment]
Feito!
