### ISSUE TITLE
Remover a opção de criar conversa no /conversations para usuários comuns

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#134]
Essa opção só deve aparecer na timeline de conversas do usuário (ejplatform.org/<username>. Hoje ela está aparecendo, para um usuário comum, no /conversations

Vejam a opção "add new conversation":

![captura de tela de 2018-06-12 09-29-41](https://user-images.githubusercontent.com/1162183/41290624-d54a530c-6e23-11e8-95a5-c86d4e5e4152.png)

**Comment by caiosba** [comment]
Feito!
