### ISSUE TITLE
Botão voltar (canto superior esquerdo) com comportamento perigoso dentro de conversa

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#139]
Para simular:

1) Entre em uma conversa;
2) Clique no botão boltar (canto superior esquerdo);
3) Observe que vc voltou para a lista de conversas;
4) Clique novamente em uma conversa;
5) Vote em  um ou mais comentários e/ou insira um ou mais comentários
6) Clique no botão voltar
7) OBSERVE QUE QUE O BOTÃO VOLTAR MUDOU DE COMPORTAMENTO. Clicando no botão voltar, os comentários anteriores foram carregados, permanecendo na interna da conversa. Esse comportamento é perigoso pois além de confundir o usuário em UX, também quebra a aleatoriedade dos comentários.

**Comment by caiosba** [comment]
Acho que isso foi corrigido... não consegui mais reproduzir.

**Comment by ricardopoppi** [comment]
Realmente, foi corrigido. Fechando.
