### ISSUE TITLE
Criação de comentário pelo django admin quebrando

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#144]
Erro REJECT quando inserir comentário direto pelo django admin. Conta de superusuário.

**Comment by fabiolamfleury** [comment]
@ricardopoppi consegui criar comentários via admin(via localhost), houveram outras variáveis que poderiam contribuir para o acontecimento do erro?

**Comment by ricardopoppi** [comment]
massa! como não conseguimos reproduzir, fecharei a issue até eventualmente acontecer de novo. como é um bug muito antigo, pode ter sido resolvido nas novas atualizações que vieram depois dessa versão
