### ISSUE TITLE
Erro de REJECT na aprovação de comentários direto pelo django admin

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#146]
Para simular: Usuario superadmin, tentando aprovar comentarios na sua propria conversa, recebe erro de REJECT

**Comment by fabiolamfleury** [comment]
@ricardopoppi consegui aprovar comentários na minha própria conversa via admin, houveram outras variáveis que poderiam contribuir para o acontecimento do erro?

**Comment by ricardopoppi** [comment]
massa! como não conseguimos reproduzir, fecharei a issue até eventualmente acontecer de novo. como é um bug muito antigo, pode ter sido resolvido nas novas atualizações que vieram depois dessa versão
