### ISSUE TITLE
Implementar o admin de edição de conversas e moderação de comentários

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#157]
Essa é a tela em que o usuário pode criar, editar conversa ou moderar comentários das SUAS conversas.

Para o tema do CPA, usar [esse wireframe](https://projects.invisionapp.com/d/main#/console/14015249/302910831/preview).

Para o tema genérico, [esse wireframe](https://projects.invisionapp.com/share/V9GNMI1BG2F#/screens/303751467_Conversa_EDIT_V2)

**Comment by caiosba** [comment]
Como eu chego nesta tela?

**Comment by ricardopoppi** [comment]
O usuário só tem permissão para criar conversas quando estiver na sua timeline de conversas. Hj como o menu lateral não exibe esse atalho (issue #189 vai corrigir isso), o único jeito de acessar é pela url ejplatform/_username_

Na timeline do usuário aparece a opção "criar conversa" (url: /conversations/add) conforme img abaixo:

![captura de tela de 2018-07-04 11-41-47](https://user-images.githubusercontent.com/1162183/42288434-0fbaaa7c-7f91-11e8-8c09-ed3f1421b2f5.png)



A opção de editar aparece no topo quando o usuário está na interna de uma conversa que criou, (url: /conversations/slug_da_conversa/edit) conforme img abaixo:

![captura de tela de 2018-07-04 11-40-03](https://user-images.githubusercontent.com/1162183/42288615-d6e72a62-7f91-11e8-89e3-05f382402059.png)




Outra forma de chegar nessa tela deveria ser a partir do botão de moderação aparece no thumbnail da conversa, conforme imagem abaixo. A issue #202 vai resolver o problema de estilos desse thumbnail. Porém notei que essa tela está diferente. Na proposta de UX ela deveria convergir pra mesma tela de edição de conversa proposta nos wireframes, que é também onde a moderação de comentários acontece. Isso vai exigir algum tipo de unificação no backend.

![captura de tela de 2018-07-04 11-40-10](https://user-images.githubusercontent.com/1162183/42288508-584b74d8-7f91-11e8-91e6-6252cbc8f590.png)

**Comment by caiosba** [comment]
Tela de moderação de comentários para o tema CPA também implementado, conforme screenshot em anexo.
![screencapture-localhost-8000-conversations-admin2-test-moderate-2018-07-24-11_04_15](https://user-images.githubusercontent.com/117518/43143580-65e54204-8f31-11e8-921d-a9cbbcd17cbc.png)

**Comment by ricardopoppi** [comment]
Maravilha @caiosba 

Assim que tivermos as formulações da @luizapeixe nas issues #267 e #268 vc poderá finalizar.

**Comment by caiosba** [comment]
Renomeei esta tarefa para ser apenas edição e moderação. Concluí a edição de conversas, para os temas CPA e EJ, está no `master`. Vídeos em https://www.youtube.com/watch?v=0YCUzw_Kn9A e https://www.youtube.com/watch?v=X2FymXrOPp8. Moderação também está pronto e no `master` para ambos os temas. Quando a Luiza terminar a #267 podemos abrir uma nova tarefa para implementação.
