### ISSUE TITLE
Rever política de versionamento da plataforma

### ISSUE THREAD

**Issue by luanguimaraesla** [ejplatform/ej-server#16]
O versionamento realizado no contexto do projeto Brasil que o Povo Quer tende a se tornar problemático com o passar do tempo. Sem nenhuma modificação drástica de usabilidade/interface/recursos, já nos encontramos na versão 4.0. Acredito que seja importante revisar essa nomeclatura e corrigir já nas próximas versões, considerando que a versão sem o Pol.is pode ser nomeada como v0.1.0.

**Comment by fabiommendes** [comment]
Não tenho problemas com os números ficarem grandes (veja Chrome ou Firefox, por exemplo). O que não gosto é que a release da aplicação seja um número e não alguma coisa um pouco mais amigável. Minha proposta é que cada release aumente um número e venha com um nome associado. Temos que escolher um método de escolher nomes. Minha sugestão é mulheres cientistas.

Nossos apps e libs, devemos utilizar Semver, quer os números subam muito ou não ;)

**Comment by ricardopoppi** [comment]
Proposta validada com @fabiommendes:

1) Lib usam semver (semantic version);
2) EJ incrementa em números inteiros para cada milestone, começando da 1 quando fecharmos os milestones atuais "Full product". Ex: v1, v2, v3...
3) Cada número vem com um nome amigável associado. Ex: nomes de bichos, cientistas, ativistas etc. Vamos fazer uma conversa no EJ pŕa decidir isso.
