### ISSUE TITLE
Derivar a tela de criação/edição/moderação pro wireframe genérico

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#160]
@luizapeixe fizemos uns ajustes nessa [tela para o CPA](https://projects.invisionapp.com/d/main#/console/14015249/302910831/preview). O pedido pra ti é derivar essa mesma estrutura para o idv do EJ genérico

**Comment by luizapeixe** [comment]
Ok! Acabei de subir no invision a tela de [Edição de Comentário](https://invis.io/V9GNMI1BG2F#/303751467_Conversa_EDIT_V2) alterada.

**Comment by ricardopoppi** [comment]
Maravillha, ficou ótimo o pessoal já pode usar ela pra implementar na #157
