### ISSUE TITLE
Aplicar os estilos do EJ Genérico no django admin

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#161]
Atualmente o django admin (imagem abaixo) usa o estilo padrão. Precisamos aplicar o estilo EJ nessa interface para manter a coerencia com o idv do EJ genérico.

A proposta é fazermos, nessa primeira etapa, apenas uma aplicação de estilos, sem propor modificações na arquitetura atual. Numa segunda etapa poderemos trabalhar propostas que melhorem a usabilidade de algumas funções, especialmente a criação de clusters e estereótipos

![screencapture-ejplatform-org-admin-2018-06-14-23_18_44](https://user-images.githubusercontent.com/1162183/41447228-90f8e35e-702a-11e8-89b1-dea8c5b6c168.png)

**Comment by luizapeixe** [comment]
aí vai uma primeira proposta: https://invis.io/V9GNMI1BG2F#/304630145_admin_Django

**Comment by ricardopoppi** [comment]
Ficou massa, já é suficiente pra primeira aplicação
