### ISSUE TITLE
Incluir na home "comercial" um seção sobre a documentação do EJ

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#167]
A issue #169 é referente a criação da visualização completa da documentação. Na home comercial, podemos trazer alguma seções ou exibir o link a elas num outro formato, mais resumido.

**Comment by luizapeixe** [comment]
acabei de subir no invision uma proposta de faixa pra Documentação na Home Comercial: https://invis.io/V9GNMI1BG2F#/304623866_Home_Comercial_V2

**Comment by ricardopoppi** [comment]
Ficou ótima!
