### ISSUE TITLE
[meta] Criar repositório de documentação do EJ em formato RST

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#168]
Nossa referencia é o rocket chat: https://github.com/RocketChat/docs

Iniciaremos com a seguinte estrutura:  

User guides
Installation guides
Administrator guides
Developer guides
Our AI
Contributing
Getting support

(versão traduzida)
Guias de usuário  
Guias de instalação
Guias de administração
Guia do desenvolvedor
Nossa inteligência artifical  
Contribuindo na comunidade  
Suporte da comunidade

**Comment by valessiobrito** [comment]
@ricardopoppi @luizapeixe olá pessoal, notei que o trabalho da arquitetura de informação da documentação já foi inspirada em um projeto com grande quantidade de conteúdo a ser disseminado, por isso acho que ficou confuso.    Minha proposta é simplificar essa arquitetura em 2 itens inicialmente; no máximo 3;    E com isso, também reformular as telas, removendo a necessidade de mais um item de menu 'hambúrguer'.   Minha proposta é iniciarmos com dois itens de estrutura:

#### Guia do Usuário
- Boas vindas (Sobre)
- Login/Registro
- Discussões
- Nossa inteligência artificial
- Administração (avançado)
- Perguntas Frequentes
- Acessibilidade
- Privacidade
- Suporte da comunidade
- ...

### Guia do Desenvolvedor
- Boas vindas (Sobre Dev)
- Guia rápido de instalação (Quick start)
- Contribuindo na comunidade
- Recomendações/estilo de código
- Componentes de Design UI/UX
- Trabalhando com Testes
- Evolução da inteligência artificial
- Manual da API
- Comunidade de desenvolvimento
- ...

Bom, os tópicos ainda não estão 100% fechados;  A proposta é iniciar a documentação com 2 grandes áreas:  usuários e desenvolvimento;   E quando abrir alguma dessas áreas, apresentar: a busca, o índice e conteúdo de boas vindas (primeiro tópico em cada documentação);

Dito isso, acredito que precisamos simplificar a primeira tela da documentação e as demais onde aparece um menu hambúrguer;  Segue anexo a proposta com print de uma montagem.

![doc1](https://user-images.githubusercontent.com/310049/45317382-3bab8200-b510-11e8-84c7-d97cb4916281.png)

![doc2](https://user-images.githubusercontent.com/310049/45317383-3c441880-b510-11e8-882f-d2243de0d20a.png)

@luizapeixe acho que o item do menu pode ter um fundo diferente; não sei... enfim, se puder propor esses ajustes ai para nós. ;)

**Comment by ricardopoppi** [comment]
boa @valessiobrito! 

@luizapeixe, o Valessio é o nosso novo PO da documentação, vai organizar os conteúdos e fazer a ponte entre o design e a implementação.

**Comment by luizapeixe** [comment]
Oi @valessiobrito ! Muito prazer e bem vindo ao time :)

Que bom que vamos condensar os conteúdos, assim realmente fica melhor organizado pros users e devs se acharem na documentação. Levei suas sugestões em consideração e cheguei numa nova proposta de layout pra essa área.

1. tela de "home" da documentação -> https://invis.io/HRO02JJD2EK
Os conteúdos estão divididos em dois grandes guarda-chuvas, como você sugeriu

2. interna de um dos guarda-chuvas (no caso, Guias de Usuários) -> https://invis.io/ADO02KXXPJU
Para substituir o menu hamburguer e ainda assim exibir as conteúdos, pensei num dropdown que exibiria os diferentes tópicos da documentação. Abaixo dele mantive ainda sua sugestão de breadcrumb, que imagino que poderia ficar fixo na rolagem (a validar com equipe dev sobre possibilidades de implementação)

3. interna do Guia de Usuários com o dropdown aberto -> https://invis.io/FZO0308KTXD
Clicando para abrir o dropdown o user tem acesso aos tópicos do Item selecionado e o tópico em questão fica evidenciado por uma diferenciação cromática.

O que acham?

**Comment by valessiobrito** [comment]
@luizapeixe fico com a sua última versão;  parece mais intuitivo termos o índice geral (de toda documentação) e eliminar a home.   Menos clique para o usuário navegar entre ambas.  @ricardopoppi o que acha?

**Comment by ricardopoppi** [comment]
de acordo, ficou melhor mesmo, tá lindo demais ver essa issue evoluindo!

**Comment by ricardopoppi** [comment]
pontapé inicial foi dado, aprimoramentos estão sendo tratados em issues específicas
