### ISSUE TITLE
Criar proposta visual da documentação do EJ

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#169]
Vamos usar o mesmo software que gera esse formato: https://rocket.chat/docs/index.html

Dentro desse "jeitão" é possível criar em cima da idv do EJ a aprimorar usabilidade

Seções que usaremos:

User guides
Instalation guides
Administrator guides
Developer guides
Our AI
Contributing
Getting support

(versão traduzida)
Guias de usuário
Guias de instalação
Guias de administração
Guia do desenvolvedor
Nossa inteligência artifical
Contribuindo na comunidade
Suporte da comunidade

As subseções, por hora pode usar texto de marcação

**Comment by luizapeixe** [comment]
Eis uma primeira proposta pra essa tela: https://invis.io/V9GNMI1BG2F#/303783054_Documentac-a-o

**Comment by ricardopoppi** [comment]
Ficou ótimo @luizapeixe !

Agora vale simular a aplicação dos estilos numa página interna. Referencias de páginas internas com outros estilos, usando a mesma ferramenta de documentação que a gente vai usar:

https://hyperpython.readthedocs.io/en/latest/
http://flask.pocoo.org/docs/1.0/installation/
http://trueskill.org/
https://pythonhosted.org/ranking/
https://pythonhosted.org/energy/
http://lunant.net/jdoctest/

**Comment by luizapeixe** [comment]
Obrigada pelas referencias, Poppi!

Adicionei o item "nossa IA" e fiz alguns pequenos ajustes na [tela de Documentação](https://invis.io/V9GNMI1BG2F#/303783054_Documentac-a-o). Baseada nas referencias, adicionei um [menu de navegação](https://invis.io/V9GNMI1BG2F#/303830429_Documentac-a-o_Menu) especial para a área de documentação. A intenção é que o usuário acesse os conteúdos pontualmente tópico a tópico, para não deixar as telas muito poluídas de informações e, ao mesmo tempo, que ele tenha uma navegação simplificada para acessar os outros itens a uma distancia máxima de 3 cliques: (1. no menu; 2. no item principal e 3. no sub-item específico). Clicando em "Boas vindas à Documentação" o user é levado de volta para a [página principal da Documentação](https://invis.io/V9GNMI1BG2F#/303783054_Documentac-a-o).

Nas internas, fiz dois exemplos: 1. [conteúdo mais de texto](https://invis.io/V9GNMI1BG2F#/303830430_Documentac-a-o_Pg_Interna) e 2. [conteúdo mais de dev](https://invis.io/V9GNMI1BG2F#/303830428_Documentac-a-o_Pg_Interna_2). Nessa segunda eu usei a webfont [Cutive Mono](https://fonts.google.com/specimen/Cutive+Mono) nas áreas de código. Adicionei um recurso de breadcrumb pra ajudar o usuário a se situar nos diferentes tópicos, mas posso retirar se acharem irrelevante.

**Comment by ricardopoppi** [comment]
Ficou sensacional @luizapeixe já temos o que precisamos, fechando a issue

**Comment by valessiobrito** [comment]
Registrando a versão final, reajustada com discussão na issue #168

layouts:

Documentação home - https://invis.io/S2O0MT3NBYA
Documentação home toggle aberto - https://invis.io/CXO2AR58WMS
assets:

Guia de usuário - https://drive.google.com/file/d/1I84smCL-gfm0ON34pv1zsk6l504Q5azX/view?usp=sharing
Guia de desenvolvimento - https://drive.google.com/file/d/1iI5oGZTQPQw8JLKURLFuWox2JBe3il7Y/view?usp=sharing
