### ISSUE TITLE
Ativar o readthedocs e o sphinx no servidor no dominio dev.ejplatform.org/docs

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#170]
O readthedocs e sphinx deve ler da pasta docs repositório ej-server no github. Os estilos serão implementados na issue #171

**Comment by valessiobrito** [comment]
@caiosba esta avaliando o uso da rota  /docs para rodar junto com aplicação dentro do mesmo domínio, assim evitamos de configurar um subdomínio para cada instância e de rotar a documentação a parte. Esse item esta como task na issue #171

**Comment by ricardopoppi** [comment]
Rota foi criada, creio que falta rodar o comando na raiz da aplicação e inserir no pipeline:
`sphinx-build docs build/docs`

@pablodiegoss pode dar um alo qdo tiver rodado isso no dev.ejplatform.org?

**Comment by caiosba** [comment]
PR pronto para revisão em https://github.com/ejplatform/ej-server/pull/553. A home comercial inclui os links para a documentação. Funciona para inglês e português.
