### ISSUE TITLE
Implementar os estilos da página de documentação do EJ no sphinx

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#171]
Conforme wireframes da issue #169 

- [x] Reutilizar componentes Jinja ao invés de HTML estático no layout da documentação
- [x] Implementar uma rota de acesso à documentação (URL dentro do EJ)
- [x] Suporte a internacionalização da documentação (pt_BR, en, es...)

**Comment by caiosba** [comment]
Implementei a parte da rota. É possível compilar a documentação com `sphinx-autobuild docs build/docs` e depois acessar via http://<host>/docs.

**Comment by caiosba** [comment]
Eu estava tentando fazer a documentação reutilizar os templates Jinja da aplicação Django diretamente, mas isso estava complicado porque muitas variáveis não estão definidas no contexto do Sphinx (por exemplo, o objeto `request`). Então eu fui por um caminho alternativo que foi implementar a rota `/docs` na própria aplicação Django, e esta rota, que utiliza os templates da aplicação, contém um `<iframe>` auto-redimensionável para o seu conteúdo que carrega os arquivos estáticos da documentação, definido em uma outra rota `/static-docs`. Assim, não perdemos também a informação do usuário logado e não logado. Acho que ficou uma boa solução... reaproveita o código e é fácil de manter. O GIF abaixo mostra como ficou a navegação por enquanto.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/117518/45786133-75356900-bc45-11e8-9098-60241656ec2b.gif)

**Comment by caiosba** [comment]
Partindo agora para implementar a internacionalização.

**Comment by caiosba** [comment]
Implementei a internacionalização! O template Jinja que renderiza o `<iframe>` que carrega a documentação estática contém agora uma variável `lang`. Quando esta variável não é `en-us`, o caminho carregado no `<iframe>` é `static_docs/i18n/<lang>`. Desta forma, quando o locale da aplicação é `pt-br`, a documentação em português será exibida no caminho `/docs`. Ver screenshots abaixo, que mostra o comportamento do endereço `/docs` quando o locale é `en-us` e quando o locale é `pt-br`.

**Inglês:**
![171-en](https://user-images.githubusercontent.com/117518/46120225-1d6aa500-c1e5-11e8-8650-09ca9dc6368a.png)

**Português:**
![171-pt](https://user-images.githubusercontent.com/117518/46120235-265b7680-c1e5-11e8-813b-fbb805c96714.png)

**Comment by caiosba** [comment]
Relembrando o comando para compilar a documentação, a partir da raiz do EJ: `sphinx-build docs build/docs`.

**Comment by caiosba** [comment]
PR marcado para revisão: https://github.com/ejplatform/ej-server/pull/463. Uma coisa é ver se o comando `sphinx-build docs build/docs` será adicionado ao pipeline e/ou à rotina de deployment.
