### ISSUE TITLE
Aplicar idv do CPA na home

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#176]
[Home deslogades](https://projects.invisionapp.com/d/main#/console/14015249/302157283/preview) (deve aparecer para todo usuário deslogado) e [home logada CPA](https://projects.invisionapp.com/d/main#/console/14015249/302157282/preview)

Obs: Utilizar arquitetura de temas documentada na issue #158

**Comment by ricardopoppi** [comment]
Explicando os links (cc @caiosba )
Na deslogada
1) Começar agora vai pro login
2) Fase 1 e Fase 2 vai pro rocket
3) Fase 3 vai pro /conversations

**Comment by caiosba** [comment]
IDV implementada para a home, conforme screenshot em anexo (abstrair o card de conversas, que está sendo implementado em #179 .
![screencapture-localhost-8000-start-2018-06-19-23_17_38](https://user-images.githubusercontent.com/117518/41634461-4966b860-741a-11e8-9c91-13f42d60758b.png)
