### ISSUE TITLE
Aplicar idv do CPA no menu lateral

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#177]
[Menu deslogado](https://projects.invisionapp.com/d/main#/console/14015249/302157271/preview) e [menu logado CPA](https://projects.invisionapp.com/d/main#/console/14015249/302157277/comments)

Obs: Utilizar arquitetura de temas documentada na issue #158

**Comment by lucasssm** [comment]
@ricardopoppi poderia conferir se o menu deslogado está correto mesmo? Alguns links ali são discutíveis de estarem presentes... como o de Sair(Deslogar)!

**Comment by ricardopoppi** [comment]
Tem razão @lucasssm! Comentei lá [no deslogado](https://projects.invisionapp.com/d/main#/console/14015249/302157271/comments). Basicamente cai Painel (que tava até com o ícone errado) e o "Sair" cai tb.

[No logado](https://projects.invisionapp.com/d/main#/console/14015249/302157277/comments/99500250), observe que tinha comentado tb. Onde está "Canais" vira "Painel".

Não tinha me atentado a esses errinhos do deslogado, desculpe. Agora acho que vc já tem tudo pra seguir. Qq coisa me avisa

**Comment by lucasssm** [comment]
Fiz aqui do jeito que achei certo... se for pra fazer idêntico ao idv, me deem um toque! Vou deixar a issue aberta esperando a resposta!
Deslogado:
![image](https://user-images.githubusercontent.com/16053704/41614128-02c849ec-73ce-11e8-9493-2ccecf25033a.png)

Logado: 
![image](https://user-images.githubusercontent.com/16053704/41614186-28acf004-73ce-11e8-9784-9df4e37b3cd0.png)

Logado como administrador:
![image](https://user-images.githubusercontent.com/16053704/41614215-3c1c16ce-73ce-11e8-996c-c31ead041ada.png)
![image](https://user-images.githubusercontent.com/16053704/41614247-577d2368-73ce-11e8-8286-6c921358abf4.png)

**Comment by ricardopoppi** [comment]
Perfecto!
