### ISSUE TITLE
Aplicar idv do CPA na tela de perfil

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#178]
Tela de perfil: (i) [User ainda não comentou](https://projects.invisionapp.com/d/main#/console/14015249/302157269/preview), (ii) [User comentou](https://projects.invisionapp.com/d/main#/console/14015249/302157268/preview), (iii) [Visualização de trofeus](https://projects.invisionapp.com/d/main#/console/14015249/302157266/preview), (iv) [Visualização de contribuições](https://projects.invisionapp.com/d/main#/console/14015249/302157267/preview)

Obs: Utilizar arquitetura de temas documentada na issue #158

**Comment by lucasssm** [comment]
![image](https://user-images.githubusercontent.com/16053704/41925311-a324f65a-7942-11e8-9971-c2228e871850.png)
![image](https://user-images.githubusercontent.com/16053704/41925326-ae14ce32-7942-11e8-97fe-976ef731f68f.png)
![image](https://user-images.githubusercontent.com/16053704/41925334-b5302a86-7942-11e8-926a-dd645a448b78.png)
![image](https://user-images.githubusercontent.com/16053704/41925342-bb789dce-7942-11e8-81ef-1b5b1bffec68.png)

Finalizado!

Como pequena pendência, que resolverei logo após a master descongelar:
Esconder a parte de "Meus comentários (x)" Caso não há comentários.

Como pendências a serem resolvidas depois: Todos os meta-dados relacionados à gamificação.
