### ISSUE TITLE
Aplicar idv do CPA nas internas de conversa

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#180]
Internas de conversa [user deslogado](https://projects.invisionapp.com/d/main#/console/14015249/302157279/preview) e [user logado CPA](https://projects.invisionapp.com/d/main#/console/14015249/302157278/preview) (ignorando por agora os botões de edição e solicitar relatório do header)

Obs: Utilizar arquitetura de temas documentada na issue #158

**Comment by caiosba** [comment]
Feito, conforme screenshot em anexo.
![screencapture-localhost-8000-conversations-school-system-2018-06-20-01_27_55](https://user-images.githubusercontent.com/117518/41637282-75fcb870-7429-11e8-9b6b-5cff810cd592.png)
