### ISSUE TITLE
Solução para o header liberar espaço útil no app

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#183]
Hoje no EJ, somados o header e o footer-menu, a área util de utilização do app fica bem reduzida. Possíveis soluções para o footer-menu, trataremos em outra issue. Essa é focada no header.

Quais as possíveis soluções? (cc @luizapeixe @Heloisecs @fabiommendes @caiosba @leandronunes) 
- Header auto-ocultar qdo o usuário fizer scroll pra baixo?
- [...que mais?]

**Comment by luizapeixe** [comment]
A sugestão de ocultar o header no scroll-down é uma boa! E re-exibir na ação do scroll-up.

Outra solução seria diminuir um pouco a altura do header e da navbar. Hoje eles têm 80px de altura. Simulei aqui rapidamente como ficaria com o header com 70px e a navbar com 65px pra gente ter uma ideia:

![captura de tela 2018-06-22 as 11 16 49](https://user-images.githubusercontent.com/6249788/41781606-60e520b2-760e-11e8-94cc-b672913cf65e.png)

**Comment by ricardopoppi** [comment]
Acho que podemos ficar com as duas opções. @luizapeixe pode explicar mais analiticamente como seria a animação de ocultar/desocultar do header no scroll?

**Comment by luizapeixe** [comment]
A ideia desse ocultar/desocultar seria que o header permanecesse sticky enquanto o user scrolla o site para baixo, porém se oculta (movendo-se pra cima) qnd o user scrolla o site para cima. Procurei algum site que pudesse exemplificar essa ideia mas não encontrei. No entanto, acabei repensando essa solução e tenho uma nova ideia pra sugerir:

Penso que é interessante a gente manter o header sempre visível (agora com 70px de altura) principalmente porque o header apresenta nossa logo e é importante nesse momento que a gente reafirme nossa logo e identidade visual o máximo possível. Então minha outra sugestão para otimizar o espaço de exibição na versão mobile é que a gente oculte _a navbar_ (ou a parte de nomenclatura dela) no momento de scroll-down. E então, no momento de scroll-up a navbar volta a aparecer totalmente.

Explicando melhor: Penso que quando o usuário está consumindo o site para baixo (vamos chamar isso de scroll-down) ele esta lendo ou acompanhando algo naquela página, talvez lendo um texto ou simplesmente seguindo a ordem de leitura padrão (de cima pra baixo, da esquerda pra direita). Quando o user scrolla o site pra cima, talvez seja porque está buscando algo diferente do conteúdo daquela página específica, estão faz sentido que outras possibilidades de páginas sejam reapresentadas ao user, no caso, nossa navbar.

O que vocês acham? Por favor fiquem a vontade para debater, discordar, complementar, mostrar referencias... :)

**Comment by ricardopoppi** [comment]
Eu gostei das premissas da segunda solução: manter header com logo e ocultar temporariamente navbar. Minha preocupação é que essa segunda opção pode ser pouco intuitiva. Explico:

1) Fazer scroll-down e o header sumir é intuitivo pois o usuário fica com a impressão de que "jogou" ele pra fora da tela. 
2) Fazer scroll-up e o header aparecer tb é intuitivo pois o usuário fica com a impressão de que "resgatou" ele de volta
3) Porém, fazer scroll-down e a navbar sumir pode dar um tilt na cabeça do usuário pois a navbar assumiu um movimento contrário ao do scroll.

Essa foi minha única ressalva, ainda que eu concorde com a premissa dessa segunda proposta. Tem algum jeito de minimizar esse efeito anti-intuitivo? Como opinam aqui @caiosba e @leandronunes ?
