### ISSUE TITLE
Retirar a necessidade de username do cadastro

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#184]
Para simplificar a tela de cadastro, manteremos apenas o nome e email (além da senha). Essa tarefa tem 3 fases:

- [x] O username deve ser gerado automaticamente pelo django no ato do cadastro e não será mais usado como slug na url da timeline de conversas individual do usuário;
- [x] A timeline do usuário só será criada quando ele criar a primeira conversa. Nesse caso o form de criação de conversa deve solicitar ao usuário o slug da sua timeline de conversas;
- [x] Para as outras conversas que o usuário criar, essa informação do slug não deve ser mais solicitada pois cada usuário comum só terá uma timeline de conversas

(pode complementar aqui @fabiommendes se tiver mais orientações a esse respeito?)

**Comment by rodrigocam** [comment]
Bolei uma lógica para gerar username que ficou da seguinte forma:

- Tenta user o primeiro nome em lower case
- Tenta usar o email normalizado (trocando onde tem '.' por '_')
- Tenta fazer uma combinação de primeiro nome com segundo nome, segundo nome com terceiro nome e assim em diante
- Tenta usar o email normalizado + um número ex: joacir.toledo@yahoo.com -> joacir_toledo47

Se tiverem alguma ideia de mais alguma lógica podem dizer! o/

**Comment by ricardopoppi** [comment]
@fabiommendes pode comentar?

**Comment by rodrigocam** [comment]
Conclui os critérios de aceitação listadas acima. Atualmente o fluxo está da seguinte forma:
- Todo usuário possui um campo board_name
- Usuário se cadastra (com a lógica explicada acima, geramos um username), board_name então é nulo
- Ao acessar /conversations/add/ é exibido um formulário com um campo para registrar um nome para seu board
- Ao acessar /nome_do_board/ todas as conversas do usuário que possui esse board são listadas
- Novas conversas não exibem o campo board_name no formulário

**Comment by ricardopoppi** [comment]
peço ao @fabiommendes opinar aqui
