### ISSUE TITLE
Incluir uma animação na transição dos cards de comentários

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#185]
Hoje os cards estão carregando de forma "seca", deixando pouco evidente para o usuário que houve uma mudança no comentário que está votando. @luizapeixe @caiosba @leandronunes podem incluir referencias de animações pra usarmos? Talvez seja o momento de usar algo pronto em react.

**Comment by luizapeixe** [comment]
Que tal algo assim:

![animacao_comentarios2](https://user-images.githubusercontent.com/6249788/42097893-b489ffd6-7b8f-11e8-8545-83a726e33cf8.gif)

no HOVER o botão assume a cor no background da opção e no CLICK a nomenclatura também adota a cor específica, daí o comentário votado se desloca pra esquerda e o próximo comentário aparece deslizando da direita. O counter acima da autoria do comentário vai acompanhando a progressão das votações

**Comment by ricardopoppi** [comment]
Sensacional. Passando para desenvolvimento, nessa mesma issue, mantendo o assign pro @caiosba

**Comment by caiosba** [comment]
Implementei a animação.

**Comment by caiosba** [comment]
Reabrindo para corrigir problema de margens na animação.

**Comment by caiosba** [comment]
Corrigido!
