### ISSUE TITLE
Incluir um indicador de progresso no deck de votação em comentários

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#187]
Para que o usuário tenha noção de quantos comentários faltam pra ele votar, precisamos incluir uma indicação numérica ou visual ao usuário. @luizapeixe pode atualizar um dos wires de interna de conversa com uma ou mais propostas pra isso?

**Comment by luizapeixe** [comment]
Que tal algo assim?

![captura de tela 2018-06-21 as 20 13 20](https://user-images.githubusercontent.com/6249788/41749923-9724f5a0-758f-11e8-9809-cfeaffe0ec38.png)

Minha sugestão é que esse counter sirva pro user saber quantos votos mais ele precisa conceder para poder ganhar algo da gameficação, seja um badget ou nível de badget. Daí então quando o user atingir o limite do "set de comentários p/ receber recompensa", ele recebe uma notificação informando da conquista, e um novo limite pode ser apresentado pra ele votar, ainda na mesma conversa.

(vale checar com pessoal da gameficação se isso condiz com nossas estratégias)

**Comment by ricardopoppi** [comment]
Faz sentido sim, e provavelmente a gamificação fará uso de "milestones" intermediários pra voto. Por hora  vou assignar a issue pro @caiosba pra ele deixar no backlog de implementação

**Comment by caiosba** [comment]
Feito!
