### ISSUE TITLE
Harmonizar os espaçamentos na tela de conversa

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#188]
Os espaçamentos na interna de conversa estão assimétricos, podendo gerar algum desconforto à alguns usuários. Abaixo uma imagem com indicações sobre os locais de espaçamento. Aqui o [wireframe da mesma tela](https://projects.invisionapp.com/d/main#/console/13863876/299689436/preview) para ter como referencia

![whatsapp image 2018-06-13 at 08 47 27](https://user-images.githubusercontent.com/1162183/41748114-d9c159fc-7586-11e8-8411-4aa37899e5f6.jpeg)

**Comment by caiosba** [comment]
Feito!
