### ISSUE TITLE
Itens faltantes e interação ruim no submenu de conversas no menu lateral

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#189]
O clique no submenu está fora de foco gerando muita dificuldade para baixar o "drop down".

![whatsapp image 2018-06-13 at 09 09 14](https://user-images.githubusercontent.com/1162183/41748202-32cf6a7a-7587-11e8-93df-0c2d413adc20.jpeg)

**Comment by lucasssm** [comment]
https://projects.invisionapp.com/d/main#/console/14015249/302157277/preview
De acordo com essa tela do Invision, o dropdown deixou de existir! Já está implementado de acordo com a idv. Me corrijam e abram a issue de novo se eu estiver errado!

**Comment by ricardopoppi** [comment]
@lucasssm pra usuário admin ele existe veja as imagens abaixo. Três dessas opções deveriam aparecer para o usuário comum:
1) Suas conversas: Somente quando o usuário tiver criado alguma conversa. Esse link deve direcioná-lo pra timeline dele /_username_
2) Criar conversa: A tela de criação de nova conversa
3) Conversas favoritas: Ainda não foi implementado no backend (issue #222) mas deve levar pra essa área no perfil do usuário

![photo_2018-06-28_13-13-08](https://user-images.githubusercontent.com/1162183/42046792-089f8f02-7ad5-11e8-87cd-0861bf4ac7fe.jpg)

![photo_2018-06-28_13-13-07](https://user-images.githubusercontent.com/1162183/42046804-0e0d8336-7ad5-11e8-9689-4229a4d22d1f.jpg)

**Comment by arthurbdiniz** [comment]
Foram reduzidas as margins assim como requisitado e adicionado novos botões ao para oos usuários comuns, assim como o link para adicionar uma nova conversa.

Link das conversas favoritas continuam estatico pela falta da rota(implementação)

- Painel visto pelo admin
![image](https://user-images.githubusercontent.com/18387694/42330366-e5d5aa9e-8027-11e8-8c30-f46d7cfbce5b.png)

- Painel visto pelo usuário comum
![image](https://user-images.githubusercontent.com/18387694/42330419-01391604-8028-11e8-8591-fdf22fe18bcf.png)

**Comment by ricardopoppi** [comment]
Ótimo. Estou fechando a issue pra ela ir a homolog. Assim que eu testar no dev, passo pra done. Bom trabalho @arthurbdiniz ! (cc @lucasssm )
