### ISSUE TITLE
No menu lateral, priorizar o que é mais relevante para o usuário

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#190]
Imagino que a ordem poderia ser: inicio, perfil, conversas, conteúdos estáticos para o final. Mas aproveito para consultar a @luizapeixe sobre isso, antes de seguir para os ajustes no código

**Comment by luizapeixe** [comment]
concordo com sua sugestão de ordem, @ricardopoppi !

**Comment by ricardopoppi** [comment]
Maravilha @luizapeixe então issue liberada pro @lucasssm ajustar a ordem

**Comment by lucasssm** [comment]
![image](https://user-images.githubusercontent.com/16053704/42044738-20237a6c-7ad0-11e8-9ff8-a9f76c813e6f.png)
Feito!
