### ISSUE TITLE
Aplicar margem e/ou estilos nos conteúdos estáticos

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#191]
A visualização dos conteúdos estáticos do app (carregados via admin) está sem margem. Eventualmente pode ser aplicado algum estilo genérico que possa valer para todos os conteúdos estáticos carregados. Peço a @luizapeixe recomendar.

![whatsapp image 2018-06-13 at 09 18 28](https://user-images.githubusercontent.com/1162183/41749968-d1817854-758f-11e8-8173-deddc7f13f55.jpeg)

**Comment by luizapeixe** [comment]
Segue uma primeira proposta de estilo pra página de conteúdos estático:

https://projects.invisionapp.com/share/V9GNMI1BG2F#/screens/304773998/comments

Nos comentários já descrevo algumas propriedades de CSS

**Comment by ricardopoppi** [comment]
boa. com isso o @lucasssm já pode considerar como backlog de implementação

**Comment by lucasssm** [comment]
Concluído!

**Comment by lucasssm** [comment]
![image](https://user-images.githubusercontent.com/16053704/42044703-0e2483ec-7ad0-11e8-93a3-3fd12c8e62dc.png)
