### ISSUE TITLE
Ocultar o menu-footer quando for ativado o teclado mobile

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#192]
Imagem exemplo, um usuário tentando escrever um comentário. A presença do menu junto com o footer prejudica muito a interação. Essa issue se relaciona com a issue #193 a respeito de alguma solução auto-ocultar padrão para o menu-footer.

![photo_2018-06-21_20-26-15](https://user-images.githubusercontent.com/1162183/41750263-5f47fe1e-7591-11e8-92fd-b3187045ac94.jpg)

**Comment by caiosba** [comment]
Feito!
