### ISSUE TITLE
Avaliação de usabilidade e ux do menu-footer

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#193]
Avaliar a usabilidade. Será que ele ficaria melhor se auto-ocultasse no scroll? Talvez seja uma perda grande já que ele dá acesso rapido a painel (importante para o CPA) e perfil (importante para a gamificação)...

Será que temos alguma alternativa?

**Comment by luizapeixe** [comment]
Concordo que perdemos muito ocultando a navbar. Hoje ela tem 80px de altura, na [issue #183](https://github.com/ejplatform/ej-server/issues/183) simulei uma situação em que o footer tem 65px de altura. 

Outra coisa sobre a ux da navbar, é sobre as cores que estamos utilizando. Lembro que numa versão mais antiga do design genérico, a @Heloisecs havia testado os ícones com uma cor mais escura. Acredito que a solução anterior, com a cor escura, proporciona melhor leitura dos ícones, por causa do contraste do tom escuro com o background branco. Era algo assim:
![captura de tela 2018-06-22 as 11 29 16](https://user-images.githubusercontent.com/6249788/41782089-92ab113c-760f-11e8-9f22-8fea600b7d79.png)

Gostaria de saber se ainda temos tempo hábil para experimentar nessa área

**Comment by ricardopoppi** [comment]
Oi @luizapeixe temos esse tempo sim, pois a essa navbar foi um ponto crítico pra melhorar, então vale o esforço. Pode organizar suas propostas no protótipo e linkar aqui, que a gente decide a melhor e encaminha pra implementação

**Comment by luizapeixe** [comment]
Depois de alguns testes, acabei chegando nesse preferido:

![captura de tela 2018-06-25 as 15 28 30](https://user-images.githubusercontent.com/6249788/41868447-7fc9eece-788c-11e8-858a-0433a47f3623.png)

Essa solução usa o tom escuro nas bordas, para dar o máximo de contraste dentro da nossa paleta de cores, e usa também o azul (#A3D8DD) em preenchimentos pontuais em cada um dos ícones da navbar, além do rosa no circulo que indica a quantidade de notificações não-lidas. A nomenclatura dos ícones agora seguem as seguintes orientações:
font-family: Raleway-Bold;
font-size: 11px;
color: #042049;
text-transform: uppercase;

O que acham?

**Comment by ricardopoppi** [comment]
Ficou bom sim @luizapeixe ! Vamos tocar essa. Pode atualizar no invision e indicar aqui o link do wire? Valeu!

**Comment by luizapeixe** [comment]
pronto! Atualizei as telas no invision com a última versão do footer e do header -> https://invis.io/V9GNMI1BG2F

**Comment by ricardopoppi** [comment]
Maravilha. Issue específica de desenvolvimento criada, fechando essa
