### ISSUE TITLE
Limitar largura da versão desktop considerando largura de "tablet"

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#194]
Limitar a largura da versão desktop para evitar desenvolvimento de uma versão desktop full. Atenção especial ao header atualmente quebrado na dimensão de largura sem menu hamburger

**Comment by caiosba** [comment]
Feito!

**Comment by ricardopoppi** [comment]
@caiosba talvez tenha faltado aplicar o ajuste ao header no tema CPA, olha:

Tema Ej generico:

![captura de tela de 2018-07-08 12-45-14](https://user-images.githubusercontent.com/1162183/42421495-e1ae187a-82ac-11e8-92b0-25aacd02a602.png)


Tema CPA:

![captura de tela de 2018-07-08 12-45-22](https://user-images.githubusercontent.com/1162183/42421498-eb912972-82ac-11e8-8754-03a83b5d731c.png)

**Comment by caiosba** [comment]
Corrigido! Agora o menu hambúrguer vai sempre aparecer nos dois temas independentemente da largura da tela.

**Comment by ricardopoppi** [comment]
boa solução @caiosba !
