### ISSUE TITLE
Rodapé com transparência

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#196]
Rodapé está transparente. Img de um teste com chrome pra android

![photo_2018-06-21_21-40-43](https://user-images.githubusercontent.com/1162183/41752116-ccfe8c2a-759b-11e8-9640-0140e535f25f.jpg)

**Comment by caiosba** [comment]
Corrigido nos temas CPA e EJ, conforme screenshots em anexo.
![screenshot_20180704-095655](https://user-images.githubusercontent.com/117518/42278452-456c6054-7f71-11e8-9d73-21b33246f7c0.png)
![screenshot_20180704-095319](https://user-images.githubusercontent.com/117518/42278453-458e786a-7f71-11e8-8d93-b609ba6ac51d.png)
