### ISSUE TITLE
Formular uma versão de tema pro EJ acessível

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#198]
Para termos uma versão de alto contraste e fontes maiores, será necessário gerar novos wireframes ou é possível aplicar uma regra padrão de alto contraste e aumento de fonte para alguns elementos?

Também precisamos definir onde o botão de chaveamento aparece na interface

**Comment by luizapeixe** [comment]
Acredito que para aumento de fonte seja possível seguir um padrão para todo o site entretanto para o alto contraste vamos precisar adaptar pontualmente alguns elementos, em especial aqueles que estão aplicados em background coloridos.

Segundo a [W3C](https://www.w3.org/TR/WCAG20/#visual-audio-contrast), para uma acessibilidade ideal os textos e elementos devem ter idealmente um valor de 4.5 ou mais de contraste. Analisei nossos layouts [medindo](http://contrast-ratio.com/#%2330BFD3-on-%23C4F2F4) a relação de contraste dos nossos textos e listei alguns pontos mais críticos. 

Segue abaixo um esboço da situação atual (do lado esquerdo) e possíveis soluções (do lado direito).  Espero que os prints estejam suficientemente compreensíveis! Me avisem se acharem confuso

### • Lista de conversas:
![1-lista_de_conversas](https://user-images.githubusercontent.com/6249788/42061917-2998e686-7b02-11e8-895c-eae7ef899cbd.png)

### • Página interna da conversa:
![2-interna_conversa1](https://user-images.githubusercontent.com/6249788/42061922-3507f7dc-7b02-11e8-8f2a-1864671016e8.png)
![3-interna_conversa2](https://user-images.githubusercontent.com/6249788/42061942-430f9d08-7b02-11e8-82c5-4e7372f7cbbe.png)

### • Perfil do user:
![5-perfil1](https://user-images.githubusercontent.com/6249788/42061951-4f5b8108-7b02-11e8-85f8-2278d7ff444a.png)
![6-perfil2](https://user-images.githubusercontent.com/6249788/42061955-53880a8a-7b02-11e8-94dd-37637c11ffef.png)
![7-perfil3](https://user-images.githubusercontent.com/6249788/42061962-5626e946-7b02-11e8-994c-c1be16d9ba49.png)

### • Menu:
Esse menu já considera a ordem sugerida na [issue 190](https://github.com/ejplatform/ej-server/issues/190#issuecomment-401078299), porém inclui também os itens NOTIFICAÇÕES e DOCUMENTAÇÃO, que ainda não estavam considerados até a última versão implementada do menu. Ps.: ainda não subi essa última versão de menu no invision! Farei isso entre hoje e segunda-feira (me avisem se houver urgência nessa demanda)
![4-menu](https://user-images.githubusercontent.com/6249788/42062168-17a1d270-7b03-11e8-8acc-651a8c1a1d9a.png)

### • Footer e Navbar:
A versão de solução já considera a nova versão de navbar aprovada na [issue 193](https://github.com/ejplatform/ej-server/issues/193). Ps.: Ainda não atualizei as telas no invision com a nova navbar! Farei isso entre hoje e segunda-feira (me avisem se houver urgência nessa demanda)
![8-footer_navbar](https://user-images.githubusercontent.com/6249788/42062182-2004cb3e-7b03-11e8-8cd7-986cef97a44f.png)

**Comment by ricardopoppi** [comment]
Boa, vou pedir pro @caiosba e @lucasssm opinarem aqui

**Comment by caiosba** [comment]
Me parece bom e possível de ser implementado dentro da infraestrutura atual de temas.

**Comment by lucasssm** [comment]
Acho que além das cores, poderiamos aumentar o tamanho das fontes?

**Comment by caiosba** [comment]
Ontem conversamos no Telegram e chegamos à seguinte conclusão com relação a implementação disso: como o logo e os ícones do tema em alto contraste devem ser adaptados para os temas CPA e EJ, e como deve ser possível habilitar o tema em alto contraste em tempo de execução, ele não será um tema propriamente dito. Será um arquivo `_hicontrast.scss` dentro dos temas existentes, que aplica regras de estilo que se aplicam quando o `<body>` tem uma classe `hicontrast`. Desta forma, a funcionalidade de habilitar/desabilitar o alto contraste se limita a adicionar/remover a classe `hicontrast` do `<body>`.

**Comment by lucashm** [comment]
Oi! Estou progredindo com o tema acessível... Com relação ao aumento e diminuição de fontes (+1px, -1px) creio que seja possível sim! Mas vou deixar como uma issue externa, separada do tema de alto contraste mesmo... Enfim, preciso de alguns assets para concluir o tema. Até o momento, segue os que eu preciso:
![image](https://user-images.githubusercontent.com/16053704/42631654-241a0d5c-85b1-11e8-9cb9-0e3403587d8e.png)
![image](https://user-images.githubusercontent.com/16053704/42631660-2baab472-85b1-11e8-8140-e68d8fae1abb.png)
(As bolinhas com o fundo azul escuro)

**Comment by lucashm** [comment]
https://github.com/ejplatform/ej-server/pull/235
Finalizado!

**Comment by ricardopoppi** [comment]
aeeeeeeee sensacional! <3
