### ISSUE TITLE
Implementar login por redes sociais facebook e twitter

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#199]
Tanto no generico quanto no cpa

Tela de login do generico com os botões: https://projects.invisionapp.com/d/main#/console/14872865/324346877/preview

**Comment by ricardopoppi** [comment]
É dev. aguardemos o certificado

**Comment by caiosba** [comment]
Praticamente concluído! Ver video em: https://www.youtube.com/watch?v=zdmQziqQJkk. A única coisa que falta fazer é estilizar a tela de e-mail após registro com Twitter. Também escrevi documentação em português e em inglês explicando como faz para configurar os apps de Twitter e Facebook para login (screenshots em anexo).
![199-docs-en](https://user-images.githubusercontent.com/117518/47578531-015f3e00-d920-11e8-8bab-e08394a9ba3d.png)
![199-docs-pt](https://user-images.githubusercontent.com/117518/47578533-01f7d480-d920-11e8-896a-c0badcbb7a1c.png)

**Comment by ricardopoppi** [comment]
sensacional @caiosba! Observa que nos wireframes é pedido o login por google tb

**Comment by caiosba** [comment]
PR criado e pronto para revisão: https://github.com/ejplatform/ej-server/pull/594.
Após deploy, é necessário criar os apps e configurar, tanto para Dev quanto para Produção.
Poppi, por favor atribuir novamente para mim (ou abrir uma nova tarefa) quando for a hora de fazer isso.
