### ISSUE TITLE
Criar API RESTful

### ISSUE THREAD

**Issue by fabiommendes** [ejplatform/ej-server#20]
O EJ por enquanto é uma API REST nível 2, queremos subir um nível :)

* https://martinfowler.com/articles/richardsonMaturityModel.html
* https://www.thoughtworks.com/pt/radar/techniques/anemic-rest

Issues:
* [x] Refatorar o código para utilizar o router do DRF sempre que possível
* [x] Versionar a api no endpoint /api/v1/*
* [x] Criar um router global em config.api
* [x] Utilizar recursos hiperlinkados
* [x] Verificar conflitos com o front para criarmos endpoint RPC quando necessários

**Comment by rodrigocam** [comment]
Alguns testes quebraram pela implementação do versionamento por namespace e pelos recursos hyperlinkados, estes testes foram atualmente corrigidos. :)
