### ISSUE TITLE
Alterar o conteúdo da home do CPA de conversas participativas para conversas públicas

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#203]

**Comment by arthurbdiniz** [comment]
![image](https://user-images.githubusercontent.com/18387694/42836935-dcaa66a8-89d2-11e8-9ae4-78d943ac101b.png)

@ricardopoppi você quis dizer para mudar esse titulo para **conversas participativas** para **conversas públicas**

**Comment by ricardopoppi** [comment]
Fechando essa issue pois as alterações de conteúdo estão relacionadas a issue de conteúdo #247
