### ISSUE TITLE
Verificar ítens não traduzidos na interface do rocket chat

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#206]

**Comment by leandronunes** [comment]
Precisando atualizar a versão do rocket, pois na nova versão vários erros de tradução foram corrigidos.
Ainda encontrei alguns erros, mas numa quantidade muito menor que na versão que temos em produção atualmente.

Criei uma issue de bug no projeto do rocket chat informando os erros encontrados:

https://github.com/RocketChat/Rocket.Chat/issues/11317
