### ISSUE TITLE
Conteúdo dos campos de perfil ficaram ilegíveis

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#208]
Peço a @Heloisecs propor uma alternativa pra destacar mais os conteúdos do perfil, no contexto da idv do CPA

Imagem de como está:

![photo_2018-06-21_22-08-17](https://user-images.githubusercontent.com/1162183/41752722-9c49c9ec-759f-11e8-8305-a77a031f911f.jpg)

**Comment by Heloisecs** [comment]
@ricardopoppi isso foi com essas cores? #D4F7F5 de fundo e #30BEC0 letra?
![image](https://user-images.githubusercontent.com/9471715/41788748-125ad3a0-7623-11e8-88b8-9ba76c3bb279.png)

**Comment by Heloisecs** [comment]
ps.: A cor da fonte padrão parece azul marinho no seu print, mas é aquele roxo CPA #3F1B53

**Comment by ricardopoppi** [comment]
hummm tem razão a implementação ficou diferente, nos wires tá bem mais legível. peço ao @lucasssm e @caiosba considerarem esse ajuste nas cores que foram implementadas

**Comment by caiosba** [comment]
Feito!
