### ISSUE TITLE
Audio enviado nos canais do rocket não tem som

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#211]
Reproduz mas o volume fica aparentemente zerado. Foram testados envios e recebimentos por vários tipos de celular.

**Comment by leandronunes** [comment]
o audio não está funcionando via mobile

**Comment by ricardopoppi** [comment]
@leandronunes pode abrir essa issue lá no rocket e registrar ela aqui?

**Comment by ricardopoppi** [comment]
@leandronunes será que já resolveram esse bug lá no rocket?

**Comment by leandronunes** [comment]
@ricardopoppi vou assinar para verificar
