### ISSUE TITLE
Melhorar a usabilidade do botão "voltar" do header EJ quando iframe do rocket estiver carregado

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#213]
Melhorar a usabilidade do botão "voltar" do header do EJ quando usando o rocket. Ele teria que controlar a interação dentro do iframe.

Para simular:
1) Entre no painel (diretório de canais)
2) Escolha um canal
3) Clique no botão voltar

**Comment by leandronunes** [comment]
Foram realizados ajustes na interface de administração do rocket para realizar pequenos ajustes de layout e navegação.
Estes arquivo se encontram em:
https://github.com/ejplatform/ej-server/tree/master/docker/extensions

Um tutorial de como realizar a configuração do rocket se encontra aqui:

https://drive.google.com/file/d/1LoEMIU4XwaypUJe1D2na8R1Qf4Fwxgy4/view
