### ISSUE TITLE
Melhorar a interação para fechar o menu lateral do rocket

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#214]
Melhorar a interação do menu lateral do rocket pois quando ele está aberto não fica claro como deve ser ocultado (botão fechar ou ocultar). 

Pode ter relação com a issue #213 sobre melhorar o botão voltar do EJ se ele puder puder controlar interações no rocket e com ele, fechar o menu.

**Comment by leandronunes** [comment]
@luizapeixe 
Precisamos de uma solução de UX para esta issue:

Fiz as duas opções abaixo para você ter uma ideia do que pode ser feito.

https://drive.google.com/file/d/1q3Vw3t6u06ZtNeALCvHC1kfuMJfvT4Qr/view

https://drive.google.com/file/d/1AIxk-p3wV0yg64RBBSjiwniTf10Aap6s/view

**Comment by luizapeixe** [comment]
@leandronunes gosto mais da primeira opção [https://drive.google.com/file/d/1q3Vw3t6u06ZtNeALCvHC1kfuMJfvT4Qr/view]. A seta deixa 100% evidente pro user como sair do menu. Uma dúvida: se o user clicar na lateral direita (fora do menu, no layout que foi sobreposto) o menu também fecha né?

**Comment by leandronunes** [comment]
@luizapeixe 
sobre isso:  "se o user clicar na lateral direita (fora do menu, no layout que foi sobreposto) o menu também fecha né?"
fecha também continua como é hoje.

**Comment by leandronunes** [comment]
Foram realizados ajustes na interface de administração do rocket para realizar pequenos ajustes de layout e navegação.
Estes arquivo se encontram em:
https://github.com/ejplatform/ej-server/tree/master/docker/extensions

Um tutorial de como realizar a configuração do rocket se encontra aqui:

https://drive.google.com/file/d/1LoEMIU4XwaypUJe1D2na8R1Qf4Fwxgy4/view
