### ISSUE TITLE
Permitir override de settings no tema

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#216]
Acho que esse deve ser o objetivo: configura o arquivo _overrides.scss na pasta de tema e vc ganha um tema novo :)

**Comment by fabiommendes** [comment]
Esse é o objetivo para a parte scss do tema ;)
Implementei o override de settings para as configurações agora. Se tiver um arquivo settings.py na pasta do tema, ele inclui as variáveis definidas lá no settings global.
