### ISSUE TITLE
Produzir um guia de aplicacao da estrutura de temas do EJ para facilitar futuras aplicações do tema

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#220]
- [x] Validar a estrutura semântica do tema (discutir quais elementos tem cores comuns, fontes comuns, espaçamentos comuns nos temas do EJ-gen e CPA)
- [x] Simplificar a aplicação dos temas CPA e EJ
- [ ] Documentar (criar um guia para aplicação de temas)

**Comment by caiosba** [comment]
Infraestrutura da documentação sendo tratada em #171
