### ISSUE TITLE
Atualizar navbar com a nova versão 

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#223]
Nova versão foi concebida nesse comentário https://github.com/ejplatform/ej-server/issues/193#issuecomment-400052860 e publicada no invision: https://invis.io/V9GNMI1BG2F

**Comment by luizapeixe** [comment]
novos ícones em .svg nesse zip:
[navbar_icons.zip](https://github.com/ejplatform/ej-server/files/2156371/navbar_icons.zip)

**Comment by caiosba** [comment]
Feito!
