### ISSUE TITLE
Atualizar imagem docker do rocket chat no servidor de homologação

### ISSUE THREAD

**Issue by leandronunes** [ejplatform/ej-server#224]
para atualizar a imagem basta dá o comando:

docker pull rocketchat/rocket.chat

**Comment by ricardopoppi** [comment]
Marcando o @luanguimaraesla talvez seja algo que o @pablodiegoss e @rodrigocam possam fazer pra exercitar a gestão da infra do EJ

**Comment by ricardopoppi** [comment]
img atualizada por @fabiommendes
