### ISSUE TITLE
Ideias sobre o box-shadow do menu e navigation

### ISSUE THREAD

**Issue by arthurbdiniz** [ejplatform/ej-server#229]
Gostaria de trocar uma ideia sobre o box-shadow do site, percebi que estava muito pequeno e resolvi aumentar para ver se dava um destaque maior, qual a opinião de voces em relação a isso @ricardopoppi @luizapeixe?

### Antes
![image](https://user-images.githubusercontent.com/18387694/42339139-f89b77d0-8040-11e8-90a1-f6bddf986784.png)

![image](https://user-images.githubusercontent.com/18387694/42339150-012ee378-8041-11e8-913d-3cc7089ed641.png)

### Depois

![image](https://user-images.githubusercontent.com/18387694/42339044-a6c76b4e-8040-11e8-8648-9e72bd463346.png)

![image](https://user-images.githubusercontent.com/18387694/42339051-ad21bad0-8040-11e8-9cd0-4dcd3dc46d53.png)

**Comment by luizapeixe** [comment]
obrigada pela sugestão, @arthurbdiniz . Achei que ficou um pouco forte demais. Acho que algo entre as duas soluções pode ser ideal

**Comment by ricardopoppi** [comment]
Gostei do efeito acho que tava faltando mesmo! Gostei da sugestão da @luizapeixe de equilibrar a intensidade. Bom trabalho @arthurbdiniz !

**Comment by arthurbdiniz** [comment]
Box shadow com alpha um pouco mais marcante

![image](https://user-images.githubusercontent.com/18387694/42512014-4e52b6e6-8408-11e8-9fc2-0440fb5c77b9.png)

**Comment by ricardopoppi** [comment]
@arthurbdiniz mto bom. Vai valer para os dois temas da plataforma? (CPA e Generico)

**Comment by arthurbdiniz** [comment]
Vai sim @ricardopoppi
