### ISSUE TITLE
Alinhamento das labels dos inputs de edição de usuário

### ISSUE THREAD

**Issue by arthurbdiniz** [ejplatform/ej-server#230]
As labels de input do usuário estão coladas na borda da tela:
![image](https://user-images.githubusercontent.com/18387694/42339521-0ca604e2-8042-11e8-80af-984563e3e095.png)

Sugiro um alinhamento junto ao texto de input.

**Comment by luizapeixe** [comment]
@arthurbdiniz isso mesmo! Se o input tem margin de 75, o label deve ter também essa margin de 75. Devem idealmente estar alinhados sim.

**Comment by arthurbdiniz** [comment]
Ok @luizapeixe, vou realizar essas mudanças...

**Comment by arthurbdiniz** [comment]
Alinhamento das labels corrigido. @luizapeixe  @ricardopoppi  

![image](https://user-images.githubusercontent.com/18387694/42512190-ce98629c-8408-11e8-8705-df6a3a4b0780.png)
