### ISSUE TITLE
pwa sem ícone 

### ISSUE THREAD

**Issue by lucashm** [ejplatform/ej-server#231]
![9d530a8d-1d99-4d09-a741-559e2b71cc34](https://user-images.githubusercontent.com/16053704/42341821-ba65f510-806a-11e8-9a84-59ec2e5b2d04.jpeg)
Atualmente, tanto a versão do ej quanto a do cpa não contém ícones para seus pwa’s.

**Comment by arthurbdiniz** [comment]
Ja consegui resolver esse problema porem fiquei na duvida qual seria o melhor design, existem duas possibilidades.

### - A primeira seria cortar a logo e retirar as letras EJ assim ficaria menos repetitivo o nome do app

- Logo
 ![design_crop](https://user-images.githubusercontent.com/18387694/42517899-a96ee1e6-8415-11e8-89ef-daf8dafcbc3e.png)

- Icone
![image](https://user-images.githubusercontent.com/18387694/42518280-554f086a-8416-11e8-8d5c-586d23a3f2bf.png)

- Splash Screen
![screenshot_20180710-114224](https://user-images.githubusercontent.com/18387694/42518007-eba3f858-8415-11e8-8307-914e59129f81.png)

- Adicionando site para App
![screenshot_20180710-114213](https://user-images.githubusercontent.com/18387694/42518059-f96d23ba-8415-11e8-965b-624edb7843e6.png)


### - A outra seria manter a logo completa 

- Logo
![design](https://user-images.githubusercontent.com/18387694/42518116-0b57c832-8416-11e8-90b8-8c5a5c7e51af.png)

- Icone
![image](https://user-images.githubusercontent.com/18387694/42518353-7e7ce45a-8416-11e8-9fad-1c45dd46cda6.png)

- Splash Screen
![screenshot_20180710-114139](https://user-images.githubusercontent.com/18387694/42518173-12ef8d32-8416-11e8-874c-80ebbbe3ab93.png)

- Adicionando site para App
![screenshot_20180710-114559](https://user-images.githubusercontent.com/18387694/42518183-19312ad4-8416-11e8-890c-c08c0ac0884d.png)



A minha opnião é de dar o crop das letras EJ e manter apenas as caixas de texto como a logo principal do app.

@ricardopoppi @luizapeixe

**Comment by lucashm** [comment]
Creio que apenas o ícone seja a melhor opção.

**Comment by luizapeixe** [comment]
minha preferida:

![logim](https://user-images.githubusercontent.com/18387694/42518280-554f086a-8416-11e8-8d5c-586d23a3f2bf.png)

**Comment by arthurbdiniz** [comment]
Icone atualizado como a prefência da maioria
