### ISSUE TITLE
Rodapé do EJ genérico com ícones muito próximos da borda

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#233]
Conforme imagem:

![photo_2018-07-13_15-10-56](https://user-images.githubusercontent.com/1162183/42706969-09bab2fa-86af-11e8-898d-4128bd73b35e.jpg)

**Comment by arthurbdiniz** [comment]
@ricardopoppi  essa issue aparentemente já havia sido resolvida porém o que acabou acontecendo com o seu celular é que ele está utilizando o cache.

A nova página já está com o design dessa forma a seguir, bem diferente de como foi mostrado no seu celular.
![image](https://user-images.githubusercontent.com/18387694/42824519-5e7f840a-89b6-11e8-8d46-d65771eefe2d.png)

Case esteja utilizando o google chrome como seu navegador do seu celular para excluir o cache, basta seguir os seguintes passos:

- Menu 
![screenshot_20180717-114241](https://user-images.githubusercontent.com/18387694/42825112-b309946a-89b7-11e8-84b1-5d8435a2e0e8.png)

- Configurações
![screenshot_20180717-114245](https://user-images.githubusercontent.com/18387694/42825147-c3ba4b92-89b7-11e8-9655-9416a3d3696f.png)

- Privacidade
![screenshot_20180717-114309](https://user-images.githubusercontent.com/18387694/42825156-c7324af4-89b7-11e8-9116-39820995c77e.png)

- Limpar Dados de Navegação
![screenshot_20180717-114322](https://user-images.githubusercontent.com/18387694/42825158-c89ac006-89b7-11e8-9865-b9efe4a890eb.png)

Obs: pode ser que seja necessario remover o app da area inicial do celular e adicionar novamente para funcionar.

**Comment by ricardopoppi** [comment]
perfeito @arthurbdiniz obrigado!
