### ISSUE TITLE
Meta Gamificação

### ISSUE THREAD

**Issue by fabiommendes** [ejplatform/ej-server#236]
[ ] Técnicas de gamificação para a métrica "Total de votos"
[ ] Telas das técnicas para a métrica "Total de votos"
[ ] Implementação das telas para a métrica "Total de votos"
[ ] Técnicas de gamificação para a métrica "Índice de borda"
[ ] Telas das técnicas para a métrica "Índice de borda"
[ ] Implementação das telas para a métrica "Índice de borda"

**Comment by ricardopoppi** [comment]
deprecated
