### ISSUE TITLE
Corrigir a navbar do EJ Genérico

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#241]
A navbar do EJ Genérico https://dev.ejplatform.org não deve ter "Painel". Apenas "Conversas" e "Perfil". Veja pelas imagens que a imagem do ítem de perfil está incorreta. Deveria ser o "EJ Cat" mas está com o sino no lugar. 

Ver print do ej generico: https://dev.ejplatform.org
![captura de tela de 2018-07-16 18-00-24](https://user-images.githubusercontent.com/1162183/42783796-700f8942-8923-11e8-879d-2fa889e970cd.png)

Por outro lado, a navbar da versão com o tema da plataforma CPA está correta (https://cpa.dev.ejplatform.org):
![captura de tela de 2018-07-16 17-59-41](https://user-images.githubusercontent.com/1162183/42783692-1b865c0c-8923-11e8-9d80-aa0a8025e8f5.png)

**Comment by caiosba** [comment]
Corrigido!
