### ISSUE TITLE
Bug na visualização de card com textos longos

### ISSUE THREAD

**Issue by leandronunes** [ejplatform/ej-server#242]
O texto está sobrepondo os botões dos cards

![erro](https://user-images.githubusercontent.com/28972/42804456-7e1d371c-897f-11e8-9a07-bf3798d29f35.png)

**Comment by caiosba** [comment]
Corrigido, conforme screenshot em anexo.
![screencapture-localhost-8000-conversations-2018-07-24-11_41_36](https://user-images.githubusercontent.com/117518/43146373-7bed6af8-8f37-11e8-92e2-370c25d11585.png)
