### ISSUE TITLE
Detalhamento dos protocolos de segurança contra fake, robô, conteúdos de ódio etc

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#243]
Guidelines:
1) No ambiente painel CPA (Grupos) só participam os 47 adolescentes, submetidos a um termo de uso sobre condutas aceitas/advertências. O ideal é usar o mesmo protocolo do CPA em si. O que acontece se um adolescente agride outro adolescente do CPA, durante uma reunião por exemplo? Há sanções previstas para isso hoje?

2) No ambiente de consultas, os comentários são pré-moderados, ou seja, discurso de ódio, fakes e robôs serão previamente bloqueados da plataforma

**Comment by parrahenri** [comment]
Tentei incluir essas questões nos Termos de Uso: https://docs.google.com/document/d/1mHWI1mUxAN5S_o89fjAtH__9YRvY9hWwYgRiwbNn-Ww/edit?usp=sharing

**Comment by ricardopoppi** [comment]
@parrahenri já revisei. Vc valida com SNDCA e me indica qdo pudermos carregar essa nova versão na plataforma ok? Enquanto isso mantenho a issue aberta

**Comment by parrahenri** [comment]
@ricardopoppi depende do jurídico em 2 itens, mas tá aprovado:
[TERMOS DE USO_v2.docx](https://github.com/ejplatform/ej-server/files/2276218/TERMOS.DE.USO_v2.docx)

**Comment by parrahenri** [comment]
Lembrando que os docs estáticos estão em: https://github.com/ejplatform/ej-server/issues/307

**Comment by ricardopoppi** [comment]
Maravilha. Como concentramos lá e essa questão foi abordada, estamos fechando essa.
