### ISSUE TITLE
Botões de acessibilidade "Tamanho da Fonte"

### ISSUE THREAD

**Issue by arthurbdiniz** [ejplatform/ej-server#245]
Criação de script para aumentar e diminuir o tamanho da fonte de toda plataforma

**Comment by lucashm** [comment]
![image](https://user-images.githubusercontent.com/16053704/42974687-a52d19a6-8b8e-11e8-8b13-b0e8467eda2f.png)
https://github.com/ejplatform/ej-server/commit/e76945d067f2d4f8b80aca872bdc5c8b704b6c74
https://github.com/ejplatform/ej-server/commit/e9d516d5c91facf5fad08ce825020706cb32a929
Finalizada! Mas pendente a algumas modificações posteriores a serem discutidas.
