### ISSUE TITLE
Customizar termos no rocket: "Canais" vira "Grupos"

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#246]
Hoje a listagem de canais é chamada de "Canais" (ver imagem). O CPA usará o nome "Grupos" para isso.

Esse termo pode ser customizável via admin do rocket @leandronunes?

![photo_2018-07-17_11-25-17](https://user-images.githubusercontent.com/1162183/42823788-ce20b696-89b4-11e8-8235-4437350ecc10.jpg)

**Comment by leandronunes** [comment]
Ajuste realizado na interface de administração do rocket
