### ISSUE TITLE
Ajustar o texto de abertura do painel CPA (home do rocket)

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#247]
Fazer nova proposta de texto sem a confusão do telegram e agregando outras necessidades de comunicação

Atualmente o conteúdo é esse:

Painel CPA
Comitê de Participação Adolescente

Utilize esse espaço para abrir canais de debate em temas específicos onde todas e todos podem entrar, colocar suas próprias ideias e interagir para construir propostas e ações coletivas!

Aqui você pode:

1. criar e participar de CANAIS de diálogo sobre infinitos assuntos
2. interagir nos debates de maneira estruturada, com respostas a comentários, menções a participantes, anexo de documentos e mais!
3. acessar e interagir com os grupos do TELEGRAM integrados aqui no painel

![photo_2018-07-17_11-47-16](https://user-images.githubusercontent.com/1162183/42824960-5e074fac-89b7-11e8-8153-a366dbdad79a.jpg)

**Comment by parrahenri** [comment]
@ricardopoppi perfeito ter anotado pq assim vira issue e a gente só fecha quando tiver sido resolvida. Naquela reunião presencial a Helo ficou de enviar um TXT com todos os conteúdos pra secretaria editar. Pedi que fizesse follow up e essa semana a Felicia disse que vão editar até sexta. Ou seja, virá algo da SNDCA pra olharmos sobre isso.

**Comment by ricardopoppi** [comment]
Na reunião o prazo para envio desses conteúdos atualizados pra gente ficou pra 01/agosto. Essa issue fica em hold até lá

**Comment by parrahenri** [comment]
@ricardopoppi e @Heloisecs esse conteúdo elas sugeriram as mudanças direto naquelas telas do paint, então não tenho um arquivo txt pra anexar, oks? Mas tá resolvida.

**Comment by ricardopoppi** [comment]
Isso @parrahenri - estou re-fechando essa issue pois a atualização desse conteúdo está coberta pela #304
