### ISSUE TITLE
Tomar a decisão sobre a nova proposta de nomenclatura

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#248]
Proposta de nova nomenclatura:

PAINEL CPA é onde existem os GRUPOS
No app são feitas as CONSULTAS

Precisamos que a SNDCA e o Conanda decidam

**Comment by parrahenri** [comment]
Recuperando o histórico. Hoje usamos as palavras:

- CONVERSA
- PAINEL CPA
- Dentro dele o rocket mostra as palavras GRUPOS e CANAIS

A SNDCA achou isso tudo muito confuso e quer:

- Substituir CONVERSA por alguma palavra (com preferência para consulta)
- Unificar GRUPO e CANAL (com preferência para grupo) 

@leandronunes vai olhar a viabilidade de unificar CANAL e GRUPO no Rocket (consulta que @ricardopoppi fez) e daí fazemos uma proposta para apresentar à SNDCA quando o @fabiommendes apresentar a nova versão do app.

**Comment by ricardopoppi** [comment]
@leandronunes vai unificar no rocket via issue #269 

Após reunião com sndca, decidimos que a nomenclatura das conversas/comentários se mantem
