### ISSUE TITLE
Criar páginas de erro estilizadas

### ISSUE THREAD

**Issue by fabiommendes** [ejplatform/ej-server#255]
Criar páginas de erro estilizadas:

* [x] 404 - página não encontrada
* [x] 403 - pemissão negada
* [x] 400 - requisição inválida
* [x] 500 - erro de servidor

**Comment by arthurbdiniz** [comment]
Vou aguardar o design ficar pronto...

**Comment by luizapeixe** [comment]
aí vão algumas sugestões de design para essas telas:

404 - https://invis.io/6RN45N9A87K#/310274892_404_-_Pa-gina_Na-o_Encontrada
403 - https://invis.io/6RN45N9A87K#/310274889_403_-_Permissao_Negada
400 - https://invis.io/6RN45N9A87K#/310274891_400_-_Requisicao_Invalida
500 - https://invis.io/6RN45N9A87K#/310274890_500_-_Erro_De_Servidor

**Comment by arthurbdiniz** [comment]
Obrigado @luizapeixe, vou comecar a fazer o style

**Comment by arthurbdiniz** [comment]
Segue como ficaram as novas paginas de erro @luizapeixe @ricardopoppi , posso fechar a issue?

* 400
![image](https://user-images.githubusercontent.com/18387694/43530085-174e61a4-9583-11e8-9f6f-88da884db47a.png)

* 403
![image](https://user-images.githubusercontent.com/18387694/43530006-ea714408-9582-11e8-8eab-19ef846dd517.png)

* 404
![image](https://user-images.githubusercontent.com/18387694/43530168-4c3f2786-9583-11e8-8500-968f7a7e96f8.png)

* 500
![image](https://user-images.githubusercontent.com/18387694/43530272-893a451c-9583-11e8-805c-59d4cefaf16e.png)
