### ISSUE TITLE
Revalidar a lógica de acesso para os dois diferentes perfis: usuário CPA e usuário comum

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#258]
A partir do recebimento dos conteúdos validados pela SNDCA (previstos para 01/agosto), vamos validar/ajustar a jornada dos dois tipos de usuários que temos na plataforma CPA. 

@parrahenri ajuda nessa.

A aplicação requer esses 3 tipos de usuários:

1) Usuário comum: não acessa painel, acessa conversas, não pode criar conversas

2) Usuário cpa: acessa painel, acessa conversas, é admin das conversas que criar

3) Usuário do grupo gestor: acessa painel, acessa conversas, pode promover conversas para a home do cpa

**Comment by parrahenri** [comment]
@ricardopoppi exatamente! São esses 3 perfis!

Vale reforçar: @Heloisecs o perfil mais importante agora é o 2 (usuário cpa) então prioriza pensando nele.

**Comment by ricardopoppi** [comment]
@parrahenri os conteúdos enviados pela SNDCA já permitem a gente definir a home do usuário comum e do usuário CPA? (cc @Heloisecs )

Obs: estou considerando que o usuário do grupo gestor terá a mesma home do CPA já que a diferença entre eles é apenas em um botão interno da criação de conversa, o "promote"

**Comment by ricardopoppi** [comment]
A home do CPA e do usuário comum serão idênticas, apenas diferenciando a existência (ou não) do botão PAINEL CPA. Para usuários CPA, aparece o botão, para todos os outros (não cpa) ele não aparece. Fechando essa issue pois issues específicas dos conteúdos do CPA estão sendo criadas
