### ISSUE TITLE
Verificação da implementação dos wireframes do CPA e EJ Generico (estilos, cores etc)

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#259]
Precisamos verificar, com olhar fino, se existem erros de implementação dos wireframes do CPA na plataforma de homologação. Eventuais bugs ou melhorias de UX também devem ser avalidadas.

Wireframes do CPA: https://projects.invisionapp.com/d/main#/projects/prototypes/14015249
Plataforma de homologação: https://cpa.dev.ejplatform.org/

Wireframes do EJ Genérico: https://projects.invisionapp.com/d/main#/projects/prototypes/13863876
EJ Genérico: https://dev.ejplatform.org/

@luizapeixe peço fazer esse diagnóstico num docs pois a partir da nossa discussão nele vamos gerar as issues posteriormente

**Comment by luizapeixe** [comment]
Foram criadas duas issues específicas para concentrar os relatos de erros de implementação encontrados:

• Para o EJ Genérico #281 

• Para o CPA #282 

obs.: Consigo entrar na plataforma de homologação do CPA tranquilo mas não estou conseguindo acessar o EJ Genérico pelo endereço https://dev.ejplatform.org/ . Dá erro 502, mesmo optando por "Ir para dev.ejplatform.org (não seguro)" . Só consigo acessar o site pelo https://ejplatform.org/conversations/

**Comment by ricardopoppi** [comment]
@luizapeixe para o genérico não vale a pena usar o ejplatform.org pois o código lá já está desatualizado, muitas coisas foram feitas. vale a pena esperar o dev.ejplatform.org voltar, deve acontecer nas próximas horas

**Comment by ricardopoppi** [comment]
Considerando que estamos trabalhando esses diagnosticos nas duas novas issues criadas, vou fechar essa
