### ISSUE TITLE
Criar app de Configurações e Redes sociais

### ISSUE THREAD

**Issue by pablodiegoss** [ejplatform/ej-server#26]
Criar um app django para fornecer informações sobre redes sociais, icones, links e prioridades (ordenação em menus). O app também pode fornecer acesso as cores da paleta da página.

**Comment by fabiommendes** [comment]
O app ej_configurations armazena links de redes sociais, configurações de cores e fragmentos de html que podem ser inseridos em trechos do site. Também coloquei todas urls que ficarão em /config/ dentro deste app.
