### ISSUE TITLE
Inserir botões com nomes dos grupos próximos à pontinha dos balões

### ISSUE THREAD

**Issue by arthurbdiniz** [ejplatform/ej-server#262]
![image](https://user-images.githubusercontent.com/18387694/43141212-bfa3b7d6-8f2b-11e8-94d7-39ba48406fdb.png)

**Comment by ricardopoppi** [comment]
@arthurbdiniz estamos retomando essa parte de dataviz do EJ, tem algo dessa issue que chegou a ser começado ou não tinha dado tempo ainda?
