### ISSUE TITLE
Propor telas de criação de conversa a partir das atuais telas de edição (para os dois temas)

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#267]
Hoje temos as telas de edição de conversa e moderação para os dois temas:

Genérico: https://projects.invisionapp.com/share/6RN45N9A87K
CPA: https://projects.invisionapp.com/share/F5MO3F2GCN8

Precisamos das telas para quando o usuário for criar uma conversa nova. É importante que elas sigam esse mesmo formato das telas de edição para unificar a experiencia. Diretrizes:

1) Elas indicarem para o usuário onde clicar para criar o conteúdo da "chamada/pergunta", tags
2) Incorporar o input de "titulo" (que é um texto curto usado para criar a url da conversa, ex: política de saúde, Brasil seguro, etc. Esse input só aparece no momento da criação.
3) Incorporar o input "timeline pública". Esse input só aparece no momento de criação da primeira conversa

**Comment by luizapeixe** [comment]
ok!

Seguem propostas atualizadas para os layouts do EJ Genérico (a gente aprovando os templates, replico as mesmas soluções para o layout do MDH)

-> tela de criação de conversa: https://invis.io/ZPN5XYV43DR
-> tela de edição de conversa: https://invis.io/7WN5YBZRNEX

1. a ideia é que o user entre na tela já com o campo de QUESTÃO ativado para a edição, isso se evidencia no box (background: rgba(255,255,255,0.50);border: 1px solid #A3D8DD;) que enquadra a área da questão. Quando o user clica fora do box, ou quando aperta a tecla "tab" pra trocar de campo, o box some deixando claro que o campo foi alterado com sucesso. Para habilitar a edição novamente basta o user clicar no link "EDITAR QUESTÃO" ou apenas clicar em cima do texto da questão. Aí então o box volta a aparecer

2. ele está apresentando ali em cima da questão. Minha sugestão é que seja um dropdown com opções já pré-estabelecidas, pensando em minimizar duplicatas, erros de ortografia e afins. _Pergunto: essa solução resolve ou seria melhor auto-complete ou campo em aberto? ou tudo isso junto?_

3. ok!

**Comment by ricardopoppi** [comment]
Massa! @luizapeixe comentei direto no invision, te marcando lá

sobre 1, achei ótimo
sobre 2, achei legal a posição mas o campo do título vai ter que ser aberto mesmo. expliquei lá no invision

**Comment by ricardopoppi** [comment]
@luizapeixe acho que vamos ter que fazer uma call sobre isso porque existe uma complexidade que eu acabei dando pouca bola, mas acho importante na concepção dessa ux. Essa complexidade é que os usuários vão criar conversas dentro do contexto de timelines e precisamos deixar isso claro pra eles. 
(i) Para usuários comuns, com 1 timeline disponível, essa timeline é criada no momento da primeira conversa. Após isso, todas as conversas subsequentes serão criadas na mesma timeline.
(ii) Para outros tipos de usuários, será permitida a criação de mais de uma timeline. Precisamos prever essa situação também, sempre simplificando ao máximo a UX.

Proponho uma call em algum horário nessa próxima segunda-feira, me indique se é viável pra ti.

**Comment by luizapeixe** [comment]
Tenho disponibilidade hoje sim, qualquer horário. Podemos já falar dessa questão e também da issue #162

**Comment by luizapeixe** [comment]
seguindo os direcionamentos da conversa com o @ricardopoppi , segue abaixo as telas adaptadas:

### 1. criação da conversa [(ver tela no invision)](https://invis.io/ZPN5XYV43DR)
adaptações:
+ adicionar campo pra definição do slug
+ adicionar campo pra atribuição de timeline da conversa
+ adicionar campo pra atribuição de que clusters a conversa comporta
+ dropdown com opções de _criar nova_ e _gerenciar*_:
![captura de tela 2018-08-01 as 23 15 23](https://user-images.githubusercontent.com/6249788/43558638-e1a2ec42-95e0-11e8-83d1-f1fd74e21c4c.png) 
*clicando em _gerenciar_: habilita um ícone na direita dos itens da lista dando opção de deletar

+ dropdown com opções de _criar novo_ e _gerenciar*_:
![captura de tela 2018-08-01 as 23 16 46](https://user-images.githubusercontent.com/6249788/43558670-0263e936-95e1-11e8-8ca6-20a23d168db2.png)
*ainda não cheguei numa solução que elimine totalmente a necessidade de uma página específica para a Gerenciar dos clusters. Receio que admnistrar os esteriótipos dos clusters dentro do dropdown pode gerar muita confusão e complexidade de implementação. Creio que uma página simples (lightbox, talvez?) pode ser a melhor solução para essa questão. Vou desenhar e publicar uma proposta na issue #162 

Uma sugestão de nomenclatura: acham que faz sentido se a gente chamar as TIMELINES DE CONVERSAS de LISTAS DE CONVERSAS?

### 2. edição da conversa [(ver tela no invision)](https://invis.io/7WN5YBZRNEX)
adaptações:
+ adicionar campos editáveis de Timeline e Clusters, porém opção de slug não poderá ser editada. Correto?
 
### 3. timeline pessoal[(ver tela no invision)](https://invis.io/ASNASPFWQKN) 
adaptações:
+ incluir opção de visualizar diferentes timelines
+ dropdown aberto:
![captura de tela 2018-08-01 as 23 18 30](https://user-images.githubusercontent.com/6249788/43559071-c98f1bc4-95e2-11e8-8b6e-ea835800c3f3.png)

### 4. timeline específica [(ver tela no invision)](https://invis.io/JTNB2BBXH2C)
adaptações:
+ tela que antes listava as conversas de um User, agora lista as conversas de uma timeline especifica, com url própria

### 5. menu hamburguer de admin [(ver tela no invision)](https://invis.io/MWNB2GGD3U9)
adaptações:
+ excluir _Solicitar relatórios_
+ incluir _Gerenciar timelines_ *
*penso em duas soluções pra essa página: 1. abre um dropdown, no menu mesmo, listando as timelines com um ícone de deletar do lado de cada item listado ou 2. user vai pra uma tela específica, parecida com que será criada para a gerencia dos clusters, e o user gerencia as timelines lá.

**Comment by ricardopoppi** [comment]
@luizapeixe mto legal, acho que reflete bem a nova arquitetura do EJ de timelines. Sobre sua pergunta: "adicionar campos editáveis de Timeline e Clusters, porém opção de slug não poderá ser editada. Correto?" - exato. umas vez criado o slug da conversa, ele não poderá mais ser editado. Acho que o mesmo acontece com a vinculação da conversa à uma timeline. @fabiommendes hj o backend permite mudar a conversa para outra timeline? Eu simplificaria esse ponto. Deixaria a escolha da timeline apenas na criação, mantendo fixo na edição.

@luizapeixe sobre a associação dos clusteres com os estereótipos, legal que vc vai pensar numa proposta para a #162, porque talvez uma boa opção seria concentrar essa configuração na própria tela de gerenciar estereótipos, em alguma solução que simplifique a associação dos clusteres (que são definidos por conversa) aos estereótipos (que são globais, por usuário).

@caiosba dá uma olhada nessas telas e tira as dúvidas que vc tiver?

**Comment by ricardopoppi** [comment]
@luizapeixe vamos encaminhar então:

1) nem slug nem timeline são campos editáveis na tela de edição. eles são definidos na criação.
2) podemos chamar as timelines de listas de conversas sim, achei uma boa solução
3) pode atualizar a tela de edição com esses ajustes do item (1) e gerar a nova versão pro genérico também? Qdo tiver os links publica aqui pra gente encaminhar pra implementação.

**Comment by luizapeixe** [comment]
Ok! Tela de edição editada com campo de _Lista de Conversa_ não-editável: https://invis.io/7WN5YBZRNEX

**Comment by luizapeixe** [comment]
Segue uma primeira proposta de adaptação das soluções adotadas para os layouts do CPA:

página Criar Conversa: https://invis.io/YRNFE75K8DV
página Editar Conversa: https://invis.io/RBNFE7992VE
página Lista de Conversas - minhas conversas: https://invis.io/47NFEEPXJ6A

Dúvida: devo criar também versões com IdV do CPA para os layouts em aprovação na issue #162 ?

**Comment by ricardopoppi** [comment]
@luizapeixe mto bom. Respondendo sua pergunta: sim é necessário criar as telas da #162 com a idv cpa (comentei lá tb). Como todas as telas dessa issue foram criadas já, estou fechando ela. Bom trabalho!
