### ISSUE TITLE
Layouts de edição/criação das Conversas

### ISSUE THREAD

**Issue by luizapeixe** [ejplatform/ej-server#268]
**Criar design de layouts para as telas de criação / edição das conversas que contemplem todos os conteúdos da conversa:**

+ título (slug, ex.: política de saúde, brasil seguro, ...) -> _sugiro trocar "título" por "categoria"_
+ questão 
+ marcadores -> _podemos chamar de TAGs?_

-> [tela de criação implementada](https://user-images.githubusercontent.com/6249788/43172625-86954d78-8f86-11e8-96d6-b673e5dbf4fd.jpg)

Uma diferença entre as páginas de CRIAR e a página de EDITAR é que na EDITAR temos ainda a moderação dos comentários/opiniões como conteúdo da página

Já temos no invision duas propostas de layout para a página de edição, [uma V1](https://projects.invisionapp.com/share/6RN45N9A87K#/screens/303751467) de aceitação/reprovação de comentário e [uma V2](https://projects.invisionapp.com/share/6RN45N9A87K#/screens/301693278) só deletando comentários

Nessas propostas de edição da conversa aproveitamos o máximo possível a estrutura da página da conversa, porém com estilo da lista de comentários tipo o [toggle de MEUS COMENTÁRIO na página de perfil](https://projects.invisionapp.com/share/6RN45N9A87K#/screens/300670645). Aí seguimos mesmo a ideia de "edit in place", que o campo de edição é o próprio nome do campo. -> _Pergunto: essa ideia é interessante também do ponto de vista da implementação?_

O que acham dessas propostas de página de edição? Acham que vale aproveitarmos a mesma estrutura para a página de criação de conversa, com "edit in place" e campos tipo 'digite sua questão aqui' ou algo assim? Ou seria o caso de nos aproximarmos de uma solução mais parecida com a página já implementada?

**Comment by ricardopoppi** [comment]
@luizapeixe peço considerar as indicações feitas na issue #267 

sobre a versão que vale é a de aceitação/reprovação mesmo

concordo com o edit in place, mesmo que gere algum complexidade de implementação, vale mto a pena em termos de experiencia. então vamos por ai.

sobre sua pergunta: "Acham que vale aproveitarmos a mesma estrutura para a página de criação de conversa, com "edit in place" e campos tipo 'digite sua questão aqui' ou algo assim?" a resposta é SIM. Melhor esse caminho do que se aproximar à pagina implementada, já que ela foi feita só pra ter algo enquanto não decidíamos o melhor caminho.
