### ISSUE TITLE
Customização de nomenclatura de grupos para canais no rocket

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#269]
Hoje a nomenclatura ficou confusa (aparecendo dois nomes juntos) e foi padronizada para canais em vez de grupos (ver img).

O correto é:

(i) Canais
(ii) Canais privados
(iii) Mensagens diretas (manter)

![captura de tela de 2018-07-24 21-28-08](https://user-images.githubusercontent.com/1162183/43173087-49373bbe-8f89-11e8-9eb9-7c68402741d5.png)

**Comment by ricardopoppi** [comment]
Para não termos que ficar administrando os js customizados do rocket, vamos voltar atrás. O padrão será canais. Já atualizei o corpo da issue @leandronunes

**Comment by leandronunes** [comment]
Feita e implantado no ambiente de homologação.

https://github.com/ejplatform/ej-server/blob/master/docker/rocketchat/rocket.js
