### ISSUE TITLE
Transformar o contador de comentários na conversa para a ordem crescente

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#270]
Atualmente o contador de conversas é decrescente. O correto é que seja crescente para que o usuário visualize o acumulo de comentários já votados. Veja na imagem o contador "5/10". Para simular: https://cpa.dev.ejplatform.org/conversations/empurandojuntes-publicidadeinfantil/

![captura de tela de 2018-07-24 22-26-32](https://user-images.githubusercontent.com/1162183/43174500-c12c374e-8f90-11e8-994c-1d79db5d9a89.png)

**Comment by lucashm** [comment]
https://github.com/ejplatform/ej-server/commit/187d9b7a515f5384e546626825b8ffbcb9f6a5e1
finalizada!
