### ISSUE TITLE
Ajustes no perfil do usuário para o tema CPA

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#271]
Ajustes no perfil de usuário que devem ter efeito apenas no tema CPA (cc @fabiommendes)

- [x] Incluir no cadastro CPA o campo "Etnia" formato aberto
- [ ] Retirar o campo "Atividade política"
- [x] Trocar "marron" por "pardo" em raça
- [x] Data de nascimento no lugar de idade
- [x] Incluir campo de "Escolaridade" formato aberto

**Comment by ricardopoppi** [comment]
@leandronunes propõe como fazer isso ser específico por tema, valida com a gente no grupo do front antes de implementar (cc @fabiommendes )

**Comment by fabiommendes** [comment]
Lembrando que no genérico apenas vamos trocar a data de nascimento por idade. Acho que devíamos colocar no Profile uma espécie de superset das informações úteis. Em cima disto, podemos ter uma configuração no Django que permita escolher quais campos serão realmente incluidos na página de perfil.

**Comment by ricardopoppi** [comment]
@gag2502 qdo puder atualiza o status dessa?

**Comment by gag2502** [comment]
Concluída

**Comment by gag2502** [comment]
Concluída
