### ISSUE TITLE
Trocar o ícone "comitê de participação de adolescentes":

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#273]
A SNDCA pediu que esse ícone não se parecesse com um "homenzinho" como é atualmente (ver img). Atualmente ele aparece em:

(i) na home
(ii) na navbar
(iii) na tela de perfil

@luizapeixe pode fazer umas duas propostas de substituição e carregar os assets?

![captura de tela de 2018-07-24 22-36-52](https://user-images.githubusercontent.com/1162183/43174747-235466f2-8f92-11e8-9132-979cf03fd05c.png)

**Comment by luizapeixe** [comment]
Fiquei na dúvida se o incomodo aí é relacionado ao gênero ou conceito do ícone, ou seja, se eles querem um ícone de pessoa mais genérico ou se não querem um ícone de pessoa at all. Entendendo que eles se referiam ao gênero no ícone, bolei as seguintes opções:
(caso eles queriam uma opção que não seja uma pessoinha, repenso outras soluções!)

aí vão algumas opções:

### opção 1:
i) 
![captura de tela 2018-07-30 as 13 14 51](https://user-images.githubusercontent.com/6249788/43409552-9b76299c-93fa-11e8-8129-a89f5ad80e36.png)

ii) 
![captura de tela 2018-07-30 as 13 11 59](https://user-images.githubusercontent.com/6249788/43409405-34371d40-93fa-11e8-8c43-87e9fb9d1e8d.png)

iii)
![captura de tela 2018-07-30 as 13 07 31](https://user-images.githubusercontent.com/6249788/43409205-a8246b82-93f9-11e8-99a8-243230170fa6.png)



opção 2:
i)
![captura de tela 2018-07-30 as 13 19 26](https://user-images.githubusercontent.com/6249788/43409771-37353c10-93fb-11e8-8fa5-413198def536.png)

ii)
![captura de tela 2018-07-30 as 13 17 44](https://user-images.githubusercontent.com/6249788/43409690-fcafe05e-93fa-11e8-9ffc-29397f124111.png)

iii)
![captura de tela 2018-07-30 as 13 07 49](https://user-images.githubusercontent.com/6249788/43409211-adf47b6a-93f9-11e8-9aaf-10bbd8afb66a.png)

**Comment by ricardopoppi** [comment]
@luizapeixe legal termos essas. Mas a rejeição acabou sendo pelo estilo "pessoinha" mesmo. pode experimentar num outro estilo?

**Comment by luizapeixe** [comment]
Entendi!

Que tal essa ideia então, reforçando a identidade do CPA?

i) 
![captura de tela 2018-08-02 as 12 00 13](https://user-images.githubusercontent.com/6249788/43592378-cd74daf8-964b-11e8-9525-7879d592540c.png)


ii)
![captura de tela 2018-08-02 as 12 00 50](https://user-images.githubusercontent.com/6249788/43592387-d1a53fb4-964b-11e8-9f93-dbf95ade2881.png)


iii)
![captura de tela 2018-08-02 as 12 00 28](https://user-images.githubusercontent.com/6249788/43592392-d62b48b2-964b-11e8-9f8c-668f8f046eb0.png)

**Comment by parrahenri** [comment]
fazendo! notificação dos favoritos não tá prevista na tela das notificações ainda @luizapeixe? acho que deixamos passar e lá só tem o "aprovados" e "reprovados", que na vdd são o SELECIONADOS e o PRESSIONADOS (nova nomenclatura que validamos)

**Comment by parrahenri** [comment]
@ricardopoppi feito:

1. selecionar
splash
CANDIDATA SELECIONADA COM SUCESSO 
Agradecemos sua participação! Continue selecionando candidatos que te interessem e não deixe de conferir sua caixa de notificações para acompanhar novidades sobre suas seleções

notificação
FULANA DE TAL: Obrigado por me selecionar aqui no app! Para conhecer mais sobre minhas propostas e história, acesse meu site: http://www.sitedacandidata.com.br

email (vai para a candidata)

Boas notícias! Você acaba de ser selecionada por um usuário no aplicativo da campanha Unidos Contra a Corrupção, o que significa que essa pessoa se interessou pelo seu perfil e pelos seus compromissos e agora vai poder ver mais detalhes e informações sobre você.

Atenciosamente.
Unidos Contra a Corrupção



2. pressionar
splash
CANDIDATA PRESSIONADA COM SUCESSO 
Agradecemos sua participação! Continue pressionando candidatos que não se comprometeram ainda e não deixe de conferir sua caixa de notificações para acompanhar novidades sobre essa pressão

notificação
Você pressionou FULANO DE TAL porque ele ainda não se comprometeu com os compromissos da Unidos Contra a Corrupção. 

*CASO HAJA MUDANÇA DE POSIÇÃO 
notificação 2
FULANO DE TAL: Acabei de me comprometer com o NOME DO ITEM. Gostaria de me reavaliar como candidato?

email (vai para a candidata)
Um usuário acaba de solicitar que você se comprometa com os compromissos da campanha Unidos Contra a Corrupção. Essa pessoa conheceu seu perfil e gostaria de pedir que registre seu compromisso.

Quando registrar o compromisso, todos os usuários que tiveram solicitado que você o fizessem receberão avisos diretamente, podendo avaliar positivamente seu perfil! Não perca tempo e registre seu compromisso agora mesmo:

[ link para site da campanha onde candidatos podem se cadastrar ]


3. favoritar
splash
CANDIDATA FAVORITADA COM SUCESSO 
Agradecemos sua participação! Continue selecionando candidatos que te interessem e não deixe de conferir sua caixa de notificações para acompanhar novidades sobre suas seleções

notificação
FULANA DE TAL: Obrigado por me favoritar aqui no app! Minhas redes sociais estão no app para acompanhar meu dia a dia e ficarmos em contato! 

email (vai para a candidata)

Excelente notícia! Depois de te selecionar e conhecer mais sobre seu perfil no aplicativo da campanha Unidos Contra a Corrupção, um usuário acaba de favoritar você. Significa que ela gostou muito de seu perfil e pensa em votar em você no dia da eleição.

Agora, seu perfil será mais fácil de ser visto por essa pessoa, que poderá usar o app no dia das eleições, como um santinho.

Atenciosamente.
Unidos Contra a Corrupção

**Comment by ricardopoppi** [comment]
@luizapeixe assim que puder, atualiza o invision do cpa com essas telas pra gente poder criar a issue de substituição no código?

**Comment by luizapeixe** [comment]
ok!

home: https://invis.io/WKNEGAAABQ7
perfil do user + navbar: https://invis.io/QBNEGBW8SA2

os novos elementos podem ser extraídos pela aba Inspect Mode no próprio invision

**Comment by ricardopoppi** [comment]
issue #293 aberta pra implementação, fechando essa
