### ISSUE TITLE
Entrega MDH

### ISSUE THREAD

**Issue by fabiommendes** [ejplatform/ej-server#28]
Plano de ação para entrega de um MVP do dia 30/04

## Linha básica de ação

Temos apenas uma semana de gás, então temos que desenvolver várias funcionalidades o mais rápido possível.
Para cumprir o deadline, vamos mudar temporariamente de estratégia. As páginas serão servidas pelo backend no modo "clássico". Toda integração e desenvolvimento do frontend Angular ficará para depois, já que o desenvolvimento no Angular é mais lento e consegue mobilizar apenas uma parte da equipe. Também adiaremos o trabalho com a API para depois da entrega já que não entrega valor p/ o cliente. A galera do back vai ter que concentrar em fazer views e (pelo menos um esboço de) templates. Já para o front, é preciso ajustar os templates e fazer CSS.

## Arquitetura

* Todos templates estão armazenados em /ej/templates/jinja2/ e são feitos em Jinja
* Eles seguem uma lógica de "components" utilizando os macros Jinja.
* CSS é baseado na arquitetura ITCSS e está salvo em /lib/scss/. Boa parte do trabalho será feita na pasta components em /lib/scss/6_components/. O tema pode ser modificado alterando o valor das variáveis em /lib/scss/1_settings
* Vamos tentar aderir o tema à nossa IDV genérica
* CSS utiliza a convenção SuitCSS para nomear as classes. Não precisa teorizar muito, basta seguir o padrão dos outros componentes...
* CSS é "mobile first".  Temos que entregar apenas a estilização para mobile. A do desktop é um bônus e em princípio fica para depois desta entrega. Ele vai ficar "responsivo" quando suportar desktop.
* Como lib de frontend usamos jQuery e unpoly e é possível puxar componentes da jQuery UI s/ temas. Por enquanto os assets JS são servidos de CDNs. Vamos configurar o webpack depois. Temos que nos preocupar em utilizar libs que se preocupam com o "progressive enhacement"

## User stories para o MVP

* [x] Cadastro com e-mail (OAuth não é necessário, confirmação de e-mail também não)
* [x] Login
* [ ] Login integrado com o rocket
* [x] Página de perfil s/ gamificação
* [x] Edição de perfil
* [x]  Ver lista conversas
* [x] Ver categorias
* [x] Ver uma conversa específica
* [x] Votar em um comentário
* [x] Fazer novos comentários
* [ ] Rastrear comentários não aprovados
* [x]  Acessar o rocket em um iframe

## Admins
* [x] Admin para gerenciar a plataforma
* [ ] Permissões específicas de edição de conversa e inserção de conteúdo

## Outros
* [x] Gerar banco de dados de exemplo
* [x] Consertar header
* [x] Aplicar um mínimo de estilização para que o site se aproxime dos wireframes criados
* [ ] A prioridade é "mobile first", mas é bom entregar pelo menos o header responsivo para desktop.

**Comment by leandronunes** [comment]
Considerando as user stories pontuadas no MVP acredito que o caminho mais rápido para ser feito seria utilizando a interface angular. No meu ponto de vista acredito estar tudo pronto já lá interface atual necessitando somente de algumas adaptações.
Entretanto se o caminho definido pelo grupo for outro estamos juntos misturados. ;)

**Comment by BrunaNayara** [comment]
@luizapeixe Aqui tem uma lista de coisas que precisamos para o MVP do dia 30. Pode dar uma olhada pq isso pode te orientar na ordem de criação das telas.  Todas marcadas com o checkzinho já estão disponíveis no [EJ Platform Dev](dev.ejplatform.org), mas precisam ser revisadas, provavelmente.

**Comment by BrunaNayara** [comment]
@luizapeixe eu coloquei o link errado. Vou enviar o link certo .  [EJ Platform](https://dev.ejplatform.org/)
