### ISSUE TITLE
Aplicar estilos no django admin do EJ Genérico

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#280]
Conforme wireframe: https://projects.invisionapp.com/share/V9GNMI1BG2F#/304630145_admin_Django

**Comment by lucashm** [comment]
página inicial do django admin finalizada!
![image](https://user-images.githubusercontent.com/16053704/43731808-166c3fca-9986-11e8-87dc-85e9625cc6fc.png)
Restam os templates das páginas de adicionar/modificar

**Comment by lucashm** [comment]
Finalizada para mobile!
