### ISSUE TITLE
Consertar defeitos de aplicação do tema genérico

### ISSUE THREAD

**Issue by fabiommendes** [ejplatform/ej-server#281]
Existem várias pequenas divergências da nossa aplicação do tema com relação às telas do Invision. Criei essa issue para a gente manter o tracking das correções e discutir entre devs e designers o que precisa ser ajustado.

**Comment by fabiommendes** [comment]
Erros que identifiquei (validar com a @luizapeixe  ou @Heloisecs)

Tela de detail da conversa:
* [ ] Espaçamento entre o balão e o header deveria ser nulo
* [ ] Várias ações (ex. editar conversa) mostram botões ao invés do estilo da idv
* [ ] Comentário com espaçamento excessivo
* [ ] Número não deveria aparecer acima do nome do autor
* [ ] Tela de postar comentário deveria ficar junta com o card do comentário

**Comment by lucashm** [comment]
https://github.com/ejplatform/ej-server/commit/169ba3b2e6d4a0f1d5115a59525291dfb8eb5ab8
Algumas correções, favor validar!
- Comentário com espaçamento corrigido
- Número do comentário agora está centralizado (?) (Não achei nada sobre no invision)
- Botão oval consertado

**Comment by ricardopoppi** [comment]
@luizapeixe importante validar isso em dev.ejplatform.org - está fora do ar mas deve estar de volta nas próximas horas

**Comment by gag2502** [comment]
Mais uma correção feita 
- Espaçamento entre o balão e o header deveria ser nulo

**Comment by leandronunes** [comment]
outros erros #295 #296

**Comment by ricardopoppi** [comment]
Fechando essa pq muita coisa já foi mudada, teremos que realizar um novo diagnóstico. Essa issue poderá ser sempre referenciada
