### ISSUE TITLE
Consertar defeitos de aplicação do tema CPA

### ISSUE THREAD

**Issue by fabiommendes** [ejplatform/ej-server#282]

**Comment by luizapeixe** [comment]
Listo abaixo alguns erros de implementação no CPA na situação de **user deslogado**

telas aprovadas no invision -> https://invis.io/CYHFR09R9M6
telas analisada dia 30/07 -> https://cpa.dev.ejplatform.org/
Obs.: naveguei usando o Google Chrome versão 67

### HOME
1. Incluir a faixa com a frase "UM LUGAR PRA CRIANÇAS E ADOLESCENTES (...)" abaixo do header
2. Incluir a faixa do "COMO FUNCIONA" e a explicação das 3 fases relacionadas no estilo toggle
-> vide [tela](https://projects.invisionapp.com/d/main#/console/14015249/302157283/preview) no invision

### CONVERSA
1. Tem um espaço desnecessário em volta do box da conversa (Me parece que é o padding da classe ReactComponent, que está como 28px e devia ser 0px)
2. Incluir recursos de FAVORITAR e COMPARTILHAR abaixo do box da conversa.
3. Tipografia todas erradas:
3a. **Tags**: segundo o invision, deveria ser font-family: SourceSansPro-Bold; font-size: 12px; color: #30C0D3;
3b. **Questão**: segundo o invision, deveria ser font-family: Raleway-Regular; font-size: 23px; color: #3F1B53;
3c. **Comentários e Votos**: deve ser font-family: Raleway (sendo Regular pra nomenclatura e Bold pro número); font-size: 12px; color: #30BEC0;
4. Restante de conteúdos de **_Opiniões da Comunidade_** e **_Deixe sua opinião_** estão ocultos pro user deslogado enquanto na tela aprovada o user pode visualizar esses conteúdos porém não pode interagir com eles. Caso o user deslogado clique para interagir num conteúdo, abre um splash [vide tela](https://projects.invisionapp.com/d/main#/console/14015249/302157270/preview).
5. No footer, excluir o texto "Empurrando Juntos é uma plataforma (...)"

### estáticas: PERGUNTAS FREQUENTES / TERMOS DE USO
1. O Container de conteúdo precisa de uma margem de no mínimo 10px nas laterais para não precarizar a leitura dos conteúdos. O ideal é estar alinhado à esquerda com o título da página.

### LOGIN
1. Tipografia errada no texto "Contribua para discussões (...)". Deveria ser font-family: Raleway-Regular; font-size: 20px; color: #C6027B;
2. Imagem do gatinho pertence ao EJ, no CPA a imagem default de user é outra. (ainda em definição vide issue #273  
3. Excluir o ponto azul e ícone do facebook entre a imagem do user e campo de email
Botão ENTRAR deve ter texto em branco #ffffff
4. O rodapé desta tela é diferente, terminar com uma imagem em retícula (aquelas bolinhas - [vide invision](https://projects.invisionapp.com/d/main#/console/14015249/302157265/preview))
5. Esta tela não apresenta a Navbar. Acaba no footer.

**Comment by ricardopoppi** [comment]
@luizapeixe estou fechando essa, mas ela pode ser referenciada para a avaliação que será feita em dev
