### ISSUE TITLE
Ativação do alto contraste no EJ Generico afetando a leitura dos controles

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#286]
Ao aplicar o alto contraste, os controles ficam da mesma cor do menu:

Antes:

![captura de tela de 2018-08-03 21-02-17](https://user-images.githubusercontent.com/1162183/43670322-d2a1f1a8-9760-11e8-9fbb-ce1a3fc9425c.png)

Depois: 

![captura de tela de 2018-08-03 21-02-05](https://user-images.githubusercontent.com/1162183/43670323-d2df8cd4-9760-11e8-876f-82e435c4daeb.png)

**Comment by lucashm** [comment]
Não creio que o alto contraste seja o problema aqui... me parece algum css quebrado! De todo modo, a development quebrou de novo, e localmente esse bug não ocorre... Fico no aguardo da develop voltar pra poder verificar melhor esse problema!

**Comment by lucashm** [comment]
Como imaginei, era problema na compilação do sass! Tudo certo na dev!

**Comment by ricardopoppi** [comment]
Coisa linda @lucashm !
