### ISSUE TITLE
Substituir o ícone do CPA na home, perfil e navbar (tema CPA)

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#293]
No tema cpa (cpa.dev.ejplatform.org) o ícone que representa o cpa e o perfil dos usuários foram reformulados e devem ser trocados na implementação:

home: https://invis.io/WKNEGAAABQ7
perfil do user + navbar: https://invis.io/QBNEGBW8SA2

os novos elementos podem ser extraídos pela aba Inspect Mode no próprio invision. Se precisar de algum asset, chamar a @luizapeixe diretamente

**Comment by Heloisecs** [comment]
Pessoal da secretaria pediu em reunião que trocasse o ícone de perfil por qualquer coisa (bichinho, robozinho) que não indicasse gênero. Nas palavras delas "tudo menos o bonequinho de banheiro" como o prazo está corrido, vamos trocar o ícone pelo do gatinho do ej mesmo.

**Comment by ricardopoppi** [comment]
maravilha, pensa um ejcat estilizado CPA
