### ISSUE TITLE
Implementar as telas de criação de conversas para os dois temas (BIG ISSUE)

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#298]
Com a troca do username do cadastro pela funcionalidade de timelines as telas de criação de conversa precisaram refletir essa novidade. Além disso, formulamos a interface e criação de estereótipos de clusteres que estava faltando.

Durante a implementação dessa issue, dúvidas de usabilidade e ux podem ser tiradas marcando a @luizapeixe. No comentário dessa issue https://github.com/ejplatform/ej-server/issues/267#issuecomment-409789264 há um panorama sobre o que foi ajustado em relação à versão anterior. Duvidas sobre o funcionamento das timelines, clusteres e estereótipos, podem ser tiradas comigo (@ricardopoppi).

Às telas:

#### 1. Tela de criação de conversa: [WIREFRAME]
- [x] Responsável: Caio
(https://projects.invisionapp.com/share/ZPN5XYV43DR#/screens)
Observação sobre essa tela: As timelines são criadas apenas no momento de criação das conversas. Para fins de simplificaçaõ não há outra tela pra isso. Quando o usuário cria uma conversa, ele também escolhe qual a timeline que a conversa fará parte. Isso pode ser feito escolhendo uma timeline criada anteriormente por ele, ou digitando um novo slug. Os nomes das timelines serão transformados em slug pelo backend. Já o link permanente, é o slug da conversa. A url da conversa compoe o dominio+slug-da-timeline/slug da conversa. Exemplo: ejplatform.org/governodebrasilia/saude-publica

#### 2. Tela de edição de conversa: [WIREFRAME]
- [x] Responsável: Caio
(https://projects.invisionapp.com/share/7WN5YBZRNEX#/screens)
Observações sobre essa tela: No momento da edição, nem o slug da conversa, nem a timeline que ela faz parte são editáveis mais.

#### 3. Tela de exibição de conversas, quando o usuário acessa sua própria timeline: [WIREFRAME]
- [x] Responsável: Leandro
(https://projects.invisionapp.com/share/ASNASPFWQKN#/screens)
Observações sobre essa tela: Para usuários que possuem mais de uma timeline criadas, é exibido o drop-down no topo da tela, logo abaixo do header. Se o usuário só tem uma timeline criada, esse drop-down pode ser ocultado. O botão "moderar conversa" leva para a tela de Edição da conversa, que foi unificada com a da moderação.

#### 4. Tela de exibição de conversars, quando o usuário acessa qualquer timeline (que não seja sua): 
- [x] Responsável: Leandro
[WIREFRAME](https://projects.invisionapp.com/share/JTNB2BBXH2C#/screens)
Observações sobre essa tela: O campo \<timeline_name\> deveria exibir o nome da timeline, gravado no momento da criação dela junto com a conversa. Espera-se que o backend tenha as duas informações (nome e slug). Se não tiver, podemos exibir o slug nesse campo, pelo menos nesse momento.

#### 5. Tela de gerencia de clusters: [WIREFRAME](https://invis.io/SVNCFZN462T)
- [x] Responsável: Gabriela
(https://projects.invisionapp.com/share/SVNCFZN462T#/screens)
Observações sobre essa tela: Aqui listamos todos os clusters com opção de "exibir mais" (tipo toggle) e "deletar". quando o user clica na seta para exibir mais, parece a conversa (não editável) do cluster e a lista de estereótipos relacionados (seguindo a referencia/inspiração da plataforma do [SOMUC](https://staging.somuc.org.br/plataforma/)). Todas as edições possíveis dos clusters são feitas nessa página mesmo. 

#### 6. Tela de gerencia de estereótipos: [WIREFRAME](https://invis.io/BQNCFZY726E)
- [x] Responsável: Lucas/Diniz
Observações sobre essa tela: Aqui listamos todos os estereótipos permitindo as interações de "editar" e "deletar". Clicando em EDITAR o user é levado pro lightbox de _edição do estereótipo_, que tem a mesma estrutura do lightbox de _criação de estereótipo_. Clicando em deletar o user recebe um lightbox dizendo algo tipo "tem certeza que quer deletar esse estereótipo?" com um "sim" e "não"

#### 7. Tela de criação de novo cluster: [WIREFRAME](https://invis.io/ZBNCFWMFJQT)
- [x] Responsável: Gabriela
(https://projects.invisionapp.com/share/ZBNCFWMFJQT#/screens)
Observações sobre essa tela: Lightbox com campos de 1. nome; 2. conversa e 3. lista de estereótipos. Essa tela serve apenas para CRIAÇÃO de clusters, uma vez que as edições podem ser todas feitas na tela anterior, de gerência dos Clusters

#### 8. Tela de criação / edição de estereótipos: [WIREFRAME](https://invis.io/2PNDAYDZ74A)
- [x] Responsável: Lucas/Diniz
Observações sobre a tela: Essa tela contempla as necessidades tanto de criação quanto de edição dos estereótipos. Exibe campos de Nome do estereótipo e Conversas relacionadas + Concordância. As diferenças entre os lightboxes de Criação e Edição seriam basicamente 2:
1. título da tela "Novo estereótipo" seria "Editar estereótipo"
2. botão ao final no lightbox "CRIAR" seria "SALVAR"

#### 9. Menu hamburger ajustado: [WIREFRAME]
- [x] Responsável: Leandro
(https://projects.invisionapp.com/share/MWNB2GGD3U9#/screens)
Observações sobre essa tela: O grupo "conversas" no menu lateral, passa a exibir os seguintes itens: 
  (i) Conversas públicas: Link para o /conversations da plataforma, que exibe a lista de conversas que foram promovidas pelo admin
  (ii) Suas conversas: Exibe a timeline do usuário. Quando ele possui mais de uma, deve levar sempre para a mais antiga
  (iii) Adicionar conversas: Vai para  a tela de criação de conversas (uma nova conversa)
  (iv) Conversas favoritas: Leva para essa área no perfil do usuário
  (v) Gerenciar timelines: Essa tela não existe (@luizapeixe pode ajustar removendo ela do wireframe?)
  (vi) Gerenciar estereótipos: Leva para a tela de criação/edição de clusters e estereótipos

#### 10. Tela de criação de conversa: [WIREFRAME]
- [x] Responsável: Caio
(https://projects.invisionapp.com/share/YRNFE75K8DV#/screens)

#### 11. Tela de edição de conversa: [WIREFRAME]
- [x] Responsável: Caio
(https://projects.invisionapp.com/share/RBNFE7992VE#/screens)

#### 12. Tela de exibição da própria timeline: [WIREFRAME]
- [x] Responsável: Leandro
(https://projects.invisionapp.com/share/47NFEEPXJ6A#/screens)

#### 13. Tela de exibição de conversars, quando o usuário acessa qualquer timeline (que não seja sua): WIREFRAME em fase de aplicação da idv #162
- [x] Responsável: Leandro

#### 14. Tela de gerencia de clusters: WIREFRAME em fase de aplicação da idv #162 
- [x] Responsável: Gabriela

#### 15. Tela de gerencia de estereótipos: WIREFRAME em fase de aplicação da idv #162
- [x] Responsável:  Diniz/Lucas

#### 16. Tela de criação de novo cluster: WIREFRAME em fase de aplicação da idv #162
- [x] Responsável: Gabriela

#### 17. Tela de criação / edição de estereótipos: WIREFRAME em fase de aplicação da idv #162 
- [x] Responsável:  Diniz/Lucas

**Comment by lucashm** [comment]
![image](https://user-images.githubusercontent.com/16053704/43995276-5a2ed87c-9d81-11e8-8c00-2f0de4231e93.png)
(6) parcialmente finalizada, resta fazer os botões de deletar e pesquisar funcionarem.

**Comment by caiosba** [comment]
Implementei as telas/funcionalidades de criar conversa e editar conversa, para os temas EJ e CPA, conforme imagens abaixo:

![298-create-cpa](https://user-images.githubusercontent.com/117518/44073630-34063f6e-9f6b-11e8-8353-f1c2e3971db9.png)

![298-create-ej](https://user-images.githubusercontent.com/117518/44073631-3429c2f4-9f6b-11e8-8b80-63021b8d9e53.png)

![298-edit-cpa](https://user-images.githubusercontent.com/117518/44073632-34585880-9f6b-11e8-9dd6-750043e6d987.png)

![298-edit-ej](https://user-images.githubusercontent.com/117518/44073634-34782d90-9f6b-11e8-84ce-d4ccfbd184bc.png)

**Comment by caiosba** [comment]
Lista de últimos ajustes necessários para a tela de criação e edição de conversas:

- [ ] Permitir adicionar mais um campo de comentário na tela de criação da conversa
- [ ] Adicionar botão de "Gerenciar Estereótipos" na tela de edição de conversa (https://projects.invisionapp.com/share/7WN5YBZRNEX#/screens) que leva para `/conversations/slug-da-conversa/stereotypes/`
- [ ] Tirar os ícones de edição à direitos dos campos no formulário de criação/edição de conversas
- [ ] O ícone de edição de conversa à direita do campo de selecionar board deve permitir criar um novo board

**Comment by caiosba** [comment]
Fiz tudo listado no comentário anterior. Como todas as imagens abaixo mostram, os ícones de edição foram retirados da direita dos campos.

Adicionar mais campos de comentário:
![298-1-more-comments](https://user-images.githubusercontent.com/117518/44173161-7eb33a80-a0b5-11e8-9517-cca0a82ad738.gif)

Criar novo board a partir do dropdown:
![298-4-new-board](https://user-images.githubusercontent.com/117518/44173163-7eb33a80-a0b5-11e8-820f-a72b90b17cc1.gif)

Botão de gerenciar estereótipos:
![298-2-manage-stereotypes-button](https://user-images.githubusercontent.com/117518/44173165-7eb33a80-a0b5-11e8-9db3-f9b59346f525.png)

**Comment by ricardopoppi** [comment]
Vou fechar essa issue aqui pois o mutirão já foi feito. A partir de agora abro issues específicas de ajustes a partir da homologação
