### ISSUE TITLE
Implementar login por google

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#299]
Implementar login pro google no generico e cpa

**Comment by rodrigocam** [comment]
Implementamos o login por google adicionando um aplicativo social no django admin e criando um app na área de desenvolvedor google, porém ele não funciona sempre, as vezes não consegue autenticar, estamos verificando o que pode ser o problema!

**Comment by ricardopoppi** [comment]
qdo as confs estiverem ativas novamente me pinguem que eu consigo testar com mais gente e descobrir se tem alguma regra pra quando não funciona
