### ISSUE TITLE
Conversas ativas na Home

### ISSUE THREAD

**Issue by BrunaNayara** [ejplatform/ej-server#30]
Implementar os cards de conversas ativas na Homepage

**Comment by caiosba** [comment]
Tô trabalhando nessa (também estou sem permissão para atribuir).

**Comment by caiosba** [comment]
PR: https://github.com/ejplatform/ej-server/pull/45

**Comment by caiosba** [comment]
Para fins de comparação...

Design:

![30-design](https://user-images.githubusercontent.com/117518/39318203-e3ed418e-4953-11e8-9d16-6d476c1a78ef.png)

Implementação:

![30-impl](https://user-images.githubusercontent.com/117518/39318211-e852cd5c-4953-11e8-91b0-c3ebfa08c5e8.png)

**Comment by caiosba** [comment]
Feito e disponível em `develop`.
