### ISSUE TITLE
Atualizar os wireframes da home CPA conforme ajustes solicitados pela SNDCA

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#302]
Conforme imagem disponibilizada. Importante que os conteúdos da home "Como funciona": "Painel CPA" e "Conversas públicas" seja acompanhado de ícones.

Importante também que os membros do CPA possam ter acesso à opção de baixar a cartilha de uso mais completa. Talvez isso pode estar localizado na home do rocket (issue #304)

Também será necessário retirar o link do twitter do cabeçalho pois o CPA, CONANDA ou SNDCA não tem twitter. Além disso, encontrar um espaço para inserir a referências dos canais de denúncia: Disque 100 e #HumanizaRedes nessa página inicial

![cpa - 1](https://user-images.githubusercontent.com/1162183/43924515-3ead499e-9bfb-11e8-8430-0512566e2316.png)

**Comment by Heloisecs** [comment]
https://invis.io/2KNHRQQRF5X
https://invis.io/P4NHRRDKDRB

**Comment by ricardopoppi** [comment]
Gostei! Fiz um comentário no invision pra derivar uma versão logado-cpa com o botão "painel cpa". @parrahenri dá o ok tb?

**Comment by parrahenri** [comment]
OK! Reforço coment do poppi

**Comment by ricardopoppi** [comment]
Maravilha. Já criei a issue #318 para implementação, fechando essa aqui então
