### ISSUE TITLE
Atualizar os wireframes da tela inicial do rocket conforme ajustes solicitados

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#304]
Conforme imagem. Lembrar que eles querem bastante efusivamente a logo do CPA nessa tela.

![cpa - 3](https://user-images.githubusercontent.com/1162183/43924838-ff07c318-9bfb-11e8-9f2d-7009456a6ab7.png)

**Comment by Heloisecs** [comment]
https://invis.io/7PNHRIX5SBY
https://invis.io/CYHFR09R9M6#/302157257_Criar_novo

**Comment by parrahenri** [comment]
eu curti! elas haviam pedido "cascata de cpa", mas podemos argumentar que repetir logo já deu destaque suficiente sem deixar pesado. é isso?

**Comment by ricardopoppi** [comment]
passando pra implementação, fechando essa
