### ISSUE TITLE
Atualizar o conteúdo do "sobre nós"

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#305]
Retirar o sobre nós do texto para ficar só o do header

![cpa- sobre n s](https://user-images.githubusercontent.com/1162183/43924949-4a790d34-9bfc-11e8-8189-bd32d6c40170.png)

**Comment by parrahenri** [comment]
Lembrando que o texto dessa seção está em: https://github.com/ejplatform/ej-server/issues/307

**Comment by ricardopoppi** [comment]
feito. sobre nós está sem título agora. commit ad294e2b3b01609c262ab5d0e40e77e1585ad8b5
