### ISSUE TITLE
Conteúdos estáticos

### ISSUE THREAD

**Issue by parrahenri** [ejplatform/ej-server#307]

**Comment by parrahenri** [comment]
[Perguntas frequentes_v2.docx](https://github.com/ejplatform/ej-server/files/2276233/Perguntas.frequentes_v2.docx)
[Sobre nós_v2.docx](https://github.com/ejplatform/ej-server/files/2276234/Sobre.nos_v2.docx)
[TERMOS DE USO_v2.docx](https://github.com/ejplatform/ej-server/files/2276235/TERMOS.DE.USO_v2.docx)

**Comment by ricardopoppi** [comment]
conteúdos atualizados na plataforma pelo commit ad294e2b3b01609c262ab5d0e40e77e1585ad8b5
