### ISSUE TITLE
Propor versão desktop do site comercial do EJ

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#308]
Atualmente o site é mobile-only. Precisamos de uma versão desktop que aproveite a largura da tela e todo o conteúdo

Atualmente:

![screencapture-dev-ejplatform-org-home-2018-08-10-17_36_52](https://user-images.githubusercontent.com/1162183/43980329-29ac7866-9cc4-11e8-831e-e8e2d0e682a7.png)

**Comment by luizapeixe** [comment]
Bolei uma primeira proposta aqui. Vou exibir aqui porque o invision está setado para exibir apenas mobile

![desktop_home comercial](https://user-images.githubusercontent.com/6249788/44036907-548e0b86-9ee9-11e8-91f3-36cf1b816e1e.png)


o que acham?

**Comment by ricardopoppi** [comment]
Tá bem massa, arrazou. Vou deixar ela ainda aberta, pois depois de vc propor a seção "quem somos" pra mobile (issue #311), vai ter que atualizar essa aqui também @luizapeixe

**Comment by luizapeixe** [comment]
Considerando a faixa Comunidade EJ:

![desktop_home comercial](https://user-images.githubusercontent.com/6249788/44061024-19c43f0e-9f2d-11e8-95db-4929a358adc7.png)

**Comment by ricardopoppi** [comment]
@luizapeixe ultimos dois pitacos

1) Será que a comunidade não vem antes de "quem adotou"? Eu mudaria a ordem
2) Nessa rolagem de logos, precisamos incluir a logo da (i) fundação perseu abramo, (ii) transparência internacional e (iii) lappis
3) No rodapé, vai esse conteúdo: Empurrando Juntos é uma plataforma desenvolvida e elaborada pelo Instituto Cidade Democrática, LAPPIS-UnB e hacklab/.
4) Passar pro invision pra facilitar implementação. Como nossos prototipos são mobile, pode gravar essa tela nesse protótipo aqui: https://projects.invisionapp.com/d/main#/projects/prototypes/12899955

O que acha @parrahenri ?

**Comment by parrahenri** [comment]
de acordo com todos os itens!

Sugiro essa ordem:

Cidade
Lappis
Hacklab
Pencil
TI
FPA
PCdoB

**Comment by ricardopoppi** [comment]
passei para implementação na #315 - fechando essa então

**Comment by parrahenri** [comment]
@ricardopoppi e @luizapeixe temos uma seção de Planos e Preços pra subir. Reabrimos a issue ou criamos uma outra pra ela?

**Comment by ricardopoppi** [comment]
@parrahenri melhor uma outra falando exclusivamente da inclusão dessa seção
