### ISSUE TITLE
Navbar não deve aparecer para usuários não logados

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#309]
Atualmente a navbar está aparecendo até para usuários deslogados. Conforme wireframe, quando o usúário estiver deslogado, deve aparecer uma barra de "entrar": https://projects.invisionapp.com/d/main#/console/13863876/299689436/preview

Importante verificar isso para os dois temas, o dev.ejplatform.org e o cpa.dev.ejplatform.org

**Comment by lucashm** [comment]
Feito!
![image](https://user-images.githubusercontent.com/16053704/43994479-df9de772-9d73-11e8-8c98-9b0258000dec.png)
