### ISSUE TITLE
Conceber na tela comercial do EJ uma seção (página interna?) quem somos

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#311]
Um seção "quem somos" onde colocaremos as fotos e legenda de todo mundo da comunidade

**Comment by ricardopoppi** [comment]
@luizapeixe acho que pode ser uma faixa tipo preview que leva pra uma interna via opção "ver todos/ver mais" etc. Não tem texto, é apenas uma galera de fotos com legenda onde colocaremos as nossas carinhas e dos parceiros da comunidade

**Comment by luizapeixe** [comment]
algo tipo assim: https://invis.io/CMNBJVZKWNF ?

na página interna, que infos vamos informar? nome e ocupação no projeto?

**Comment by ricardopoppi** [comment]
@luizapeixe comments:

1) Talvez outra coisa em vez de time. Talvez comunidade mesmo (cc @parrahenri)
2) Sendo pequeno assim cada foto (gostei!) talvez valha a pena estar todo mundo na home mesmo, sem interna, sem ver todes

**Comment by luizapeixe** [comment]
1. ok!
2. pode ser! Já sabemos quantos pessoas serão?

**Comment by parrahenri** [comment]
SIm, são as pessoas que estão na comunidade, sem dúvidas.

"Comunidade EJ"

**Comment by parrahenri** [comment]
Vamo abrir uma planilha e a galera preenche e manda foto pra um único email?

**Comment by ricardopoppi** [comment]
Lancei a coleta de fotos no grupo, fechando essa aqui
