### ISSUE TITLE
Ajustar a tela de login para o novo wireframe

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#312]
Conforme wireframes: 

- [x] Generico: https://projects.invisionapp.com/d/#/console/13863876/293544071/preview
- [x] CPA: https://projects.invisionapp.com/share/PENHROSTYJQ#/screens

**Comment by arthurbdiniz** [comment]
Tela de login no tema CPA praticamente finalizada!


![image](https://user-images.githubusercontent.com/18387694/44159746-c2467e00-a08e-11e8-81ce-aad556608d70.png)


![image](https://user-images.githubusercontent.com/18387694/44159756-cbcfe600-a08e-11e8-8b54-483a7567bb1c.png)

**Comment by arthurbdiniz** [comment]
@luizapeixe no final da tela existe uma reticula, não consegui achar o asset, teria como verificar isso posteriormente?

**Comment by luizapeixe** [comment]
claro. aqui está, @arthurbdiniz 

![cpa_reticula](https://user-images.githubusercontent.com/6249788/44160107-c030ef00-a08f-11e8-9ae6-21c83bc74932.png)

**Comment by arthurbdiniz** [comment]
Obrigado @luizapeixe!

**Comment by arthurbdiniz** [comment]
@ricardopoppi, estamos enfrentando uma série de contratempos em relação ao tema do CPA que antes estava como está nas comentários anteriores e agora esta da seguinte forma:

![image](https://user-images.githubusercontent.com/18387694/44291702-8fe77d00-a256-11e8-9811-d2fa0ef70505.png)

Algum bug ocorreu em relação as imagens do tema e colorização de botões

**Comment by arthurbdiniz** [comment]
Amanha vou entender e corrigir esses problemas

**Comment by ricardopoppi** [comment]
humm parece que misturou com o tema genérico, a logo pelo menos. @fabiommendes sabe dizer se é algum bug na configuração do tema ou nas variáveis de build?

**Comment by ricardopoppi** [comment]
O @fabiommendes descobriu um bug na task que está gerando essa mistura. Pinga a gente aqui @fabiommendes qdo tiver conseguido subir o fix?

**Comment by ricardopoppi** [comment]
@arthurbdiniz o @fabiommendes já está subindo o fix pro master, dá pull aí que já vai estar ok isso. Se vc atualizar o novo código não precisa, mas enquanto isso um workaround é usar o comando "inv sass -t cpa run -t cpa"

**Comment by arthurbdiniz** [comment]
blz @ricardopoppil, obrigado!

**Comment by arthurbdiniz** [comment]
@gag2502, bem vinda. Se quiser fazer a parte do login genérico ainda não fiz:
https://projects.invisionapp.com/d/#/console/13863876/293544071/preview

**Comment by arthurbdiniz** [comment]
Estou finalizando o tema CPA

**Comment by arthurbdiniz** [comment]
O @lucashm finalizou o footer no tela CPA e a @gag2502 estava para finalizar o tema generico
