### ISSUE TITLE
Atualizar a home do rocket e a tela de criação de canais

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#313]
Conforme wireframes:

- [x] Home do rocket: https://projects.invisionapp.com/share/7PNHRIX5SBY#/screens

- [x] Tela de criação de canais: https://projects.invisionapp.com/share/CYHFR09R9M6#/screens/302157257_Criar_novo

**Comment by leandronunes** [comment]
Está pendente a imagem que ficará no topo da home

**Comment by ricardopoppi** [comment]
@Heloisecs pode fornecer essa asset pro @leandronunes?
