### ISSUE TITLE
Ajustar a home institucional do EJ com novos conteúdos e logos de parceiros e versão desktop

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#315]
mobile (avatares 50px) - https://invis.io/CMNBJVZKWNF
desktop (avatares 60px) - https://invis.io/JCNILM3PQXD

Assets gerais: https://github.com/ejplatform/ej-server/files/2288013/assets_EJhomeComercial.zip
Assets fotos avatares: https://drive.google.com/drive/u/0/folders/1iePkcxLEZXqsMpcYyiMFlQkaT9EMDriO

Assets que não estiverem disponíveis no invision, pedir diretamente à @luizapeixe

**Comment by luizapeixe** [comment]
Zipei os assets aqui, galera. Se sentirem falta de algum, me avisem q eu mando

[assets_EJhomeComercial.zip](https://github.com/ejplatform/ej-server/files/2288013/assets_EJhomeComercial.zip)

**Comment by caiosba** [comment]
Implementei a seção para a comunidade EJ. Para a versão desktop, ficou faltando a imagem do cabeçalho, @luizapeixe :)

**Comment by luizapeixe** [comment]
opa! tá na mão :)
![ej_destaque](https://user-images.githubusercontent.com/6249788/44229087-5e46b700-a16d-11e8-819e-7c29e7775815.png)

**Comment by ricardopoppi** [comment]
Duas fotos atualizadas @caiosba peço considerar nessa versão final: Tallys Martins e da Vanessa Tonini

Estão na pasta de assets do drive

**Comment by caiosba** [comment]
Feito!
