### ISSUE TITLE
Exercitar a home institucional do EJ com o avatar um pouco maior na seção comunidade

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#316]
Nessas aqui:

Desktop -> https://invis.io/JCNILM3PQXD
Mobile -> https://invis.io/CMNBJVZKWNF

**Comment by luizapeixe** [comment]
Seria interessante a gente saber a quantidade exata de pessoas e nomes que vamos colocar ali, pra gente ter uma noção da diagramação dos elementos e extensão dessa faixa. A situação mobile é mais crítica pra diagramação dos avatares, então vou mostrar abaixo 3 testes com tamanhos diferentes pra gente analisar as possibilidades:

## • 40 px
no grid, cabem 6 fotos por linha // no nome, cabem 9 caracteres por linha

![captura de tela 2018-08-15 as 11 37 50](https://user-images.githubusercontent.com/6249788/44155256-34741cd2-a083-11e8-8ae3-71ccfca1d3b0.png)

## • 50 px
No grid, cabem 5 fotos por linha // no nome, cabem 11 caracteres por linha

![captura de tela 2018-08-15 as 11 46 59](https://user-images.githubusercontent.com/6249788/44155308-5262cb12-a083-11e8-8791-16c1f3ffc0b1.png)

## • 60 px
No grid, cabem 4 fotos por linha // no nome, cabem 13 caracteres por linha

![captura de tela 2018-08-15 as 11 58 54](https://user-images.githubusercontent.com/6249788/44155368-720f215e-a083-11e8-9e8b-9c344eff1117.png)


Olhando assim, sem saber a quantidade exata de pessoas, tendo a preferir a opção 50px, porém se tivermos uma lista muito extensa, talvez 40px seja a melhor opção mesmo. O que você acha?

**Comment by ricardopoppi** [comment]
@luizapeixe devem ser umas 20-25 pessoas. Eu iria de 50px. Por mim pode atualizar os dois wires com isso. O que acha @parrahenri?

**Comment by parrahenri** [comment]
50px, manda ver!

**Comment by luizapeixe** [comment]
Dúvida: do ponto de vista técnico, é muito ruim a gente deixar 50px no mobile e 60px no desktop?

Telas atualizadas com 24 pessoas no total!

mobile (50px) - https://invis.io/CMNBJVZKWNF
desktop (60px) - https://invis.io/JCNILM3PQXD

**Comment by ricardopoppi** [comment]
ah, boa ideia, vou colocar assim pra implementação, os compas dão conta sim rsrs
