### ISSUE TITLE
Ajustar a home do cpa conforme wireframes ajustados

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#318]
- [x] Para DESLOGADOS: https://projects.invisionapp.com/share/2KNHRQQRF5X#/screens
- [x] User comum logado: https://projects.invisionapp.com/share/P4NHRRDKDRB#/screens
- [x] User grupo CPA logado: https://projects.invisionapp.com/share/ZTNJDBZEQCA#/screens

**Comment by MatheusRich** [comment]
Estou fazendo a tela de usuários deslogados!

**Comment by arthurbdiniz** [comment]
@luizapeixe, teria como me mandar os seguintes icones?

![image](https://user-images.githubusercontent.com/18387694/44216465-5ece5600-a14b-11e8-84ed-ac11eb8e1c6e.png)

**Comment by luizapeixe** [comment]
@arthurbdiniz o ícone de alerta eu tenho aqui (alias, é fontawesome, mas te mando por aqui em .svg zipado, pra facilitar) já o ícone do gatinho foi adicionado à navbar numa última versão desenhada pela @Heloisecs então ela quem deve conseguir te passar certinho

[CPA_navbar-alertas.svg.zip](https://github.com/ejplatform/ej-server/files/2294372/CPA_navbar-alertas.svg.zip)

**Comment by arthurbdiniz** [comment]
@Heloisecs , aguardo o asset do little cat...

**Comment by arthurbdiniz** [comment]
@MatheusRich como está o andamento da tela do usuário DESLOGADO?

**Comment by arthurbdiniz** [comment]
@ricardopoppi assim que pegar o ultimo asset com a @Heloisecs, o User comum logado é fechado, acredito que no dia de amanha teremos mais notícias.

**Comment by ricardopoppi** [comment]
@MatheusRich @arthurbdiniz @lucashm atentem para o fato de que essa home deve ser configurada para a instancia/build https://cpa.dev.ejplatform.org/home/ - isso provavelmente é feito via settings mas se não tiverem totalmente familiarizados nisso peçam orientação para o time de pipeline: @fabiommendes @pablodiegoss

**Comment by lucashm** [comment]
@ricardopoppi Então, nós iniciamos essa tela pensando que era a /conversations... que era configurada como a antiga "main" do cpa... No caso, devemos voltar a tela /conversations para como ela era antigamente, pra daí configurar a home de acordo com as telas dessa issue?

**Comment by ricardopoppi** [comment]
@lucashm acho que dá pra usar a /conversations como home dessa instância. A diferença é que aparecem esses conteúdos estáticos nela, que na /conversations do dev.ejplatform por exemplo não aparecem. Veja print do invision:

![captura de tela de 2018-08-17 21-09-51](https://user-images.githubusercontent.com/1162183/44293503-0342bc00-a262-11e8-82c3-c97045b4ad05.png)


Com base nisso é possível padronizar que o deslogado acessa aquela tela mais rica de estáticos ([wireframe invision](https://projects.invisionapp.com/share/2KNHRQQRF5X#/screens)) e o logado tanto cpa quanto comum vão acessar a conversations com esses textos propostos no wireframe dos logados ([wireframe invision](https://projects.invisionapp.com/share/P4NHRRDKDRB#/screens/313661723)).

**Comment by fabiommendes** [comment]
Separamos provisoriamente as urls assim:
- Usuários logados vão sempre ser redirecionados para EJ_USER_HOME_PATH (/conversations/)
- Usuários não logados vão ser redirecionados para EJ_ANONYMOUS_HOME_PATH
  - Instância do CPA tem EJ_ANONYMOUS_HOME_PATH='/start/'
  - Instância genérica tem EJ_ANONYMOUS_HOME_PATH='/home/'

No futuro vamos matar a URL /start/ e propor uma solução mais elegante (via override de template, ou algo assim), mas por enquanto é o lugar para implementar este wireframe do CPA.

**Comment by ricardopoppi** [comment]
@lucashm então com essa orientação do Fábio, vc deve então implementar a home do deslogado do cpa ([wireframe](https://projects.invisionapp.com/share/2KNHRQQRF5X#/screens)) no '/start'. Da mesma, a home do logado (instancia cpa) no '/conversations' ([wireframe](https://projects.invisionapp.com/share/P4NHRRDKDRB#/screens))

**Comment by Heloisecs** [comment]
[cats.zip](https://github.com/ejplatform/ej-server/files/2307221/cats.zip)

**Comment by ricardopoppi** [comment]
@arthurbdiniz @lucashm os itens fixos no final da pagina /start do cpa devem ter esses conteúdos:

![43924515-3ead499e-9bfb-11e8-8430-0512566e2316](https://user-images.githubusercontent.com/1162183/44419510-c7557280-a551-11e8-8798-6fe72df2ad33.png)

**Comment by lucashm** [comment]
![image](https://user-images.githubusercontent.com/16053704/44420419-3e8c0600-a554-11e8-8456-a1b3de95dada.png)
tô precisando desses 2 assets @Heloisecs

**Comment by Heloisecs** [comment]
[COMOFUNCIONA.zip](https://github.com/ejplatform/ej-server/files/2307672/COMOFUNCIONA.zip)
