### ISSUE TITLE
Adicionar ícones

### ISSUE THREAD

**Issue by BrunaNayara** [ejplatform/ej-server#32]
Ícones a serem colocados:
- [x] Favicon
- [x] Ícones do EJ pro PWA

Os ícones devem ser png, nas resoluções (48x48, 96x96, 192x192, 512x512)

**Comment by fabiommendes** [comment]
@Heloisecs  e @luizapeixe , confiram se o favicon vai ser esse mesmo. Em baixa resolução ele perde muita qualidade e seria interessante ter uma versão pixel-perfect para 16x16px e 32x32px

**Comment by lucasssm** [comment]
![image](https://user-images.githubusercontent.com/16053704/39398215-30db2a86-4ae1-11e8-8302-70bba9b7a0f4.png)
eu coloquei esse aqui dos assets...
Se não me engano só tinham 3 lá, um com EJ escrito ao lado, esse, e outro com a tag de rocket...
Optei por esse porque o que tinha EJ escrito ficou bem pequenininho, não sei se será o correto mesmo :P validem aí por favor!
