### ISSUE TITLE
Complementar as logos de organizações que adotaram o EJ na pag institucional

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#326]
Atualmente a página implementada só exibe 4 logos. Peço a @luizapeixe passar ao @caiosba as logos faltante e as orientações sobre o carrossel

**Comment by luizapeixe** [comment]
Segue zip contendo os 7 logos. A ordem de importância de aparição no carrossel deve ser:

1. Cidade democrática
2. Lappis
3. Hacklab
4. Pencil
5. Transparência Internacional
6. FPA
7. PCdoB

[EJ_logos.zip](https://github.com/ejplatform/ej-server/files/2299496/EJ_logos.zip)

**Comment by caiosba** [comment]
Feito! Adicionei os logos faltantes, corrigi a ordenação conforme orientação de Luiza e implementei o carrossel para o responsivo.
