### ISSUE TITLE
Texto do botão criar conversa quebrando no topo da tela de criação

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#328]
Sugestão: manter o texto em "CREATE" que vira "CRIAR" na tradução. Assim fica mais curto e não quebra.

![captura de tela de 2018-08-17 20-14-28](https://user-images.githubusercontent.com/1162183/44292371-7b0ce880-a25a-11e8-8c9d-fabdae3ce786.png)

**Comment by caiosba** [comment]
Substituição feita conforme sugestão!
