### ISSUE TITLE
Opção "create new board" na tela de criação de conversas não permite escrever nome do board

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#329]
Quando a opção "Create new board" é escolhida deveria habilitar um campo para escrever o nome do board no próprio campo. Esse campo não está sendo habilitado:

![captura de tela de 2018-08-17 20-21-13](https://user-images.githubusercontent.com/1162183/44292511-6aa93d80-a25b-11e8-865a-a3773c0d02cc.png)

**Comment by caiosba** [comment]
Poppi, que navegador você usou? Pra mim tá funcionando...veja o vídeo: https://www.youtube.com/watch?v=cAXsBlW4DKo

**Comment by ricardopoppi** [comment]
Debugando mais, isso acontece algumas vezes na primeira carga da página. Erro do inspector: Uncaught ReferenceError: createNewBoard is not defined at HTMLSelectElement.onchange (<anonymous>:2:1)

**Comment by caiosba** [comment]
Corrigido!
