### ISSUE TITLE
Dono da conversa não visualiza o botão de edição/gerenciar conversa

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#332]
![captura de tela de 2018-08-17 21-29-09](https://user-images.githubusercontent.com/1162183/44293764-c0361800-a264-11e8-9ffb-0b41d58f1a6d.png)

**Comment by fabiolamfleury** [comment]
Corrigido!

**Comment by ricardopoppi** [comment]
fechando essa issue pra homologar em dev
