### ISSUE TITLE
Site institucional do EJ não ocupa largura completa da tela na versão desktop

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#335]
Conforme print:

![captura de tela de 2018-08-17 21-21-51](https://user-images.githubusercontent.com/1162183/44302757-eb247880-a305-11e8-9513-fcdeffdc3e83.png)

**Comment by caiosba** [comment]
Ahh tá... eu coloquei a largura que estava no wireframe desktop... vou colocar pra tomar a largura toda.

**Comment by caiosba** [comment]
Feito!
