### ISSUE TITLE
Proteger master do GitHub com integração de testes com Travis CI

### ISSUE THREAD

**Issue by Dayof** [ejplatform/ej-server#336]
- Proteger branch master no GitHub e permitir commits somente com build e todos os testes executarem com sucesso no pipeline do Travis CI
- Commits na master somente com PRs

**Comment by ricardopoppi** [comment]
fechando pois essa issue está deprecated de acordo com a nova politica que está sendo implementada: https://github.com/ejplatform/ej-server/wiki/Pol%C3%ADticas-de-Reposit%C3%B3rio
