### ISSUE TITLE
Página de perfil

### ISSUE THREAD

**Issue by BrunaNayara** [ejplatform/ej-server#34]
De acordo com: https://projects.invisionapp.com/d/main#/console/13863876/293506911/inspect

**Comment by caiosba** [comment]
Concluído e disponível em `develop`. Screenshot em anexo.
![screencapture-localhost-8000-profile-2018-04-28-00_36_17](https://user-images.githubusercontent.com/117518/39391588-5f99791e-4a7c-11e8-80f7-d3fdf0f2994c.png)
