### ISSUE TITLE
Bolar uma imagem bundle com a logo do EJ junto com a logo da Rocketchat

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#340]
No catálogo dos softwares EJ queremos indicar com uma imagem a versão com rocket. @Heloisecs pode conceber essa imagem em svg?

**Comment by Heloisecs** [comment]
![artboard 23 copyempurrandorocket](https://user-images.githubusercontent.com/9471715/44425080-4605dc00-a561-11e8-9aff-ab624d7e4433.png)
[Artboard 23empurrandorocket.svg.zip](https://github.com/ejplatform/ej-server/files/2307790/Artboard.23empurrandorocket.svg.zip)

**Comment by Heloisecs** [comment]
[SVG.zip](https://github.com/ejplatform/ej-server/files/2307927/SVG.zip)

<img width="694" alt="artboard 1 copy 9 2x" src="https://user-images.githubusercontent.com/9471715/44427498-1f976f00-a568-11e8-9dfc-c0ca87520f47.png">

**Comment by ricardopoppi** [comment]
@fabiochips @pablodiegoss @rodrigoredcode vejam imagem pra usar no Docker hub da versão ej+rocket

**Comment by ricardopoppi** [comment]
ficou sensacional @Heloisecs!
