### ISSUE TITLE
Retirar item "criar quadro" do menu hamburguer

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#342]
Esse ítem não existirá na plataforma. A criação dos quadros é feita no momento de criação da conversa. Não teremos uma tela de gestão de quadros.

![captura de tela de 2018-08-20 12-10-25](https://user-images.githubusercontent.com/1162183/44349031-7589eb00-a472-11e8-910c-bf9a9fd84ee2.png)

**Comment by MatheusRich** [comment]
[Done!](be49bfd02144a966d91259237d8a3f1558557eca)
