### ISSUE TITLE
Tela de edição/moderação de conversa não exibe os botões superiores nem os comentários

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#348]
ROTA: https://dev.ejplatform.org/conversations/\<nome-da-conversa\>/moderate/
O wireframe de como devia ser: https://projects.invisionapp.com/d/main#/console/13863876/303751467/preview

Print de como está:

![captura de tela de 2018-08-20 16-51-57](https://user-images.githubusercontent.com/1162183/44363079-6c604480-a499-11e8-8440-5e1ec741a7f3.png)

**Comment by caiosba** [comment]
Poppi, acho que no caso da moderação aqueles botões não fazem sentido pois não tem nada para ser salvo... e nos comentários já tem os botões para aceitar ou rejeitar. Aqueles botões superiores aparecem na tela de edição de conversa (basta trocar `moderate` por `edit` na URL ou clicar em "Editar conversa" na tela de moderação), pois lá faz sentido. Por outro, é possível também moderar comentários a partir da tela de edição de conversa. Então talvez a tela de moderação seja redundante e possamos redirecionar sempre para a tela de edição. Por favor avalie.

Com relação aos comentários, aparecem os comentários pendentes para moderação. Eu testei aqui e funcionou normal. Certifique-se por favor de testar com uma conversa que certamente tenha comentários pendentes.

**Comment by ricardopoppi** [comment]
blz @caiosba obrigado! vou testar por aqui e realmente os botões superiores não fazem sentido na tela de moderação. concordo contigo que no próximo release temos que pensarm em unificação dessas telas pra melhorar a ux geral
