### ISSUE TITLE
Item colapsável (toggle) de conversas favoritas e comentarios não funciona no perfil do usuário

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#349]
Faça alguns comentários, vá até o perfil do usuário e tente visualizá-los. Vale o mesmo para conversas favoritas. O número aparece mas o toggle não exibe os elementos. Ver print:

![captura de tela de 2018-08-20 23-43-16](https://user-images.githubusercontent.com/1162183/44377424-114b4380-a4d3-11e8-8a55-61662a1b7b5c.png)

**Comment by lucashm** [comment]
![image](https://user-images.githubusercontent.com/16053704/44422553-d809e680-a559-11e8-8669-ad5f8b8e19cf.png)
Feito!
