### ISSUE TITLE
Aplicar a nova logo no header do dev.cpa e no favicon usar a logo antiga

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#352]
Conforme imagem: https://github.com/ejplatform/ej-server/issues/301#issuecomment-414746957

No header a logo nova. No favicon, a logo antiga.

Algum asset adicional, pedir direto pra @Heloisecs

**Comment by MatheusRich** [comment]
@ricardopoppi A mudança deverá ser somente no header ou em qualquer outro lugar que fosse utilizada anteriormente?

Por enquanto mudei apenas no header.
![image](https://user-images.githubusercontent.com/20938712/44613029-61344e00-a7e4-11e8-8218-894de09c353a.png)

@Heloisecs pode me passar o favicon?

**Comment by ricardopoppi** [comment]
Opa @MatheusRich só no header mesmo. Mas observe que o header passa a ter fundo branco com a aplicação dela.

Sobre o favicon, pode gerar ele com a logo antiga, que é mais "quadrada"

**Comment by MatheusRich** [comment]
@ricardopoppi Acredito que está done já.

![image](https://user-images.githubusercontent.com/20938712/44729963-4567cb00-aab6-11e8-877e-11494d1fb489.png)
