### ISSUE TITLE
Página fale conosco está com alguns estilos diferentes do wireframe

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#355]
Wireframe dessa página: https://projects.invisionapp.com/d/main#/console/14015249/314110132/preview

Print da tela implementada:
![captura de tela de 2018-08-22 13-08-53](https://user-images.githubusercontent.com/1162183/44475922-ba498980-a60c-11e8-9bf2-b49781286c09.png)

**Comment by lucashm** [comment]
done!
