### ISSUE TITLE
Interna de conversa do cpa não está pegando corretamente as strings traduzidas

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#357]
Observe logo abaixo da questão (no print): 0s comments / 0s votes / 0s favorites

Print:
![captura de tela de 2018-08-22 13-50-06](https://user-images.githubusercontent.com/1162183/44477935-81acae80-a612-11e8-930f-d84489d7aa65.png)

**Comment by caiosba** [comment]
Corrigido localmente... não consegui testar em Dev porque CPA está fora do ar.
