### ISSUE TITLE
Os ítens de "gênero" e "raça" não estão pegando tradução

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#360]
Os ítens de perfil "gênero" e "raça" não estão sendo traduzidos na interface, mesmo existindo a tradução no arquivo PO

![captura de tela de 2018-08-22 17-40-13](https://user-images.githubusercontent.com/1162183/44489682-81bca680-a632-11e8-8bd9-1bfc2849879f.png)

**Comment by ricardopoppi** [comment]
boa @fabiolamfleury abri a #378 sobre isso

**Comment by fabiolamfleury** [comment]
Corrigido pelo Professor Fábio! O problema era no django boogie em relação à objetos da class IntEnum(esses campos de escolha) no que diz respeito a pegar os campos traduzidos

**Comment by ricardopoppi** [comment]
blz! e o boogie vai ficando cada vez melhor! (cc @fabiolamfleury @fabiommendes)
