### ISSUE TITLE
Algumas páginas estão com o conteúdo muito próximo do final, conflitando com navbar

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#363]
Ex: Conteúdos estáticos e edição de perfil. Como estão muito próximos conflitam com a navbar. Ver print abaixo.

Possível solução é deixar um respiro de altura maior que a navbar para que ela nunca sobreponha conteúdos.

Rota: https://cpa.dev.ejplatform.org/about-us/
Prints:

![photo_2018-08-22_17-51-06](https://user-images.githubusercontent.com/1162183/44490195-0bb93f00-a634-11e8-851d-fe42a1276ece.jpg)
![photo_2018-08-22_17-51-03](https://user-images.githubusercontent.com/1162183/44490197-0c51d580-a634-11e8-96ac-11ed5f7e6776.jpg)

**Comment by arthurbdiniz** [comment]
@ricardopoppi acredito que essa issue já tenha sido corrigida, porem no ambiente de dev está diferente. Fiz testes em várias paginas e todas estão funcionando corretamente. Além disso no ambiente de dev a pagina https://cpa.dev.ejplatform.org/about-us/ está quebrada...

**Comment by arthurbdiniz** [comment]
Rota: https://cpa.dev.ejplatform.org/about-us/ 
![image](https://user-images.githubusercontent.com/18387694/44694544-76a7b300-aa44-11e8-9e64-477ca18a03b0.png)

**Comment by ricardopoppi** [comment]
maravilha, já foi corrigida então, fechando essa
