### ISSUE TITLE
Na interna da conversa o texto "Comentários da comunidade" vira "Comentários"

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#367]
Na interna da conversa. Ex de rota: https://cpa.dev.ejplatform.org/conversations/direitos-escola/

**Comment by fabiolamfleury** [comment]
Acabei corrigindo esse nome enquanto arrumava outras traduções :)

**Comment by ricardopoppi** [comment]
mto bom @fabiolamfleury!
