### ISSUE TITLE
Conceber uma ux para o caso de implementarmos a volta dos comentários pulados

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#368]
Se implementarmos que os comentários pulados continuam no deck para votação, qual seria uma boa UX pra isso?

Lembrando que precisamos informar o usúario que isso está acontecendo e isso não deve afetar a barra de progresso da futura gamificação

**Comment by Heloisecs** [comment]
Não entendi, se eles voltarem não vão aparecer no final da fila dos comentários? Porque o usuário precisa ser avisado disso?

**Comment by ricardopoppi** [comment]
Pode ser. Acha que é suficiente?

**Comment by ricardopoppi** [comment]
@Heloisecs to lembrando aquele mini teste que fizemos, algumas pessoas acharam ruim eles sumirem, outras ficaram incomodadas com o fato deles voltarem. Como não há consenso, talvez pudessemos pensar num lembrete que aparece apenas na primeira vez que qq usuário pula um comentário
