### ISSUE TITLE
Esconder Funções/Links no Rocket

### ISSUE THREAD

**Issue by arkye** [ejplatform/ej-server#37]
Toda a NavBar da SideBar, menos "User" e "Pesquisar"

![screenshot from 2018-04-25 15-49-32](https://user-images.githubusercontent.com/4184861/39266409-53c53dcc-48a0-11e8-8d1f-49edee2d02ab.png)

**Comment by ricardopoppi** [comment]
Issue aparentemente resolvida, fechando
