### ISSUE TITLE
Melhorar a usabilidade quando o usuário tenta comentar além do limite

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#370]
Para testar:

1) Entre numa conversa. Ex: https://cpa.dev.ejplatform.org/conversations/direitos-escola/
2) Faça um comentário
3) Faça outro comentário
4) Faça um terceiro comentário e observe que o aviso quase não aparece e o usuário fica com a impressão que o comentário foi aceito pelo app

@luizapeixe pode detalhar uma interação melhor para esses casos?

**Comment by luizapeixe** [comment]
Acho que poderia subir um toast avisando que o user já atingiu no limite de comentários daquela conversa. Tipo assim:

![captura de tela 2018-08-22 as 18 51 35](https://user-images.githubusercontent.com/6249788/44492892-740c1e80-a63c-11e8-8004-9c6530ba9beb.png)

O que acha?

**Comment by ricardopoppi** [comment]
achei ótimo. te peço @luizapeixe: derivar a versão genérica, atualizar os dois no invision e postar os links aqui pra eu usar na issue da implementação. vlw!

**Comment by luizapeixe** [comment]
ok!

EJ: https://invis.io/KTNPFXDM436
MDH: https://invis.io/U4NPFY4ZKYW

**Comment by ricardopoppi** [comment]
Ótimo! Abri a #386 pra implementação, fechando essa
