### ISSUE TITLE
Ajustes na concepção do alto contraste

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#371]
- [x] Interna da conversa. Ex: https://cpa.dev.ejplatform.org/conversations/direitos-escola/ - a fonte da pergunta não é alterada. Esse comportamento está correto @luizapeixe?
- [x] Login fica com o texto explicativo muito apagado (ver print abaixo)
- [x] Título dos conteúdos estáticos também fica com a cor da fonte muito próxima do fundo (ver segundo print abaixo)

Prints:
![photo_2018-08-22_18-08-03](https://user-images.githubusercontent.com/1162183/44491190-d3ffc680-a636-11e8-874b-f224b9022c7b.jpg)
![photo_2018-08-22_18-08-04](https://user-images.githubusercontent.com/1162183/44491189-d3ffc680-a636-11e8-9931-4013cb3ed012.jpg)

**Comment by luizapeixe** [comment]
Sobre a 1ª questão: Está correto! Com o Alto Contraste ativado o background se mantem #D4F7F5 e o texto fica #072A49. A relação de contrate entre essas cores é de 12.82, ou seja, ótima!

Sobre a 2ª questão: podemos aumentar o font-weight dessas fontes para melhorar a legibilidade delas

Sobre a 3ª questão: A relação entre background #30c0d3 e texto #072A49 é de 6.68 o que é considerando bom, já que é acima de 4.5

**Comment by ricardopoppi** [comment]
Obrigado pelas respostas @luizapeixe! Pode incluir no invision uma solução pra 2a. questão? Obrigado!

**Comment by luizapeixe** [comment]
ok! aqui está: https://invis.io/7KNQEMIBJW3

**Comment by ricardopoppi** [comment]
maravilha! pontos resolvidos, para o 2 criei issue específica #412 para esse wireframe. fechando essa.
