### ISSUE TITLE
Django cospe erro quando usuário tenta criar um quadro com slug já existente

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#375]
Para simular

1) crie uma convesa num quadro
2) logue com outro usuário
3) tente criar uma conversa num quadro com o mesmo nome usado no item (1)

Erro que aparece:

Request Method: | POST
-- | --
http://dev.ejplatform.org/conversations/add/
2.0.8
IntegrityError
duplicate key value violates unique constraint "ej_boards_board_slug_key" DETAIL:  Key (slug)=(quadroteste) already exists.
/pypackages/lib/python3.6/site-packages/django/db/backends/utils.py in _execute, line 85
/usr/bin/python3
3.6.6
['/app',  '/usr/local/bin',  '/app/src',  '/app',  '/pypackages/lib/python3.6/site-packages',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages',  'src',  '/app']
Qua, 22 Ago 2018 19:46:10 -0300

**Comment by rodrigocam** [comment]
@ricardopoppi não consegui reproduzir o erro como você descreveu. No caso seria criar uma conversa com o mesmo nome de uma conversa em outro quadro certo? Testei aqui e ele consegue criar um slug unico mesmo com o nome sendo igual. Em quadros, se tentar criar com um slug já existente ele retorna um erro no próprio formulário dizendo que o slug já existe. Será que não faltou algum passo?

**Comment by ricardopoppi** [comment]
@rodrigocam valeu pelo empenho nessa aqui. Quando a gente repete o slug no mesmo usuário, tanto de conversa quanto de quadro, vai bem. Ele resolve. Mas quando vc loga com outro usuário (experimenta criando um outro registro qq) e tenta usar o mesmo slug de quadro de um outro usuário, dá esse erro.

Tenta criar um quadro chamado "quadroteste2" em qq usuário seu. Deve dar esse erro ai e vc vai poder trackear.

**Comment by fabiolamfleury** [comment]
Conseguimos reproduzir o erro aqui! Vou acrescentar uma validação no formulário, avisando para o usuário caso já exista um board com aquele slug, para que ele possa entrar com outro nome

**Comment by ricardopoppi** [comment]
perfeito!

**Comment by fabiolamfleury** [comment]
Corrigido pelo rodrigo [nesse commit](https://github.com/ejplatform/ej-server/commit/2e681854ed2fefc38105df16a714bac43655f384)

**Comment by ricardopoppi** [comment]
maravilha!
