### ISSUE TITLE
Rota profile/conversations não está exibindo o botão "Criar conversa"

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#376]
Teste feito na rota do generico: https://dev.ejplatform.org/profile/conversations/

Usuário logado, deveria exibir o botão criar conversa no topo da página, nessa rota

**Comment by MatheusRich** [comment]
@ricardopoppi Essa rota ainda existe? Para mim retorna `TemplateDoesNotExist at /profile/conversations/`.

**Comment by ricardopoppi** [comment]
Essa rota parece que foi removida. A @fabiolamfleury está trabalhando nisso, por enquanto estou fechando essa issue pois ela deve ser resolvida junto com a resolução da rota de boards e criação de conversas
