### ISSUE TITLE
Tratar no front o erro quando o comentário de uma mesma conversa tem o mesmo conteúdo

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#377]
Devemos tratar esse erro no front em dois momentos:
(i) tela de criação de conversa
(ii) interna da conversa no campo de comentários. 

Wireframes com o toast:

EJ Genérico: https://projects.invisionapp.com/d/main#/console/14872865/311557168/preview#project_console
CPA: @luizapeixe pode atualizar nos comentários dessa issue o wireframe desse toast derivado para o CPA?

Atualmente, está estourando no django. Trace do erro:

Request Method: | POST
-- | --
http://dev.ejplatform.org/conversations/add/
2.0.8
IntegrityError
duplicate key value violates unique constraint "ej_conversations_comment_conversation_id_content_fefe6483_uniq" DETAIL:  Key (conversation_id, content)=(28, oi) already exists.
/pypackages/lib/python3.6/site-packages/django/db/backends/utils.py in _execute, line 85
/usr/bin/python3
3.6.6
['/app',  '/usr/local/bin',  '/app/src',  '/app',  '/pypackages/lib/python3.6/site-packages',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages',  'src',  '/app']
Qui, 23 Ago 2018 14:58:47 -0300

**Comment by ricardopoppi** [comment]
@BrunaNayara @LeoSilvaGomes pode mandar o PR da branch dessa issue com o label [WIP] se ainda não estiver pronto?

**Comment by LeoSilvaGomes** [comment]
Irei verificar! adicionarei essas modificações no outro PR que eu fiz para um erro que eu encontrei. 
[REVIEW] Adjust code to toast #541

**Comment by ricardopoppi** [comment]
resolvido com o seu commit @LeoSilvaGomes, tudo certo! passando essa issue de staging pra done!
