### ISSUE TITLE
A tela de moderação de conversa não organiza os comentários aceitos ou rejeitados

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#379]
@luizapeixe precisamos bolar uma solução para situação de muitos comentários. Creio de devam existir abas (ou algo do tipo) que separe os comentários que estão aguardando moderação/aprovados/rejeitados.

Inicialmente pode trabalhar nesse wire aqui: https://projects.invisionapp.com/d/main#/console/13863876/303751467/preview - a gente aprovando deriva pro CPA

**Comment by luizapeixe** [comment]
Gosta da solução das abas, @ricardopoppi !

aí vai uma proposta pro EJ
aba EM MODERAÇÃO: https://invis.io/SRNPGWGPM3A
aba APROVADOS: https://invis.io/3YNPGYVZFST
aba REJEITADOS: https://invis.io/U2NPGZ0Z6QE

obs1.: Sobre a implementação, é importante que quando o user clicar pra mudar de aba, a página carregue na mesma altura de scroll de antes do clique.
obs2.: Nas abas APROVADO e REJEITADO, reparem que a ação selecionada (botões de Aprovar ou Rejeitar) fica com 100% de opacidade enquanto a não selecionada fica com 30% de opacidade. O ideal é que qnd o user passar o mouse hover (na versão desktop) a opção em 30% fique com 100%, para deixar evidente que o user admin ainda pode APROVAR um comentário REJEITADO e vice versa.

Em breve envio a versão CPA

**Comment by luizapeixe** [comment]
Segue CPA também alterado

aba EM MODERACAO: https://invis.io/NHNPHURXSZV
aba APROVADOS: https://invis.io/PXNPHVXTMJ5
aba RECUSADOS: https://invis.io/6XNPHW6FUZC

**Comment by ricardopoppi** [comment]
obrigado @luizapeixe, passei pra implementação na issue #387 fechando essa aqui
