### ISSUE TITLE
Conceber como repercutir ao usuário erro de conteúdo de comentário identico

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#380]
Como repercutir para o usuário na tela de criação de conversa quando (de proposito ou por erro) o usuário coloca dois comentários com o mesmo conteúdo? Como o envio só é feito quando ele pressiona o botão criar, teria que ser algo como um toast combinado com uma msg abaixo do campo de comentário onde o erro ocorreu.

@luizapeixe pode conceber?

Ver print da tela: https://dev.ejplatform.org/conversations/add/

![captura de tela de 2018-08-23 15-19-55](https://user-images.githubusercontent.com/1162183/44544354-572d2500-a6e8-11e8-9902-ad5267d8c2c8.png)

**Comment by luizapeixe** [comment]
Ok!

Aí vai uma proposta dessa página com o toast apontando duplicidade nos comentários: https://invis.io/5QNPK1ZCZ3T

Dúvida: aquela tela de criação de conversa https://invis.io/ZPN5XYV43DR está ultrapassada, certo? Devo substituí-la por essa nova alterada? Faço o mesmo no CPA?

**Comment by ricardopoppi** [comment]
Valeu Luiza, vou encaminhar o toast pra implementação.

Sobre a criação, realmente tivemos que fazer alguns ajustes direto em código. Nessa tela da issue ainda falta o link do board que não tá carregando de primeira pra mim. A melhor referência pra atualizar os wires é usando o App mesmo e pegando das telas implementadas. Inclusive vc pode propor melhorias usando as telas implementadas como base. Peço que considere isso no seu to-do

**Comment by ricardopoppi** [comment]
aberta a #377 para implementação, fechando essa
