### ISSUE TITLE
Rota de login/registro em tela de usuário deslogado deveria preservar a url da conversa

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#381]
Quando o usuário deslogado acessa uma tela de conversa, ele vê a informação de que deve fazer login.

Porém ao fazê-lo, não retorna para a tela de conversa. A rota de login/registro deveria preservar a url para retornar o user para o contexto que ele estava.

Ex: https://dev.ejplatform.org/conversations/saude/

**Comment by fabiolamfleury** [comment]
Resolvido :)

**Comment by ricardopoppi** [comment]
testado e funcionando lindo
