### ISSUE TITLE
Ajustes de acessibilidade (leitores de tela)

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#388]
- [x] Cabeçalhos de títulos – evitar a presença de título principal 2 vezes, dificulta a leitura;
- [ ] Quando avançamos a conversa o leitor começa a ler novamente toda a página até chegar ao novo comentário. Alguma indicação deve ser dada ao leitor para que leia apenas o novo comentário que foi carregado.
- [x] Algumas imagens estão sem descrição. É preciso atualizar a descrição de todas as imagens
- [x] Os botões nem sempre estão com a indicação do que se trata, sendo lido primeiramente todos os botões e depois o que são eles. O ideal é que o leitor ao passar no botão já faça a indicação do que se trata;
- [x] Os formulários para preenchimento deverão vir com a indicação do que se trata cada campo

**Comment by lucashm** [comment]
Então, alguns detalhes importantes com relação à essa issue:
- A depender do leitor de tela utilizado, diferentes resultados podem ser visualizados. No momento, testei o chromeVOX (plugin do chrome) e o VoiceOver (aplicação padrão do iPhone). Cada um se comportava de um jeito em cada trecho do site.
- Nenhum desses dois leitores que eu utilizei possuiam a feature de "ler a página inteira" assim que passo a conversa... Todos eles liam trechos que eu selecionava.
- No geral, temos que levar em conta que a própria tecnologia web tem seus limites com relação à acessibilidade. Claro, há muito o que melhorar no EJ com relação à isso... mas acho que um estudo mais aprofundado, juntamente com "wireframes" mais detalhados de como o leitor de tela deve se comportar, são coisas importantes a se fazer antes disso tudo!

**Comment by lucashm** [comment]
De todo modo, estou dando uma geral por cima do EJ inteiro, cobrindo alguns detalhes mais grosseiros (como as imagens sem alternatives ou os títulos dobrados). No mais, acho que um maior respaldo com relação à esse tópico seja necessário pra se seguir em frente!
