### ISSUE TITLE
Trocar o ícone do painel CPA

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#389]
O ícone do painel cpa deve ser o que está nesse wireframe: https://projects.invisionapp.com/share/ZTNJDBZEQCA#/screens

**Comment by ricardopoppi** [comment]
estou voltando essa issue pra inprogress, pois ela só pode ser fechada quando o pr for aceito.

**Comment by LeoSilvaGomes** [comment]
Issue já resolvida
