### ISSUE TITLE
Refatorações DevOps para Otimizar Pipelines

### ISSUE THREAD

**Issue by arkye** [ejplatform/ej-server#39]
- [x] Criar Dockerfile base (`ej-server:base`) com o máximo da estruturação essencial do sistema;
- [x] Aplicar a base no `ej-server:staging` e `ej-server:latest`
- [x] Aplicar a base no local/test
- [ ] Entrypoint executar tasks `inv`
- [x] Trocar o nome do diretório `compose` para `docker`
- [x] Isolar os composes em uma pasta fora da raíz
- [x] Otimizar GitLab CI/CD
- [ ] Investigar necessidade de Sidekick do Nginx no Deploy

**Comment by luanguimaraesla** [comment]
Alterei o comportamento do ambiente de desenvolvimento. Agora ele espera uma variável de ambiente do host chamada `MANUAL_MODE`, essa variável pode ser registrada em um arquivo `.env` na raiz do projeto. Caso ela não exista, o docker-compose atribuirá uma string vazia para esta variável dentro do container, então ele executará assim como antes:

1. Roda as migrações
2. Executa o runserver_plus

Caso essa variável seja setada para `false`, o container também se comportará como foi descrito acima. Contudo, caso a variável seja `true`, o container do django entrará em estado de espera infinita para que tenhamos mais flexibilidade para executar comandos dentro do docker. Acessamos o terminal através do seguinte comando:
```bash
sudo docker-compose exec django bash
```
