### ISSUE TITLE
Conceber os wireframes do funcionamento da mecanica de gamificação da V2

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#391]
Criação das telas da v2 da gamificação:

#### Ponte de diálogo
Players que estão na fronteira entre dois cluster, que em tese podemos concluir que eles têm opiniões que possa dialogar com os membros de ambos os cluster. Pessoas com este tipo de perfil, podem funcionar como uma pessoa que transfira informações e entenda o que pode ser dito pelo pessoal mais centrado em algum cluster. Desta forma, é possível explorar as opiniões dessa pessoa, fazendo opiniões divergente e convergentes trabalharem juntas, levando informações para um lado e para o outro que faça ele se tornar um “diplomata” entre pessoas que estejam alienadas com uma só visão.

Foco: Fazer interação entre dois clusters.

Pegaremos uma pessoa por borda, a pessoa que é a própria borda. Qual o critério? ML vai definir uma métrica que indica quando uma pessoa é mais borda que a outra. Se tiver empate a gente sorteia um dos perfis. 
48H para exercer o poder, 24H de duração para o efeito do poder
Os destinatários do poder são os membros dos dois clusters limítrofes
O poder roda a cada 3 dias

##### Como gerar o interesse no ponte em falar?
Escassez de tempo (48h)
O poder consiste na promoção de um próprio comentário/se não tem comentário incentiva a fazer e o comentário já nasce promovido
O comentário inserido no contexto do poder não consome o limite de comentário das conversas

##### Como viabilizar que ele seja escutado?
Quem recebe o push notification: todos que fazem parte dos clusteres limítrofes
(mesmo sabendo que há riscos de flood, vamos dar meios acessíveis para o usuário limitar o recebimento dos pushes pelo lado do recebimento e não pelo lado da oferta)

##### Limite de pushes que o usuário vai receber ser facilmente configurável

Por conversa (eventualmente no painel de conversas disponível atualmente no perfil do usuário)
Limite global de notificações facilmente a mão
As notificações de troféu e achievements da v1 da gamificação não mandar push, ser informada via toasts

#### Ativista de minoria
Players que estão dentro de um cluster, tem opinião com altos indices de concordancia no grupo, mas que em algum momento demonstraram opiniões divergentes em relação a maioria da conversa. Isto lhe transforma em uma pessoa que consegue dialogar facilmente com as pessoas daqueles cluster e que pode também mostrar uma visão diferenciada daquilo que estão costumados a ver. O critério que define um ativista de minoria é um usuário que:
(i) A pessoa tem um comentário feito em algum conversa;
(ii) Esse comentário tem taxa de aceitação superior a 60% dentro do seu próprio cluster;
(iii) A pessoa discorda de alguma opinião majoritária (superior a 60%) da conversa;

Foco: Fazer pessoas de um cluster observarem outra perspectiva. 

Possíveis métricas: Quantidade de pessoas que começam a se espelhar no que é compartilhado pelo ativista de minoria

##### Ordem da análise:

Condições que devem ser satisfeitas para a obtenção do poder (só passa para a próxima condição e a anterior for verdadeira):

(i) Verificar qual o comentário (A) mais concordado no cluster dentre os comentários feitos por pessoas daquele cluster (acima de 60%)
(ii) O autor desse comentário (A) vota oposto à maioria da conversa em um comentário (B) (maioria da conversa = mais de 60% dos participantes) 
(iii) Mais de 60% dos membros do cluster do autor vota oposto à ele nesse comentário (B) específico 
(iv) Dá o poder para esse autor, marca o comentário (A) dele como “wasted” (pra não ser avaliado na próxima vez que a lógica rodar nesse cluster) e o comentário (B) também deve ser marcado como wasted para esse mesmo perfil de ativista

##### Como viabilizar ao ativista falar pro grupo?

Escassez de tempo (48h)
O poder consiste na promoção de um novo comentário que já nasce promovido
A opção de entrada de novo comentário deve ser feita dando contexto ao ativista sobre o assunto do comentário (B), aquele que ele votou de forma oposta à maioria
O comentário inserido no contexto do poder não consome o limite de comentário das conversas

##### Como viabilizar que ele seja escutado?

Quem recebe o push notification: todos que são membros do cluster do ativista (mesmo sabendo que há riscos de flood, vamos dar meios acessíveis para o usuário limitar o recebimento dos pushes pelo lado do recebimento e não pelo lado da oferta)

**Comment by fabiommendes** [comment]
Gente, estou com uma dificuldade de formalizar o ativista de minoria. Do jeito que está, teremos vários ativistas (possivelmente o grupo inteiro) e não existe um critério de seleção entre os diferentes indivíduos.

Além disso, o poder dado não parece fazer muito sentido pra mim pq não tem nenhum benefício claro. Lembro que estávamos falando da lógica de promover comentários e pra mim isso parece melhor do que essa mecânica de "wasted"

**Comment by ricardopoppi** [comment]
Complementarmente, talvez a gente possa seguir sua sugestão e chegar no mesmo lugar. Mas teríamos que adicionar o componente da maioria, esse ficou faltando. Teria que ser algo assim:

1. O ativista sai do grupo dos X% (25?) mais próximos do centro
2. Deste, selecionamos o que tem o comentário com maior discordância no grupo
3. Verificamos se ele vota contrário a algum comentário com mais de 60% de votos na conversa (e que ao mesmo tempo tenha mais de 60% de votos no proprio grupo dele, no mesmo sentido da maioria)
4. Se 3 for "false", volta pro 2 e pega o segundo colocado, e até dar "true" no passo 3

Poder:
Promover este comentário ou criar um novo comentário sobre o mesmo tópico

**Comment by ricardopoppi** [comment]
fechando essa pois os ulitimos comentários já foram feitos no invisio
