### ISSUE TITLE
Navbar está fixa em algumas paginas e auto-ocultante em outras

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#393]
Parece que houve uma tentativa de mudar o comportamento mas não foi feito em todas as páginas

**Comment by caiosba** [comment]
Resolvido em https://github.com/ejplatform/ej-server/pull/413. Atribuí a revisão para o @fabiommendes.

**Comment by ricardopoppi** [comment]
Fechando a issue pra ela passar pra staging

**Comment by luizapeixe** [comment]
testando aqui constatei que:

auto-oculta:
- interna da conversa
- lista de conversas
- sobre
- perguntas frequentes
- fale conosco
- termos de uso

não oculta:
- perfil -> https://cpa.dev.lappis.rocks/profile/

notei um comportamento estranho quando ela reaparece depois de auto-ocultar. As vezes aparece um background branco sob o gradiente logo acima da navbar, vejam:

![captura de tela 2018-09-10 as 18 06 59](https://user-images.githubusercontent.com/6249788/45324390-5e479600-b524-11e8-9805-d669039df0dc.png)

Isso não acontece na página de perfil, onde a navbar não oculta.

**Comment by ricardopoppi** [comment]
estou reabrindo essa issue pois o PR ainda não foi aceito na master para homologação. essa issue só será fechada quando o PR for aceito, aí será fechada automaticamente, se houver msg de close no commit, ou manualmente pelo autor ou assignee
