### ISSUE TITLE
Criar grupos de cada cluster da conversa

### ISSUE THREAD

**Issue by BrunaNayara** [ejplatform/ej-server#397]
Cada grupo de uma conversa deve estar em um grupo para que possam receber as notificações (caso não estejam desativadas) dos perfis de gamificação.
- [ ] Criar as permissões e especificidades dos grupos
- [ ] Cada cluster de uma conversa deve estar em um grupo

**Comment by ricardopoppi** [comment]
fechando essa pois a #437 substitui
