### ISSUE TITLE
Expor dados com informações de perfil do usuário

### ISSUE THREAD

**Issue by fabiommendes** [ejplatform/ej-server#399]
Incluir opção de adicionar informações do perfi na exportação de dados CSV nos reports

**Comment by alexandrebarbaruiva** [comment]
@fabiommendes vc pode adicionar mais detalhes a esta issue?

**Comment by fabiommendes** [comment]
Documentando as mudanças:

* Incluir informações do perfil do usuário (genero + idade + profissão, etc) no CSV gerado
