### ISSUE TITLE
Validação de username do Rocket.Chat

### ISSUE THREAD

**Issue by fabiommendes** [ejplatform/ej-server#401]
Fazer a validação do Rocket.Chat corretamente. Por enquanto ele valida algumas coisas mas não cobre todas as possibilidades. O Django deveria consultar a API do Rocket antes de tentar criar o usuário e registrar um erro no formulário quando tiver problemas de login.

**Comment by ricardopoppi** [comment]
@leandronunes chegou a futucar essa tb? talvez vc precise que o @fabiommendes faça coach pois ele que desenvolveu a integração
