### ISSUE TITLE
A navbar do rocket está sendo cortada na parte inferior

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#402]
A barra do rocket, que contém emojis, anexos, e botão de enviar, está sumindo no celular. No computador e instalando o app (pwa adicionado à home screen) não apresenta esse problema.
Problema:
![image](https://user-images.githubusercontent.com/4125846/45053139-78ceca80-b05f-11e8-9850-7c70d2c11c40.png)

Esperado:
![image](https://user-images.githubusercontent.com/4125846/45053195-a451b500-b05f-11e8-8c37-b6c320ff93c6.png)

**Comment by ricardopoppi** [comment]
@leandronunes futucou nessa?

**Comment by leandronunes** [comment]
@ricardopoppi já tinha ajeitado isso a um tempo, mas pode ter sido umas das coisas que se perdeu naquele lance do banco...
Vou retestar

**Comment by leandronunes** [comment]
Não consegui reproduzir o erro.
Segue a imagem.
![rocket](https://user-images.githubusercontent.com/28972/45458489-4d388980-b6ca-11e8-8452-ebed240c700f.png)

**Comment by ricardopoppi** [comment]
fechando essa por enquanto já que não foi possível simular e o @leandronunes está trabalhando numa nova proposta de integração
