### ISSUE TITLE
Criar as guidelines para contribuição de código no EJ

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#407]
Ex:

- nome da branch term o # para o github linkar automaticamente
- ajustar o template de pull request (com as sugestões feitas na reunião de apresentação)
- incluir nas guidelines a prática de squash pelos desenvolvedores (O MAIS IMPORTANTE: contar uma boa história para os revisores!)

**Comment by fabiolamfleury** [comment]
@valessiobrito coloquei referências, no doc compartilhado via telegram, dos trabalhos realizados de documentação na wiki, como mais é possível contribuir nessa parte de documentação do desenvolvimento

**Comment by valessiobrito** [comment]
@fabiolamfleury desculpa a demora em responder, estive trabalhando com a doc do usuário e só agora vou focar na parte do Devel.   Como comentei com você, precisamos ver como potencializar a documentação através das _docstrings_ (documentação embutida no código) e como renderizar isso no Sphinx.

Vi seus comentários e doc. ref. no Wiki, colocando os links aqui para registro:
* https://github.com/ejplatform/ej-server/wiki/Pol%C3%ADticas-de-Reposit%C3%B3rio
* https://github.com/ejplatform/ej-server/wiki/Guia-Docker
