### ISSUE TITLE
Dar feedback para o usuário que envia um comentário

### ISSUE THREAD

**Issue by BrunaNayara** [ejplatform/ej-server#409]
Atualmente, ao escrever um comentário, a pessoa é avisada que o comentário foi recebido. Mas não fica claro o que acontece com o comentário (ele não aparece na tela, não tem explicação dos próximos passos, quem terá acesso a ele para ler ou votar)

**Comment by Heloisecs** [comment]
feedback já existia como toast notification,  avisando que ele está sob moderação (se o usuário clica no toast ele é levado à seção de comentários no perfil
