### ISSUE TITLE
No modo acessibilidade, aumentar o font-weight do subtexto que fica nos imputs de cadastro e login

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#412]
Atualmente, essa fonte está conforme o print abaixo. Identificamos que esse poderia ser um ponto de dificuldade para pessoas com alguma defciencia visual. Formulamos então uma nova proposta aumentando o font-weight desses textos: https://projects.invisionapp.com/share/7KNQEMIBJW3#/screens

ATUALMENTE ESTÁ ASSIM:

![photo_2018-08-22_18-08-03](https://user-images.githubusercontent.com/1162183/44491190-d3ffc680-a636-11e8-874b-f224b9022c7b.jpg)

**Comment by gag2502** [comment]
@luizapeixe @Heloisecs concluí essa correção e está no commit "Fix login inputs font weight in high contrast mode" na branch devel , por favor validar.

**Comment by luizapeixe** [comment]
@gag2502 tentei acessar pelo https://cpa.dev.ejplatform.org/ para validar essa correção mas o site não tá entrando corretamente. Confirma pra mim a url correta de acesso pra validação por favor?

**Comment by fabiolamfleury** [comment]
@luizapeixe Agora o link pro cpa é: https://cpa.dev.lappis.rocks/start/

**Comment by ricardopoppi** [comment]
estou reabrindo essa issue pois ela só será fechada quando o PR for aceito na master

**Comment by ricardopoppi** [comment]
@gag2502 pode abrir o PR dessa issue? vamos incorporar na Ada Lovelace

**Comment by gag2502** [comment]
@luizapeixe pode revisar novamente por favor ?

**Comment by gag2502** [comment]
@luizapeixe   o código está na branch i412_fix_high_contrast_font

**Comment by luizapeixe** [comment]
> @luizapeixe pode revisar novamente por favor ?

claro. qual URL posso acessar pra revisar? o https://ej.staging.lappis.rocks/ não estão entrando pra mim. "502 Bad Gateway" :/

**Comment by ricardopoppi** [comment]
@luizapeixe essa melhoria só poderá ser revisada qdo esse PR entrar no código: https://github.com/ejplatform/ej-server/pull/490

O link para revisão é ejdev.lappis.rocks pro generico e cpadev.lappis.rocks pro cpa
