### ISSUE TITLE
Criar proposta de visualização desktop do EJ

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#418]
@luizapeixe não é necessário desenhar todas as telas, mas apenas os elementos que diferenciam do mobile pra desktop. Exemplo:

1) menu hanburguer vira um menu fixo aberto (ex do besouro)
2) limitação de largura
3) etc

**Comment by luizapeixe** [comment]
Segue uma primeira proposta do template desktop do EJ -> https://invis.io/82O3843PJDS
O que acham?

**Comment by ricardopoppi** [comment]
@luizapeixe tá ficando bem legal! Podemos fazer um exercício de mudar um pouco o contraste do menu? minha preocupação é que a tela pode ficar muito inundada de azul, pelo fato do menu estar permanentemente aberto (o que foi uma ótima proposta)

**Comment by ricardopoppi** [comment]
@fabiommendes @valessiobrito @BrunaNayara vamos aprovar a proposta? creio que isso não entra na Ada mas entra na próxima

**Comment by ricardopoppi** [comment]
fechando essa e passando pra implementação na issue #557
