### ISSUE TITLE
Ativar lógica do "esqueci minha senha" para os usuários

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#419]
Inclui:

- [x] Tela para o usuário inserir o email  (esqueci minha senha)
- [x] Lógica da url única (id) que é enviada por email
- [x] Tela para reset da senha

**Comment by lucashm** [comment]
Terreno pronto! Só precisamos do serviço de e-mail para finalizar a issue.

**Comment by ricardopoppi** [comment]
Maravilha que o terreno tá pronto! Hj mais cedo passei pra @gag2502 o acesso do mailgun pra configurar os emails. Qq dúvida que tiverem avisem.

**Comment by ricardopoppi** [comment]
@gag2502 @lucashm como está essa? podem mandar o PR?

**Comment by ricardopoppi** [comment]
@gag2502 testando essa feature em dev, o django exibiu um erro (abaixo). Poderia orientar se falta algo no servidor?

Para replicar:
1) crie um usuário novo em http://dev.ejplatform.org
2) faça logout
3) vá em esqueci minha senha
4) insira o email do usuário recém criado




ERRO:


Request Method: | POST
-- | --
http://dev.ejplatform.org/recover-password/?next=/conversations/
2.1.2
ProgrammingError
relation "ej_users_token" does not exist LINE 1: INSERT INTO "ej_users_token" ("url_token", "user_id", "date_...                     ^
/pypackages/lib/python3.6/site-packages/django/db/backends/utils.py in _execute, line 85
/usr/bin/python3
3.6.6
['/app',  '/usr/local/bin',  '/app/src',  '/app',  '/pypackages/lib/python3.6/site-packages',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages',  'src',  '/app']
Qua, 10 Out 2018 22:48:11 -0300

**Comment by ricardopoppi** [comment]
Sobre essa issue (cc @fabiolamfleury @fabiommendes @gag2502 @lucashm). Testando em dev, quando insiro o email pra envio da senha dá um erro:


Request Method: | POST
-- | --
http://dev.ejplatform.org/recover-password/?next=/conversations/
2.1.2
SMTPServerDisconnected
please run connect() first
/usr/lib/python3.6/smtplib.py in send, line 359
/usr/bin/python3
3.6.6
['/app',  '/usr/local/bin',  '/app/src',  '/app',  '/pypackages/lib/python3.6/site-packages',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages',  'src',  '/app']
Qui, 11 Out 2018 15:01:47 -0300

**Comment by ricardopoppi** [comment]
resolvido pela @fabiolamfleury
