### ISSUE TITLE
O input de imagem não aparece ao editar perfil

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#425]
Tanto para o Generico quanto para o CPA. Conforme print do generico:

![captura de tela de 2018-09-13 15-22-48](https://user-images.githubusercontent.com/1162183/45507629-08176480-b769-11e8-8f9a-70b5791a8119.png)

**Comment by MatheusRich** [comment]
@ricardopoppi Parece que o @fabiommendes comentou o código existente. Provavelmente não estava da maneira padrão de ser feita. @fabiommendes alguma orientação sobre o que deveria ser feito?

```python

{% block content %}
    <div class="ProfileEdit">
        <form method="post" enctype="multipart/form-data" action="">
            {{ csrf_input }}
            {{ form.as_p() }}
            {{ form.non_field_errors() }}
{#            <div class="FormItem CustomFileInput">#}
{#                <div>#}
{#                    {{ _('Choose a file') }}#}
{#                </div>#}
{#                <div id="image-filename">#}
{#                    {{ _('No file chosen') }}#}
{#                </div>#}
{#            </div>#}
            <input class="Button" type="submit" name="submit" value="{{ _('Save') }}">
        </form>
    </div>
{% endblock %}
```

**Comment by ricardopoppi** [comment]
@MatheusRich pode vir amanhã de manhã e conversar com o @fabiommendes pessoalmente sobre esse PR?
