### ISSUE TITLE
Converter scatter e tabelas  do ej_reports para roles

### ISSUE THREAD

**Issue by alexandrebarbaruiva** [ejplatform/ej-server#426]
exemplo em ej_conversations/roles.py

Refatorar funções de acordo com sugestões do @fabiommendes

**Comment by alexandrebarbaruiva** [comment]
Passar as funções de scatter e tabelas para o data_viz, manter no ej_reports perdeu sentido

**Comment by ricardopoppi** [comment]
@alexandrebarbaruiva pode mandar o PR da branch dessa issue, usando o label [WIP] no título se ainda não estiver pronto?

**Comment by alexandrebarbaruiva** [comment]
scatterplot taggeado com genero (cor dos pontos homem mulher etc)

**Comment by alexandrebarbaruiva** [comment]
verificar cor e formato no echarts
