### ISSUE TITLE
Rota /profile/conversations está quebrada

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#427]
Vale tanto para genérico quanto para cpa

Para simular:
1) faça login
2) clique em "minhas conversas"

Erro: TemplateDoesNotExist at /profile/conversations/ ej_conversations/conversations-list.jinja2 Request Method: GET Request URL: http://ej.staging.lappis.rocks/profile/conversations/ Django Version: 2.0.8 Python 

Print:

![captura de tela de 2018-09-16 15-19-39](https://user-images.githubusercontent.com/1162183/45599573-4c527100-b9c4-11e8-8f7d-844fb0934f76.png)

**Comment by fabiolamfleury** [comment]
Percebi alguns problemas enquanto lidava com essa issue:

- Na criação de conversa, o campo de descrição está sendo salvo como o slug
- Apenas pode criar uma conversa usuário que tem permissão para promover conversas (mesmo que o usuário tente criar dentro do próprio board)

Estou criando correções para estes problemas

**Comment by fabiolamfleury** [comment]
@fabiommendes o campo de slug está como auto slug, então ele é sempre o slugify do title, posso retirá-lo do forms de conversa ou existe alguma necessidade de deixá-lo?
