### ISSUE TITLE
A criação e gerência de esteriótipos apresenta alguns bugs

### ISSUE THREAD

**Issue by fabiolamfleury** [ejplatform/ej-server#435]
- [x]  O constraint de esteriótipos de uma conversa não poderem ter o mesmo nome, não está funcionando

- [x] Depois da criação de um esteriótipo, o redirecionamento  para os clusters não funciona (verificar se foi o template)

- [x] No formulário de criação de esteriótipo, está permitindo a duplicação de um comentário, com votos diferentes. Ou seja, o esteriótipo pode concordar e discordar com o comentário, por exemplo

- [x] O formulário de criação de esteriótipo não relaciona o esteriótipo a uma conversa

- [x] Criação duplicada de conversa

- [x] O criador da conversa não consegue fazer comentários pela página da conversa. (Aconteceu após a criação de conversa com vários comentários, quando houve tentativa de acrescentar mais comentários pela página da conversa)

- [x] Quando um usuário comum tenta visualizar quantos comentários ele ainda pode fazer na conversa, aparece o texto 'False' (dentro da página da conversa)

- [ ] Validação de comentário: falando que já existe um comentário com aquele conteúdo, mas não existe e quando o comentário tem só um char também, dá exceção

**Comment by ricardopoppi** [comment]
@fabiolamfleury sobre os clusteres, a criação de estereótipo deveria disparar um gatilho pra criação dos clusteres correspondentes, na relação 1 cluster para cada estereótipo. Fizemos essa simplificação para o usuário não ter que criar os dois tipos de elementos, apenas o primeiro (estereótipo).

**Comment by fabiolamfleury** [comment]
@ricardopoppi Exato, mas acredito que houve alguma falha na implementação em relação a forma como estão os relacionamentos e o ml trabalha vou tomar cuidado com esse detalhe durante correção

**Comment by ricardopoppi** [comment]
@fabiolamfleury ótimo!
