### ISSUE TITLE
Home do CPA não está exibindo as conversas públicas, apenas os estáticos

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#441]
Conforme print:

![photo_2018-09-19_11-29-45](https://user-images.githubusercontent.com/1162183/45759898-557b5200-bbff-11e8-99b2-49373edd1457.jpg)

**Comment by MatheusRich** [comment]
@ricardopoppi Este é um problema no deploy? Não consegui reproduzir na última versão da develop.

![image](https://user-images.githubusercontent.com/20938712/45955710-00688300-bfe7-11e8-953b-408c78c98092.png)

**Comment by ricardopoppi** [comment]
@MatheusRich me refiro a home deslogada, a /start - como está ela na ultima versão da develop?

**Comment by MatheusRich** [comment]
@ricardopoppi Estava investigando esta issue e ela realmente acontece. Pelo que encontrei uma das mudanças foi ocasionada [por este commit](https://github.com/ejplatform/ej-server/commit/b4d09fbf49617894e00cdc6837654ce32d6a5a60#diff-1c1da32a72710519299b9b4d6eaea6c8) do @fabiommendes. Não sei exatamente a razão, podemos discutir isto?
