### ISSUE TITLE
Carrossel de logos da home inst do ej generico está cortado no final da página

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#442]
Conforme print:

![photo_2018-09-19_11-29-49](https://user-images.githubusercontent.com/1162183/45760036-95dad000-bbff-11e8-86c3-5b09dc85798c.jpg)

**Comment by lucashm** [comment]
![image](https://user-images.githubusercontent.com/16053704/45768581-a4cb7d80-bc13-11e8-9a09-5228084593bf.png)
não consegui reproduzir... tanto em dev local quanto em staging. Fazendo um diff com relação à versões antigas, nota-se somente que as setas estão um pouco mais abaixo do que deviam, mas não chegar a ser cortadas... vou ver se corrigindo a altura das setas, esse bug também suma.

**Comment by ricardopoppi** [comment]
Boa acho que é um bom caminho

**Comment by ricardopoppi** [comment]
Fechando essa issue pra ela ir a staging já que o PR dela foi mergeado
