### ISSUE TITLE
Barra inferior "ENTRAR" só aparece qdo scroll está no topo

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#443]
Vale tanto para o genérico quanto para o CPA. Print:

![photo_2018-09-19_11-29-47](https://user-images.githubusercontent.com/1162183/45760168-db979880-bbff-11e8-8219-a642f836e5f2.jpg)

**Comment by lucashm** [comment]
Isso é um bug? Foi modificado pelo Caio um tempo atrás pra só aparecer quando encostar no topo... segue o commit: https://github.com/ejplatform/ej-server/commit/46b4a7b7d815615caf56eec078bbbc152db78629#diff-2b90fe42f6d885637e39a45791086ee2

**Comment by caiosba** [comment]
Exato, a ideia do ticket era exatamente esta: https://github.com/ejplatform/ej-server/issues/393.

**Comment by ricardopoppi** [comment]
Ahhh então foi falta de clareza da issue pois a barra deve aparecer sempre que houver scroll pra cima, mesmo que não tenha chegado no topo

**Comment by lucashm** [comment]
https://github.com/ejplatform/ej-server/pull/455
Retornei ao comportamento anterior... peço a verificação de mais pessoas, visto que essa é uma issue recorrente!

**Comment by ricardopoppi** [comment]
@lucashm a interação planejada para essa barra é seguinte:

(i) sumir qdo o usuário fizer scroll down (some logo que o scroll down começa, não espera chegar no final da página)
(ii) voltar a aparecer quando o usuário fizer scroll up (aparece logo que o scroll up começa, não espera chegar no topo)

O comportamento do pr #455 está assim?

**Comment by lucashm** [comment]
Exato... posso dar o PR? Ainda sim... prefiro uma validação que não seja a minha. Posso dar o PR pra você testar, ou eu posso sentar alguma hora e te mostrar funcionando.

**Comment by ricardopoppi** [comment]
@lucashm pode dar o PR sim, aí eu homologo em staging ;-)

**Comment by ricardopoppi** [comment]
@lucashm eu testei o comportamento está ok! ]

Só te peço verificar pois notei que na página de perfil ela fica sempre visivel, não some nunca. Também não consegui testar na página /conversations e numa interna de conversa pois há um bug na criação de conversas que me impediu de fazer esses testes (já abri issue de back sobre esse bug).

Então te peço só verificar o comportamento dela na pagina de perfil e se ele também está ok tanto na /conversations quanto numa interna de conversa.

**Comment by ricardopoppi** [comment]
Fechando essa issue pra ela ir a staging pois o PR dela já foi mergeado
