### ISSUE TITLE
Tela de criação de quadros está sem estilo

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#446]
@luizapeixe pode conceber? Tanto a versão generica quanto CPA

Veja print do atual:

![captura de tela de 2018-09-19 11-49-27](https://user-images.githubusercontent.com/1162183/45761252-41851f80-bc02-11e8-99ca-7a329f2f357c.png)

**Comment by MatheusRich** [comment]
@luizapeixe Me marca aqui quando finalizar?

**Comment by luizapeixe** [comment]
Eis as telas de criação/edição dos quadros.

EJ genérico: https://invis.io/PAO7XLS2VGS
CPA: https://invis.io/8WO7XLXGCDY

Na tela do EJ Genérico, @Heloisecs e eu já estamos considerando que temos de mais atualizado com relação ao processo de padronização de estilos do EJ genérico.

cc @MatheusRich

**Comment by ricardopoppi** [comment]
issue foi fechada pelo PR https://github.com/ejplatform/ej-server/pull/508
