### ISSUE TITLE
Implementar opção para editar o nome do quadro, quando usuário está dentro do quadro

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#449]
Quando o usuário está dentro do quadro, devemos exibir uma opção para ele editar o nome do quadro. Lembrando que nessa tela (print abaixo) tb vai aparecer o botão padrão de "criar conversa" (conforme apontado na issue #447)

@luizapeixe pode conceber essa opção de editar nome do quadro pro generico e CPA?

Print:

![captura de tela de 2018-09-19 11-58-52](https://user-images.githubusercontent.com/1162183/45762289-6bd7dc80-bc04-11e8-9be5-a7bbe2d1a408.png)

**Comment by MatheusRich** [comment]
@luizapeixe Me marca aqui quando finalizar?

**Comment by luizapeixe** [comment]
Seguem as telas atualizadas para a interna do quadro considerando os recursos de Criar conversas e Editar quadro

EJ genérico: https://invis.io/ZAO7XJZQ9DC
CPA: https://invis.io/82O7XK2D3XW

cc @MatheusRich

**Comment by ricardopoppi** [comment]
@MatheusRich está liberado para implementação. O usúario clicando na edição de quadro, leva para as telas de issue #446, porém ocultando a opção do slug (identificador) pois ele só é configurado na criação do quadro

**Comment by ricardopoppi** [comment]
fechando essa que foi resolvida no PR https://github.com/ejplatform/ej-server/pull/497
