### ISSUE TITLE
Integração com o rocket não conclui acesso do usuário ao painel cpa

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#454]
Para replicar:

1) crie um usuário comum
2) via admin, adicione esse usuário no grupo CPA do django
3) via usuário comum clique no ícone "Painel" na navbar
4) digite o usuário rocket
5) observe que o rocket não carrega no irame

Erro do inspector:
Refused to display 'https://cpa.staging.lappis.rocks/conversations/' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors localhost talks.cpa.staging.lappis.rocks".

**Comment by rodrigocam** [comment]
Não consegui reproduzir o erro aqui @ricardopoppi, segui os passos e ao final ele abriu o painel com a opção de entrar no canal general e tal. Esse é o fluxo normal mesmo? Ao colocar o usuário rocket ele redirecionar pro /talks onde existem os canais e tal?

**Comment by ricardopoppi** [comment]
Sim, esse é o fluxo normal, está correto. Consegue verificar porque em staging ele pode novo login no rocket?

O erro que dá em cpa.staging é: 

about:blank:1 Refused to display 'https://cpa.staging.lappis.rocks/conversations/' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors localhost talks.cpa.staging.lappis.rocks".

Print:

![captura de tela de 2018-09-24 11-37-37](https://user-images.githubusercontent.com/1162183/45958618-4bd25f80-bfee-11e8-944d-5006a1663461.png)

**Comment by ricardopoppi** [comment]
fechando essa por enquanto, já que o @leandronunes está trabalhando numa no proposta de integração
