### ISSUE TITLE
Erro ao usuário nao admin criar conversa no mural (board)

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#466]
Para replicar:

1) Criar um usuário comum (não admin)
2) Logar e ir em "suas conversas"
3) Criar um mural qualquer (board)
4) Tentar criar uma conversa no mural

Rota: https://ejdev.lappis.rocks/ricardouser/conversations/add/
Erro que acontece:

Request Method: | GET
-- | --
http://ejdev.lappis.rocks/ricardouser/conversations/add/
2.1.1
TypeError
render() got an unexpected keyword argument 'renderer'
/pypackages/lib/python3.6/site-packages/django/forms/boundfield.py in as_widget, line 93
/usr/bin/python3
3.6.6
['/app',  '/usr/local/bin',  '/app/src',  '/app',  '/pypackages/lib/python3.6/site-packages',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages',  'src',  '/app']
Ter, 25 Set 2018 12:15:44 -0300

**Comment by fabiolamfleury** [comment]
O que eu consegui investigar desse erro por enquanto: Não consegui reproduzi-lo localmente, fiz algumas pesquisas sobre ele, parece que no django 2.1 houve uma atualização na função render que está com a assinatura diferente.

No ambiente local, estou usando o django 2.0.8, por isso o erro não ocorre, vou conversar com o Pablo para ver como pode ser corrigido

**Comment by fabiolamfleury** [comment]
Corrigido atualizando a versão do taggit-django :)
