### ISSUE TITLE
Os toggles da pagina de perfil não estão mudando de posição quando abertos

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#471]
Nos toggles de Comentários e Conversas Favoritas, a seta "\\/" quando clicada deveria mudar sua posição para "/\\" sugerindo o movimento de subir para ocultar o conteúdo do item clicado.

A mesma coisa acontece nos toggles de dados na tela de edição de perfil. Vejam prints:

![captura de tela de 2018-09-25 14-42-29](https://user-images.githubusercontent.com/1162183/46032257-7f39ea80-c0d1-11e8-8420-6fb54ea7bad1.png)
![captura de tela de 2018-09-25 14-41-04](https://user-images.githubusercontent.com/1162183/46032258-7fd28100-c0d1-11e8-89a5-94bbee5b3146.png)

**Comment by lucashm** [comment]
https://github.com/ejplatform/ej-server/pull/479
PR feito, aguardando review

**Comment by BrunaNayara** [comment]
@lucashm comentei lá no PR. O segundo print ainda tá do mesmo jeito

**Comment by ricardopoppi** [comment]
fechada pelo merge do pr https://github.com/ejplatform/ej-server/pull/479
