### ISSUE TITLE
Nos campos INFO e CONTRIBUIÇÕES da tela de perfil falta elemento que indica ao user em qual sessão ele está

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#472]
Nos campos INFO e CONTRIBUIÇÕES, está faltando um elemento triangular que indica ao user em qual sessão ele está, confirme layouts no invision (ignorar a sessão troféus). 

EJ: https://projects.invisionapp.com/d/main#/console/13863876/300670646/preview#project_console
CPA: https://projects.invisionapp.com/d/main#/console/14015249/302157266/preview

**Comment by luizapeixe** [comment]
Uma atualização importante sobre essa issue!

Confirmei recentemente com a @Heloisecs que, alinhando com a frente de criação da gameficação, a versão mais recente de layout de Perfil de User é essa: https://projects.invisionapp.com/d/main#/console/14872865/311557165/preview

Ou seja, não existe mais o elemento triangular apontado na issue

**Comment by MatheusRich** [comment]
@ricardopoppi Outra coisa: notei que o texto da aba ativa não está em negrito. Devo corrigir isto agora?

**Comment by ricardopoppi** [comment]
@MatheusRich como já foi mergeado, se não foi corrigido o negrito, deixa pra próxima, pode focar nas outras issues :)
