### ISSUE TITLE
Ativar geolocalização para a informação de Cidade/UF no perfil

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#483]
Ativar geolocalização no login para que as informações de UF/Cidade sejam populadas automaticamente

**Comment by kimuraz** [comment]
Issue disponível ainda?

**Comment by BrunaNayara** [comment]
@kimuraz Sim

**Comment by kimuraz** [comment]
Então posso abrir um PR em breve 👍
