### ISSUE TITLE
Na tela de edição de perfil, em ESTADO, não aparece mais uma lista dos Estados Brasileiros

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#487]
Atualmente aparecem só duas opções state e province. Ver print abaixo.

A lista de estados brasileiros pode ser obtida aqui: https://pt.wikipedia.org/wiki/Unidades_federativas_do_Brasil

![captura de tela de 2018-09-26 16-41-39](https://user-images.githubusercontent.com/1162183/46104995-3e160900-c1ab-11e8-89de-9dfd963ff8ea.png)

**Comment by BrunaNayara** [comment]
Quando a issue de geolocalização (https://github.com/ejplatform/ej-server/issues/483) for resolvida, essa daqui ainda faz sentido?

**Comment by ricardopoppi** [comment]
Sim pois a issue de geo tem que definir um dos estados da lista e o usuário deve poder editar no perfil dele se a geo pegou errado ou se ele estava em viagem, por exemplo. Entendo que são issues completares

**Comment by ricardopoppi** [comment]
fechando essa issue pois o PR já foi mergeado. @rafaelmakaha qdo for colocar o número da issue em futuros PRs lembre-se de incluir a palavra "resolves: #\<numero da issue\> pois quando o PR é mergeado a issue já fecha sozinha e vai pra staging
