### ISSUE TITLE
Rota de edição de conversa quebrando para usuário normal autor

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#502]
Para replicar:

1) Crie uma conversa como usuário comum
2) Entre em "moderar conversa"
3) Vá em "editar conversa"

Ex de rota: https://ejdev.lappis.rocks/ricardouser10/conversations/saude-publica/edit/

Erro:

TypeError at /ricardouser10/conversations/saude-publica/edit/ cannot retrieve CSRF token from empty request. Request Method: GET Request URL: http://ejdev.lappis.rocks/ricardouser10/conversations/saude-publica/edit/ Django Version: 2.1.1

**Comment by fabiolamfleury** [comment]
@fabiommendes esse erro poderia estar relacionado com o csrf input do hyperpython? Ele está acontecendo de forma intermitente em algumas rotas e eu não consigo mapear qual é o problema raíz

**Comment by fabiommendes** [comment]
@ricardopoppi , não estou conseguindo reproduzir o bug localmente

**Comment by rodrigocam** [comment]
Faltava uma diretiva with context no template jinja de edit conversation, corrigido!
