### ISSUE TITLE
Texto incorreto sendo exibido na interna de conversa, próximo ao input de comentários

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#506]
Atualmente a interna da conversa exibe um texto "Sem comentários" antes do input de comentário.. Investigando o PO, esse texto é uma tradução da string "No comment".

Essa string está incorreta, deveria ser: **"Leave your comment"**

![captura de tela de 2018-10-02 15-49-07](https://user-images.githubusercontent.com/1162183/46370132-334fee00-c65b-11e8-8c36-395ac8feb544.png)

**Comment by BrunaNayara** [comment]
@ricardopoppi esses textos todos do print deveriam estar em português ou em inglês? 
Eu estou com o navegador em inglês e todos os textos estão em inglês. Não aparece "Sem comentários", aparece "Leave your comment"

**Comment by ricardopoppi** [comment]
valeu @BrunaNayara eu pego essa pois é erro de tradução, vou resolver junto com a minha issue de tradução

**Comment by ricardopoppi** [comment]
tradução corrigida, commit feito direto na develop https://github.com/ejplatform/ej-server/commit/a5b2f3795eee8cc32f3cc745b3e1dc3908307ce5
