### ISSUE TITLE
Django deve validar os tokens de integração com o Rocket

### ISSUE THREAD

**Issue by luanguimaraesla** [ejplatform/ej-server#51]
Se os tokens estiverem incorretos, o que podemos verificar utilizando-os para acessar a API, não permitir que o admin registre no Constance.

Deve-se também adicionar logs para verificar se as chamadas da API estão sendo efetuadas da maneira correta.

No caso de tentativa de login falhar no Rocket, devemos exibir uma página de erro para o usuário ao invés do Iframe travado.

Deve-se arrumar a lógica de login no Rocket para que se não for possível realizá-lo, não levantar uma exceção que quebre o Django. O melhor seria escrever no log e exibir uma tela de erro amigável. Essa melhoria pode estar relacionada com a issue #50.

**Comment by ricardopoppi** [comment]
Fechando por falta de informação, abriremos novamente se detectarmos algum bug relacionado a isso
