### ISSUE TITLE
Criar componente padrão que oculta elementos da tela

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#520]
Criar um compilador de unpoly que oculte partes da página quando o usuário estiver em celular e subir o teclado para input.

Queremos usar assim no html:

```html
<div class="SomeComponent HideOnInput">...</div>
```

No unpoly, criamos um compilador (https://unpoly.com/up.compiler)

```javascript
up.compiler('.HideOnInput', function ($element) {
    doSomethingWithElement($element)
});
```

**Comment by fabiommendes** [comment]
dicas: https://stackoverflow.com/questions/599288/cross-browser-window-resize-event-javascript-jquery

Tem que ouvir

**Comment by LeoSilvaGomes** [comment]
Eu tenho que ocultar os elementos diferentes do que agregam o input ou apenas especificar na página os elementos que agregam o input sem ocultar o resto?

**Comment by LeoSilvaGomes** [comment]
Essa issue ainda está de pé? Estava esperando o retorno, porque ficamos de decidir já que essa parte na verdade era voltada para a remodulação do login. Preciso da opinião do senhores para saber se ainda é necessário, tendo em vista que a remodulação do login já foi feita e pode ser testada.

**Comment by LeoSilvaGomes** [comment]
@ricardopoppi @fabiommendes @BrunaNayara

**Comment by ricardopoppi** [comment]
fechando essa issue pois esse componente não será mais necessário agora
