### ISSUE TITLE
Aprimoramentos da tela interna da conversa

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#521]
Essa nova tela interna de conversa ganhou alguns aprimoramentos:

- [ ] Não exibir o indicador de favoritos no balão

- [ ] Incluir a barra de progresso exibindo quantos comentários ainda falta pro usuário votar

- [x] #596  Implementar a animação que desloca o form de comentário pro local do comentário a ser votado pra deixar claro ao usuário que ele está inserindo um novo comentário na conversa e não simplesmente uma resposta ao comentário anterior. A animação será um FADE: https://user-images.githubusercontent.com/9471715/47521477-7de31580-d869-11e8-9de1-3076f0285c8b.gif

- [ ] Ajustes dos botões de voto
https://projects.invisionapp.com/d/main#/console/14872865/325072065/preview
https://projects.invisionapp.com/d/main#/console/14872865/325072066/preview
https://projects.invisionapp.com/d/main#/console/14872865/325072067/preview

Nova tela:
Antes de clicar no botão "criar comentário": https://projects.invisionapp.com/d/main#/console/14872865/327179066/preview
Após clicar no botão "criar comentário": 
https://projects.invisionapp.com/d/main#/console/14872865/324346893/preview

Detalhe da barra de progresso:
https://projects.invisionapp.com/d/main#/console/14872865/324346895/preview

**Comment by luizapeixe** [comment]
Algumas dúvidas:

1. os indicadores de Tag, Comentários e Votos continuarão aparecendo no balão da Conversa?
2. haverá o link de "Grupos de opinião" abaixo do link de "Criar comentário"?
3. agora que chamamos a antiga Opinião de Comentário, sugiro alterar o texto para "Inclua algo novo, evite comentários semelhantes. Você pode postar até 3 comentários"

Sobre a animação do card, quando vi essa nova solução (que adorei, alias!) quase que automaticamente pensei nessa animação de transição: https://davidwalsh.name/demo/css-flip.php
Por default ficaria exibido o card com Comentários pra votar, e no clicando no "Criar Comentários"
o card dá esse flip dando lugar ao form de Novo Comentário. Acham fazível do ponto de vista técnico? Mais infos potencialmente úteis aqui: https://davidwalsh.name/css-flip

**Comment by ricardopoppi** [comment]
Respostas:

1. Sim, continuarão aparecendo.
2. Sim, podemos manter esse link também, mesmo com o form ativo no lugar do balão de comentário
3. Sim, vc tem permissão pra fazer a alteração do texto versionando o mesmo wireframe?
4. Sobre a proposta do flip. Achamos ótima! A única coisa é que talvez o indicador atual "/\" que precede o texto "CRIAR COMENTARIO" ([wireframe](https://projects.invisionapp.com/d/main#/console/14872865/324346892/preview#project_console)) não se aplique mais e precisaremos pensar em outra solução. Será que seria um botão, a exemplo de outros componentes que já temos no EJ?

**Comment by luizapeixe** [comment]
1. ok!
2. ok!
3. ok! não consigo versionar, mas posso subir uma nova tela alterada no invision e colo o link aqui
4. certo... vou pensar numa solução pra esse botão e publico aqui em breve!

**Comment by luizapeixe** [comment]
telas atualizadas!
- modo Votação: https://invis.io/VAOPR4FB3MG
- modo Criar Comentário: https://invis.io/A9OPR31MTC2
Sobre o tooltip (https://projects.invisionapp.com/d/main#/console/14872865/324346895/preview) podemos manter esse mesmo modelo da tela no Dataviz, já que seu estilo foi adotado como final na etapa de padronização dos elementos

O que acham?

**Comment by luizapeixe** [comment]
> @luizapeixe sobre o 3 e o 4 peço publicar as novas telas no mesmo protótipo indicando o link aqui, aí eu substituo nas issues. vlw!

opa! vc diz o Dataviz e Gameficação?

**Comment by ricardopoppi** [comment]
@luizapeixe isso, no protótipo Dataviz e Gameficação

**Comment by luizapeixe** [comment]
ok! subi as telas para o protótipo Dataviz e Gameficação

• modo votação: https://invis.io/J7OQ978ZUVX
• modo criar comentário: https://invis.io/G5OQ99JQVY8

Sobre a animação, minha sugestão é que por default fica exibido o card com **Comentários pra Votar**, e no clicando no "Criar Comentários" o card dá esse flip [  https://davidwalsh.name/demo/css-flip.php ] dando lugar ao **Form de Novo Comentário**. Acham fazível do ponto de vista técnico? Mais infos potencialmente úteis sobre a animação do flip aqui: https://davidwalsh.name/css-flip

**Comment by ricardopoppi** [comment]
obrigado @luizapeixe!

@Heloisecs pode opinar nessa proposta? são as mesmas telas finais, porém com um ajuste no botão criar comentário que deixa de ser um toggle "/\" e passa a ser um "+" já que a animação não será de toggle e sim de flip: https://davidwalsh.name/demo/css-flip.php - conforme descrição da Luiza no comentário anterior

**Comment by Heloisecs** [comment]
Então, o problema é que o usuário estaria embaixo, e o "+" não indica que está mudando um elemento que está acima, e isso pode confundir. (já tinha comentado com a Luiza, se não me engano)
Penso numa transição mais suave, tipo esse primeiro quadrado "fading" até aparecer https://michalsnik.github.io/aos/
É um pouco dura a animação de flip.

**Comment by luizapeixe** [comment]
Já havíamos sim conversado sobre trocar o ícone de criar comentário. Quando vi no layout final o ícone de criar com a seta pra cima, me pareceu pouco intuitivo porque antes do clique nada ali me sugere que haverá um movimento de algo para cima, só depois do clique que o ícone ganha sentido. 

A sugestão do ícone de "+" não tem a ver com a animação ou o movimento a principio, sua função é evidenciar pro usuário que clicando ali ele criar algo novo, tipo adiciona um novo comentário. 

Independente da animação que vamos adotar, penso que o ícone deve idealmente ilustrar a função do botão e não o movimento da transição de cards

**Comment by Heloisecs** [comment]
É muito incomum ter um botão que abre um novo elemento acima, não é intuitivo. Se for colocar o ícone de "+", sugiro trocar o botão de lugar (embora sua posição seja estratégica) ou ter alguma sinalização extra de que o comentário abre em cima (exemplo, uma seta que apareça e despareça depois de clicar ou - a animação do o elemento de comentário começa imediatamente acima do botão e sobe até o lugar do comentário.

**Comment by luizapeixe** [comment]
é realmente mais usual que as ações de botões aconteçam embaixo deles e não em cima, por isso uma animação drástica pode ser a solução pra situar o user eficientemente. O fato de os cards serem bem distintos (com background de cores diferentes, principalmente) também nos ajuda a evidenciar pro user onde ocorreu a ação do botão. 

A animação de fade-up é mesmo mais suave que o flip, e penso que pode ser igualmente eficiente, já que a fade-up partirá meio que de cima do botão de Criar Conversa, podendo encaminhar o olhar do user pra onde queremos. Vale ver como funcionaria essa animação no Clique invés de no Scroll

**Comment by ricardopoppi** [comment]
@luizapeixe @Heloisecs tentando sintetizar aqui, acho que podemos ficar com o botão "+" por ele refletir bem a função "adicionar" mas com essa ressalva de identificar como vamos trabalhar a animação para que o efeito do botão seja intuitivo ao usuário.

Temos portanto duas opções de animação:
1) Flip: o botão "+" rotaciona para o formato "x", o comentário-pra-votar flipa pra input e o topo da tela do usuário se move pro input aparecer todo
2) Fading: o botão "+" ao ser clicado abre um input no mesmo local que logo em seguida sobe em fading ocupando o espaço do comentário-pra-votar, movendo o topo da tela pro usuario ver o input todo (é isso @Heloisecs? teríamos um exemplo dessa animação funcionando no clique pra gente visualizar?)

**Comment by Heloisecs** [comment]
@ricardopoppi não sei se você queria uma biblioteca já existente de animação, mas fiz uma animaçãozinha no after effects:
![animation](https://user-images.githubusercontent.com/9471715/47521082-6192a900-d868-11e8-927b-6802791428ed.gif)

**Comment by luizapeixe** [comment]
pessoal, to voltando nessa issue pra gente confirmar uma decisão a respeito dos indicadores de **comentários** e **votos** na interna da conversa.

a última tela aprovada está assim por enquanto:
![captura de tela 2018-11-05 as 08 50 06](https://user-images.githubusercontent.com/6249788/47996646-58af9c00-e0e0-11e8-9ca7-e145091354e1.png)

semana passada conversamos @Heloisecs , @BrunaNayara e eu e chegamos a conclusão de que realmente não é necessário apresentar esses indicadores na interna uma vez que eles já estão apresentados no card da conversa e a quantidade de comentários está apresentada na barra de progressão. Estou jogando essa pauta aqui pra gente se alinhar e chegar no modelo final do componente para incluir na documentação de elementos e componentes visuais

**Comment by ricardopoppi** [comment]
@luizapeixe é isso mesmo, a interna não precisa desses indicadores. A retirada deles deixa a ux mais focada na pergunta e nos comentários.

**Comment by luizapeixe** [comment]
maravilha! então seguem links dos layouts atualizados (versionados no board do Dataviz)

- interna da conversa > modal votação: https://invis.io/J7OQ978ZUVX
- interna da conversa > modal comentário: https://invis.io/NXOXZ9GDSZA

**Comment by ricardopoppi** [comment]
@Heloisecs vamos precisar fazer um último ajuste nessa interna a partir de feedbacks que estamos recebendo dos primeiros beta testers. Hoje o criador da conversa só tem acesso ao botão de moderar abaixo do thumbnail (ver print abaixo) e o botão editar apenas na tela de moderação. Para o criador, o ideal seria que a interna da conversa exibisse esses dois botões.

@Heloisecs pode propor como esses dois botões apareceriam para o criador na interna? creio que pode seguir o padrão da forma que esses botões já aparecem em outros contextos, para preservar os componentes, o que acha?

![captura de tela de 2018-11-06 19-18-54](https://user-images.githubusercontent.com/1162183/48094521-83414800-e1f9-11e8-8cd1-e3ba044fef09.png)
![captura de tela de 2018-11-06 19-19-02](https://user-images.githubusercontent.com/1162183/48094527-86d4cf00-e1f9-11e8-80e8-4eb08cea0c34.png)

**Comment by ricardopoppi** [comment]
Conversamos e decidimos que o melhor caminho para essas opções é o menu de "três pontinhos" na tela interna. Para isso @Heloisecs vai fazer uma proposta de como essas opções aparecem em cada tela do EJ
