### ISSUE TITLE
Implementar tela de promoção de comentários

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#522]
Quando um usuário aceita o poder da gamificação ele recebe um modal (issue #523). Ao clicar no modal é direcionado para essa tela, onde poderá promover comentários ou criar um novo que já nasce promovido:

https://projects.invisionapp.com/d/main#/console/14872865/324346888/preview#project_console

**Comment by rodrigocam** [comment]
@ricardopoppi pode me dar acesso a essa parte do invision?

**Comment by ricardopoppi** [comment]
@rodrigocam feito! Te add no prototipo que está essa tela: https://projects.invisionapp.com/d/main#/projects/prototypes/14872865
