### ISSUE TITLE
Implementar modais da gamificação como componente

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#523]
Essa issue tem duas partes. É fundamental que os modais sejam implementados como componentes de modo a poder ser reaproveitados em outras partes do código

- [x] Modais de Boas vindas (que são ativos sempre que o usuário acessar pela primeira vez a plataforma)
https://projects.invisionapp.com/d/main#/console/14872865/324346881/preview
https://projects.invisionapp.com/d/main#/console/14872865/324346880/preview
https://projects.invisionapp.com/d/main#/console/14872865/324346879/preview

- [x] Modais abertos quando o usuário clicou no push de um dos dois poderes 
https://projects.invisionapp.com/d/main#/console/14872865/324346883/preview
https://projects.invisionapp.com/d/main#/console/14872865/324346884/preview#project_console

**Comment by LeoSilvaGomes** [comment]
@Heloisecs 
1º- Esta etapa deve ter animação ao aparecer ou ela deve simplesmente aparecer?
2º- Existe um botão "próximo" e ao lado temos botões para ir e voltar, deve-se ter os dois?
![screenshot from 2018-10-10 15-30-41](https://user-images.githubusercontent.com/38738836/46757772-7f291580-cca1-11e8-9628-6c914659511a.png)

**Comment by LeoSilvaGomes** [comment]
Criação da parte visual do modal do dataviz
https://projects.invisionapp.com/d/main#/console/14872865/324347600/preview
