### ISSUE TITLE
Melhorias na edição de informações do perfil

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#524]
Conforme wireframes

Tela em estado de edição https://projects.invisionapp.com/d/main#/console/14872865/324346891/preview

Tela quando não está em estado de edição https://projects.invisionapp.com/d/main#/console/14872865/324346904/preview

**Comment by fabiolamfleury** [comment]
@ricardopoppi dei uma olhada no invision e parece que existe uma nova implementação de menu, o que faz com que esssa página quando não esteja em estado de edição não tenha botão. Conversei com a @Heloisecs e ficamos na dúvida: é para já fazer a implementação usando o novo menu (existe preocupação em como vai ficar a versão em desktop disso) ou não se implementa com o menu por enquanto?

**Comment by ricardopoppi** [comment]
@fabiolamfleury @Heloisecs de acordo. acho que não vale a pena a gente implementar essa e já passar pra issue do menu. Eu tinha feito um pedido de ajuste e ela não tinha sido criada ainda, acabei de fazer isso: #666

Fechando essa portanto.
