### ISSUE TITLE
Implementar toasts de comentário e voto enviado

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#525]
- [ ] Wireframes com o toast de comentário enviado:
https://projects.invisionapp.com/d/main#/console/14872865/324346892/preview
https://projects.invisionapp.com/d/main#/console/14872865/324346896/preview

- [ ] Toast de voto registrado:
https://projects.invisionapp.com/d/main#/console/14872865/324346897/comments#project_console

**Comment by BrunaNayara** [comment]
O componente de _toast_ já existe e está sendo utilizado para notificar quando um usuário está fazendo um comentário repetido (_ej_conversations_) . Já existe, também, um início de generalização do componente (_ej_). É interessante que essa generalização seja aprimorada e que seja utilizada, inclusive, onde já tem a "não-genérica"
