### ISSUE TITLE
Implementar a inbox de notificações com configurações de frequencia

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#526]
Essa issue tem 3 partes:

- [ ] O inbox onde serão visualizadas as msgs recebidas por notificações (a infra de notificações foi desenvolvida na issue #398)

- [ ] A parte superior onde o usuário configura a frequência em que deseja receber as notificações

- [ ] O toast quando o usuário muda a configuração das notificações (beber do componente da issue #525)

WIREFRAME: https://projects.invisionapp.com/d/main#/console/14872865/324346885/preview

**Comment by lucashm** [comment]
Oi @ricardopoppi ! Perdão pelo atraso no andamento da issue, tive uma semana bem complicada ):
Mas enfim! Conversei com o Rafael sobre essa issue, e reparamos que a parte de notificação ainda não foi implementada... Desse jeito, só podemos criar um conteúdo estático, uma casca para receber melhor essa feature de notificações...
Teria como você conferir como está o andamento da feature de notificações? Enquanto isso, vamos focar em desenvolver em estático, pra não ficarmos ociosos durante o processo :)

**Comment by ricardopoppi** [comment]
@lucashm ola! tudo bem sobre desenvolver estático, por enquanto é isso mesmo. Assim que a mecânica de notificações tiver pronta vcs atualizam. Pra ficar de olho nesse andamento, sugiro monitorar esse PR: https://github.com/ejplatform/ej-server/pull/417

**Comment by fabiolamfleury** [comment]
@lucashm foi sugerido na reunião que vocês puxem a branch a do pr #417 para a branch de vocês para seguirem o trabalho, e conversem comigo caso precisem de ajuda, para que o trabalho seja destravado
