### ISSUE TITLE
Aprimorar o thumbnail da conversa incluindo barra de progresso do usuário

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#527]
Conforme wireframe:
https://projects.invisionapp.com/d/main#/console/14872865/324346900/preview

**Comment by BrunaNayara** [comment]
A barra de progresso será utilizada em outros locais da plataforma. Para evitar replicação de código, implementar componente de acordo com as especificações da issue #515

**Comment by ricardopoppi** [comment]
Para implementar essa issue, basta puxar o número de progresso que atualmente aparece na interna da conversa, conforme print abaixo:

![captura de tela de 2018-10-22 15-33-18](https://user-images.githubusercontent.com/1162183/47311395-01a1c580-d610-11e8-9969-3b8243571982.png)

**Comment by fabiolamfleury** [comment]
Para respeitar a issue #515, como mencionado pela @BrunaNayara, criei um role de conversa, que pode ser usado com um objeto da conversa e, templates jinja2, da seguinte forma:
 ```
{{ conversation|role('progress-bar') }}
 ```

Uma opção de exibição dessa barra é mostrar ou não os números absolutos do progresso(o valor default é False):
True:
![image](https://user-images.githubusercontent.com/20935369/49230115-13784480-f3d6-11e8-9f88-ee1b50a29406.png)

False:
![image](https://user-images.githubusercontent.com/20935369/49230137-1d9a4300-f3d6-11e8-98b4-dcc0fcd7dedc.png)

 ```
{{ conversation|role('progress-bar', show_absolute=True) }}
 ```
