### ISSUE TITLE
Implementar dataviz dos clusteres na conversa

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#528]
- [ ] Implementar o link para o dataviz na página interna da conversa

- [ ] Implementar a primeira metade da página de dataviz

O usuário acessa a página do dataviz da conversa por um link localizado no final da página interna de conversa, conforme [wireframe](https://projects.invisionapp.com/d/main#/console/14872865/324346898/preview): 

![captura de tela de 2018-10-09 18-42-32](https://user-images.githubusercontent.com/1162183/46700468-50546600-cbf3-11e8-8f55-7b302ccdd652.png)

O wireframe da pagina de dataviz é esse: https://projects.invisionapp.com/d/main#/console/14872865/324354574/preview

Essa issue é referente apenas a primeira metade, os clusteres:

![captura de tela de 2018-10-09 18-46-14](https://user-images.githubusercontent.com/1162183/46700613-acb78580-cbf3-11e8-82d9-6b553f68986c.png)

**Comment by ricardopoppi** [comment]
@leandronunes atualizei o corpo da issue com o novo wireframe que inclui uns ajustes. Mas não afeta a primeira parte que é o dataviz dos clusteres

**Comment by caiosba** [comment]
JSON sugerido:
`
[ 
  {
    sets: ['A'], size: 12
  },
  {
    sets: ['B'],
    size: 12
  },
  {
    sets: ['C'],
    size: 12
  },
  {
    sets: ['A','B'], 
    size: 2
  },
  {
    sets: ['A','C'],
    size: 2
  },
  {
    sets: ['B','C'],
    size: 2
  },
  {
    sets: ['A','B','C'],
    size: 2
  }
]
`
Basicamente, estamos tratando aqui de diagramas de Venn. A ideia é que o JSON represente os valores de cada um dos conjuntos isoladamente e das interseções entre eles.

**Comment by caiosba** [comment]
O que acham do JSON sugerido acima, @fabiommendes @ricardopoppi @alexandrebarbaruiva

**Comment by fabiommendes** [comment]
Legal! Vou começar a trabalhar no back para gerar esses dados hoje. Você está trabalhando em alguma branch com esses dados?

**Comment by fabiommendes** [comment]
Minha proposta de algoritmo:

1) ML define o quais são os clusters (atualmente usamos k-means)
2) Calculamos quantos usuários cada grupo i contribui para o grupo j
3) Essa relação não é necessariamente transitiva, então usamos o menor valor de G_ij para representar a interseção entre os dois grupos.

Para calcular a contribuição de cada grupo para os outros:
1) Calculamos a posição do individuo em uma linha que liga cada cluster i ao j. Definimos a porcentagem de pertencimento como sendo a fracao do caminho percorrido entre o centro de um cluster com o outro. Esse numero está entre (-oo, 0.5]. 
2) A contribuição do cluster i para o j é a soma de todos pertencimentos positivos dos indivíduos de i para o cluster j

Obs.:
* Isso fornecerá números fracionários 
* Caso todos os n usuários de um cluster A estejam exatamente na borda com B, A irá contribuir com n /  2 de usuários para B. (Será que deveríamos dobrar essa métrica para que nesse caso idealizado convirja para n ao invés de n / 2?)

**Comment by caiosba** [comment]
Massa, Fábio! Não, ainda não empurrei para nenhum branch... estou trabalhando num JavaScript + HTML estático primeiro que, dado um JSON da forma que mencionei, desenha os diagramas de Venn como balões do EJ.

**Comment by caiosba** [comment]
Concluí a implementação. Uma versão online e o código estão em https://ca.ios.ba/files/ej/528/. É um diagrama de Venn em que cada grupo é representado visualmente como o balãozinho do EJ. Agora é só uma questão de integrar isso com a aplicação... a visualização é gerada em runtime (JavaScript: D3, Venn.JS e JQuery) a partir de um JSON com a mesma estrutura que citei anteriormente. Em anexo, uma imagem que mostra a renderização.
![528](https://user-images.githubusercontent.com/117518/50048841-86f7a280-00b4-11e9-960b-db54f0ba30e8.png)

**Comment by ricardopoppi** [comment]
Melhorias no svg (cc @caiosba)

- hover do balão no mouse
- onde está o usuário (eu)
- espessura da linha do balão
- pra onde aponta o bico do balão 
- transparência
