### ISSUE TITLE
Comentário rejeitado quando listado no perfil do usuário não exibe o status de "REJEITADO" nem a msg de rejeição

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#536]
Peço a @luizapeixe fazer uma proposta com base nesse wireframe, que é o que foi implementado (conforme print abaixo): https://projects.invisionapp.com/d/main#/console/13863876/300670645/preview - além do status de rejeitado, é importante exibir a mensagem de rejeição.

No exemplo abaixo, o segundo comentário da lista "Muitas coisas são importantes" ele foi rejeitado pelo moderador da conversa, mas isso não é exibido ao usuário, parecendo que é um comentário que foi aceito

![captura de tela de 2018-10-09 16-03-53](https://user-images.githubusercontent.com/1162183/46692252-2d1ebc00-cbdd-11e8-9065-9c93f7681420.png)

**Comment by caiosba** [comment]
Feito conforme screenshot abaixo. PR pronto em https://github.com/ejplatform/ej-server/pull/547.
![536](https://user-images.githubusercontent.com/117518/46807760-2446fb00-cd41-11e8-823f-9bc72e0fa0c9.png)

**Comment by ricardopoppi** [comment]
fechando essa pois pr https://github.com/ejplatform/ej-server/pull/547 foi mergeado. estou abrindo issue #548 pra gente utilizar nos próximos aprimoramentos
