### ISSUE TITLE
Configuração dos votos dos comentários nos estereótipos não estão persistindo

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#537]
Ao configurar os votos nos estereótipos a configuração é aceita mas não persiste. Ao editar um estereótipo já criado, os votos aparecem em branco, tanto no front do EJ quanto no Django admin (testei com uma conversa e estereótipos criados por um usuário admin, pois está quebrando para usuário comum - issue #534)

![captura de tela de 2018-10-09 16-17-26](https://user-images.githubusercontent.com/1162183/46693190-80920980-cbdf-11e8-87b1-94feaebca069.png)
![captura de tela de 2018-10-09 16-17-21](https://user-images.githubusercontent.com/1162183/46693191-80920980-cbdf-11e8-9396-9b3f6028c2e1.png)

**Comment by rodrigocam** [comment]
Aparentemente esse é um bug na biblioteca django-boogie, pois em todos os lugares que usam o campo EnumField que vem dela estão com este problema. Estou investigando o código da biblioteca para ver se descubro algo, pode ajudar @fabiommendes ?

**Comment by ricardopoppi** [comment]
@rodrigocam legal, mto bom!
