### ISSUE TITLE
Verificar porque a tela de login do EJ não está pegando as variáveis na tradução

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#539]
Aparentemente está relacionado com algum problema na variável EJ_REGISTER_TEXT que define o texto "Not part of EJ yet?"

Mas o texto "Forgot your password" também está sem tradução  e no PO essas strings estão traduzidas

**Comment by LeoSilvaGomes** [comment]
Concertei o bug, o Fabio falou que eu poderia da push direto para a develop, então foi o que eu fiz!!

**Comment by LeoSilvaGomes** [comment]
@ricardopoppi da um pull e confere se está tudo ok

**Comment by ricardopoppi** [comment]
com o seu commit @LeoSilvaGomes tudo ficou lindo e resolvido. parabéns!!!!
