### ISSUE TITLE
Tela de edição de board está sem estilo e com os botões quebrados

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#540]
A tela implementada não confere com os wireframes:
EJ genérico: https://invis.io/PAO7XLS2VGS
CPA: https://invis.io/8WO7XLXGCDY

Ver print:

![captura de tela de 2018-10-09 19-07-27](https://user-images.githubusercontent.com/1162183/46701710-05d4e880-cbf7-11e8-80d5-4b7b7ae9dd7c.png)

**Comment by lucashm** [comment]
@ricardopoppi conferir se os assets/statics foram atualizados e o sass foi compilado com o pessoal do pipeline. Aqui no local está normal, e creio que pro pessoal que fez o review também estava!

**Comment by lucashm** [comment]
![image](https://user-images.githubusercontent.com/16053704/46769581-a9d79600-ccc2-11e8-962f-ae1b36a09be8.png)
já identifiquei um probleminha de margem ali! Vou verificar em local assim que possível pra ver se o pipeline quebrou algum css, ou se eu esqueci de commitar alguma mudança!

**Comment by ricardopoppi** [comment]
@lucashm seu empenho e compromisso me inspira demais! mto bom!

O pessoal resolveu o lance da compilação no pipeline. Olha que lindo que ficou em dev! (tem só um detalhezinho de tradução que eu vou verificar nos POs)

![captura de tela de 2018-10-10 21-58-11](https://user-images.githubusercontent.com/1162183/46774287-0db88980-ccd8-11e8-87fd-17ddcb620d0d.png)
![captura de tela de 2018-10-10 21-58-18](https://user-images.githubusercontent.com/1162183/46774290-0db88980-ccd8-11e8-949c-d81cd9b1eb00.png)

**Comment by ricardopoppi** [comment]
como tá funcionando lindo, estou fechando essa issue. se vc detectar alguma necessidade de ajuste, pode abrir nova issue e atribuir para o milestone EJ Barbara Liskov
