### ISSUE TITLE
Tela de edição de esteriótipos não está mostrando botão de editar quando na versão desktop

### ISSUE THREAD

**Issue by fabiolamfleury** [ejplatform/ej-server#543]
@ricardopoppi encontramos esse bug ao testar algumas telas de esteriótipo. O botão de editar esteriótipo não aparace na tela versão desktop, provavelmente por ficar muito a direita na tela

Versão mobile:
![image](https://user-images.githubusercontent.com/20935369/46758578-8e10c780-cca3-11e8-899e-f6c6cd08f22f.png)

Versão desktop:
![image](https://user-images.githubusercontent.com/20935369/46758596-9d901080-cca3-11e8-941f-9bae01cb33d8.png)

**Comment by ricardopoppi** [comment]
@fabiolamfleury mto bom vc ter registrado!
