### ISSUE TITLE
Erro no django quando admin tenta editar conversa

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#545]
Quando usuário admin tenta editar sua conversa, o django retorna esse erro:

TypeError at /conversations/saude-publica/edit/
html() got multiple values for keyword argument 'request'
Request Method:	GET
Request URL:	http://dev.ejplatform.org/conversations/saude-publica/edit/
Django Version:	2.1.2
Exception Type:	TypeError
Exception Value:	
html() got multiple values for keyword argument 'request'
Exception Location:	/pypackages/lib/python3.6/site-packages/hyperpython/jinja2.py in role, line 17
Python Executable:	/usr/bin/python3
Python Version:	3.6.6
Python Path:	
['/app',
 '/usr/local/bin',
 '/app/src',
 '/app',
 '/pypackages/lib/python3.6/site-packages',
 '/usr/lib/python36.zip',
 '/usr/lib/python3.6',
 '/usr/lib/python3.6/lib-dynload',
 '/usr/local/lib/python3.6/dist-packages',
 '/usr/lib/python3/dist-packages',
 'src',
 '/app']
Server time:	Qua, 10 Out 2018 17:08:21 -0300

**Comment by fabiommendes** [comment]
@ricardopoppi , nao consegui reproduzir o erro, mas acho que sei onde estava o problema. Se nao era isso, pegou um outro bug :P

**Comment by ricardopoppi** [comment]
@fabiommendes esse bug está acontecendo em dev, testa lá. Fui replicar e agora até a tela de moderação tá quebrada (olha o erro abaixo).

Loga com admin e acessa o link de moderação de uma das conversas: http://dev.ejplatform.org/conversations/educacao-publica/moderate/

E isso só acontece com o admin, usuário normal tá ok. Reabrindo a isssue.

ERRO:


Request Method: | GET
-- | --
http://dev.ejplatform.org/conversations/educacao-publica/moderate/
2.1.2
TypeError
cannot retrieve CSRF token from empty request.
/pypackages/lib/python3.6/site-packages/hyperpython/django/components.py in csrf_input, line 20
/usr/bin/python3
3.6.6
['/app',  '/usr/local/bin',  '/app/src',  '/app',  '/pypackages/lib/python3.6/site-packages',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages',  'src',  '/app']
Qui, 11 Out 2018 08:44:42 -0300

**Comment by caiosba** [comment]
Eu tô corrigindo isso... porque tá me bloqueando na #536.

**Comment by caiosba** [comment]
Corrigido! Correção disponível neste PR: https://github.com/ejplatform/ej-server/pull/547.

**Comment by ricardopoppi** [comment]
fechando essa pois pr https://github.com/ejplatform/ej-server/pull/547 foi mergeado
