### ISSUE TITLE
URL do mural (board) não pode ser case sensitive

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#551]
Atualmente se no identificador do board é criado com letras maiúsculas, o versão em minusculo não acessa novo board.

Para testar: um board chamado Brasilia com o "B" maiúsculo
http://dev.ejplatform.org/Brasilia

Tentando acessar com o "b" minúsculo a rota quebra: http://dev.ejplatform.org/brasilia

**Comment by rodrigocam** [comment]
Apenas a url principal funcionaria sem case sensitive ou todas as rotas que contém /<slug-do-board>/ ?

**Comment by ricardopoppi** [comment]
O ideal é que fosse sem case sensitive todas as rotas com slug-do-board assim como as rotas com slug-de-conversa. Ex:

/Board/conversations/Nameconv fosse igual a
/board/conversations/nameconv
