### ISSUE TITLE
Adicionar páginas com texto default nas sessões da documentação que ainda não existem

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#556]
Atualmente exibe erro 404

**Comment by caiosba** [comment]
Acessei todas as páginas da documentação e português e inglês e nenhuma está mais apontando para 404. Poppi, se encontrar alguma, avisa aqui por favor.

**Comment by ricardopoppi** [comment]
@caiosba as páginas sobre "nossa inteligencia artificial" e "contribuindo" deram 404 pra mim tanto no local quanto em dev. Acho que uma alternativa é criar um conteúdo de estrutura só pra elas enquanto a gente não tem conteúdo  real.

http://dev.ejplatform.org/docs/?page=user-ai.html
http://dev.ejplatform.org/docs/?page=contributing.html

**Comment by ricardopoppi** [comment]
realmente era só rodar, estão ok em prod  - https://www.ejplatform.org  - então vou fechar a issue
