### ISSUE TITLE
Implementar página desktop do EJ

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#557]
Conforme wireframe: https://projects.invisionapp.com/share/DCO3LIZ5EG8#/screens

Versão mobile pode ser testada em: http://dev.ejplatform.org

**Comment by luizapeixe** [comment]
OK! invision atualizado

**Comment by caiosba** [comment]
Feito, PR em https://github.com/ejplatform/ej-server/pull/629 e vídeo em https://www.youtube.com/watch?v=KRwHRRSmVEc.
