### ISSUE TITLE
Dados dos relatórios não baixam direito no servidor de dev

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#559]
Local está funcionando, mas em dev.ejplatform.org os relatórios das conversas não baixam, em nenhum dos 3 formatos. Aparece um erro 500 - Internal server error

http://dev.ejplatform.org/conversations/saude-publica/reports/votes.csv

![captura de tela de 2018-10-11 20-29-17](https://user-images.githubusercontent.com/1162183/46839492-972d9180-cd94-11e8-889d-33db96c0ce52.png)

**Comment by alexandrebarbaruiva** [comment]
O problema se deve ao fato de as conversas criadas sem serem públicas terem url's seguindo o seguinte padrão {nome_do_mural_que_o_usuário_forneceu}/conversations/{new_conversation}/reports, contudo o Django espera apenas /conversations/{new_conversation}/reports
O @fabiommendes ficou com a issue por conta de se tratar mais do Django e haver a necessidade de acrescentar a URL em múltiplos aplicativos.

**Comment by ricardopoppi** [comment]
fechando essa pois já está funcionando em dev
