### ISSUE TITLE
Formular proposta de whitelabel para boards

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#576]
Considerando a versão atual do mural (board), formular:

- [ ] Proposta de inserir uma logo da organização que virá acompanhada do atual "nome do mural" (no print abaixo o nome é "Temas do Ricardo". A logo deve ser exibida na mesma hierarquia do nome, mantendo a logo do EJ no header e preservando os componentes atuais de "nova conversa", "editar mural" e "visualizando mural". A logo pode ser inserida na mesma tela do "editar mural" (segundo print abaixo)

- [ ] Permitir a escolha de paletas alternativas, que devem afetar o thumbnail da conversa e a interna

![captura de tela de 2018-10-22 17-19-46](https://user-images.githubusercontent.com/1162183/47317301-96f88600-d61f-11e8-9c91-0d9a7038bb8d.png)
![captura de tela de 2018-10-22 17-25-14](https://user-images.githubusercontent.com/1162183/47317306-99f37680-d61f-11e8-8d71-ce34b906b3ec.png)

**Comment by luizapeixe** [comment]
Certo! Algumas duvidinhas:

1. abrimos mão daquela [barra com tags](https://invis.io/JTNB2BBXH2C) para filtrar os resultados a lista de conversas? 
2. paletas alternativas vc diz de cores? Onde o user escolheria essas cores? na tela de lista de conversas? ou na interna da conversa? ou no momento de criação da conversa?

**Comment by ricardopoppi** [comment]
oi @luizapeixe segue respostas:

1. Não abrimos a barra nesse caso pois queremos que os usuários fiquem limitados ao board. Inclusive não poderemos exibir aquele breadcrumb de "conversas públicas" e "minhas conversas" quando o board tiver customizado

2. Isso de cores. As paletas seriam escolhidas na tela de edição do board, assim como a logo tb seria carregada nesse contexto

**Comment by luizapeixe** [comment]
Subi os layouts no board do EJ Genérico (se precisar subir no Dataviz, me digam q reorganizo aqui!)

• Lista de conversas com logo aplicado: https://invis.io/WDORF1EMQBZ 
1. fiquei na dúvida se na situação de ter um logo o título do board some ou se continua aparecendo. Deduzi q ele some
2. Sobre as dimensões do logo, sugiro q a altura máxima seja 60px, e a largura máxima até 285px

• Criar ou Editar Mural: https://invis.io/ZKORF2EWPUM

**Comment by ricardopoppi** [comment]
@luizapeixe essas propostas pode incluir numa sessão "whitelabel" no protótipo do EJ Genérico no invision. 

Sobre a paleta gostei bastante! Qual foi a sua fonte de inspiração? Tentou pensar em cores bem diferentes umas das outras? Discutindo com o @parrahenri e outros pensamos que vale um exercício numa modalidade mais pastel, pra gente poder até escolher algumas de cada modalidade, atendendo assim todos os gostos. Que tal?

Sobre a imagem, creio que não será necessário pedir uma nova imagem na tela de edição do board pois podemos perguntar pro usuário se ele deseja exibir a sua foto de perfil no board, assim já atende a necessidade e simplifica

**Comment by ricardopoppi** [comment]
@luizapeixe lendo seu ultimo comentário e olhando as telas, vi que vc propos uma imagem retangular, estilo capa. Acha melhor isso ou uma imagem quadrada ao lado do nome do board? Temos as duas opções, eu diria, mas não estou seguro por nenhuma delas (cc @parrahenri)

**Comment by luizapeixe** [comment]
sobre a escolha das cores, me baseei no card de conversa atual e analisei o que ali pode ser cambiante e o que deve ser preservado do componente original, tanto pra manter padrão quando pra facilitar a aplicação pros DEVS. Penso que quanto menor a quantidade de elementos variando, melhor! Então cheguei a conclusão de manter fixos o padrão do balõezinhos, o botão de "participe agora" e a cor do texto  da conversa. Todos os demais elementos (podem adotar cores diferentes). Vejam o print pra ficar mais claro:

![captura de tela 2018-10-24 as 15 06 58](https://user-images.githubusercontent.com/6249788/47451676-be299180-d79e-11e8-83b2-9666b0aa827a.png)

então cheguei a conclusão que todas as paletas alternativas devem ter um tom mais escuro (que permita um boa leitura de um texto em branco) e um tom bem clarinho (que também tenha uma boa leitura sob o tom escuro). Daí, dada essa regra, busquei cores bem diferentes entre si pra dar uma diversidade interessante para as alternativas de paletas. Meu receio com tons pastéis é que eles podem dificultar a leitura do texto em branco (nesse seria necessário pensando paletas que modificariam também a cor do texto branco). Vocês podem me indicar que cores pastéis exatamente vocês têm em mente? Posso testar aqui e mostrar pra vcs.

sobre a imagem, acho que não entendi muito bem... Tinha entendido que seria um logo mesmo, tipo de um projeto ou ong ou algo assim. Então, recapitulando, o titulo deve continuar aparecendo mesmo quando o user sobe uma imagem, certo? E qual será exatamente a função da imagem no mural?

**Comment by ricardopoppi** [comment]
@luizapeixe entendi perfeitamente suas decisões e creio que o objetivo é esse mesmo, poder alternar entre paletas alterando apenas os elementos necessários pra isso. Acho que tons pasteis realmente exigiriam uma mudança brusca. Então acho que podemos fechar nessas propostas.

Sobre a imagem, é um logo, institucional ou de projeto. A questão é, quais os prós e cons de uma das duas opções?
1) Logo quadrada, usando a da imagem de perfil, exibida na mesma hierarquia do "nome do board" que continuariam sendo exibido
2) Logo retangular, carregada na edição do board, exibida no lugar do "nome do board" (como vc propôs)

**Comment by luizapeixe** [comment]
o problema de definir a imagem como 1. QUADRADA é que o logos que não forem quadrados ficarão cortados, exibindo apenas uma parte do logo. Pro caso do usuário usar a foto de perfil seria OK, porque a foto já é centralizada e recortada redonda, mas pro caso de utilizar logos não necessariamente quadrados, penso que a melhor solução seria dispor um espaço 2. RETANGULAR, determinando via código apenas a altura máxima e largura máxima para não distorcer nem fragmentar imagens mais institucionais

Alias, se optarmos pela solução QUADRADA, sugeriria usar um padrão redondo invés de quadrado, pra manter o padrão da própria foto de perfil

**Comment by parrahenri** [comment]
@luizapeixe @ricardopoppi pensando aqui que essa coisa da foto vai servir muito do ponto de vista negócio pra atender prefeituras que querem botar sua logo. E acho que a maior parte das logos de prefeitura são retangulares.

**Comment by parrahenri** [comment]
Uma pergunta: não visualizei onde essa imagem vai aparecer. É no lugar do "temas do ricardo"?

**Comment by ricardopoppi** [comment]
@parrahenri, na proposta retangular, a logo apareceria no topo do board, no lugar do título do board, mantendo apenas a descrição, conforme essa imagem do wireframe demonstra:

![captura de tela de 2018-10-25 10-38-56](https://user-images.githubusercontent.com/1162183/47504329-68a6c080-d842-11e8-97d6-295d99f00355.png)

**Comment by luizapeixe** [comment]
minha proposta é que esse formato retangular seja apenas a dimensão máxima das imagens aplicadas ali, seja logo seja foto, ou seja, se o user subir uma foto quadrada, a imagem ficaria assim: 

![captura de tela 2018-10-25 as 11 29 10](https://user-images.githubusercontent.com/6249788/47507821-4f554280-d849-11e8-9cc9-96471f201ebc.png)

ou seja, altura máxima de 60px

**Comment by parrahenri** [comment]
Fechou! gostei!

**Comment by ricardopoppi** [comment]
Fechado então! @luizapeixe pode organizar no protótipo do genérico e linka aqui preu organzar a issue de implementação. Sucesso!

**Comment by luizapeixe** [comment]
Beleza! então os finais são:

• Lista de conversas com logo aplicado: https://invis.io/WDORF1EMQBZ
• Criar ou Editar Mural: https://invis.io/ZKORF2EWPUM

certo?

**Comment by ricardopoppi** [comment]
@luizapeixe isso aí. Só faltou aquela imagem com os thumbs das paletas detalhando cada cor escolhida e onde aplicar, bem como um exemplo de interna tb detalhando cada cor e onde aplicar. Não precisam ser 6 internas, basta uma só detalhando onde aplicar que os desenvolvedores conseguem replicar para as outras

**Comment by luizapeixe** [comment]
Verdade! Acabei de subir as telas faltantes. Para exemplificar os thumbnails das conversas, concentrei todos na página do Mural (se acharem confuso, me avisem!). E subi também uma versão pra cada cor da página de Criar/Editar mural, para não deixar dúvidas a respeito da aplicação das cores. Concentrei essas telas numa nova section "White Label" no invision, como você sugeriu. 

O HEXs das paletas é:
1. Azul (default): tom escuro #30BFD3 // tom claro #C4F2F4
2. Cinza: tom escuro #666666 // tom claro #EEEEEE
3. Rosa: tom escuro #FF3D72 // tom claro #FFE3EA
4. Verde: tom escuro #36C273 // tom claro #B4FDD4
5. Laranja: tom escuro #F5700A // tom claro #FFE1CA
6. Roxo: tom escuro #7758B3 // tom claro #E7DBFF

tela de lista de conversas: https://invis.io/WDORF1EMQBZ
tela de criar/editar mural default: https://invis.io/ZKORF2EWPUM
tela de criar/editar mural CINZA: https://invis.io/MEOSXK1DZVA
tela de criar/editar mural ROSA: https://invis.io/DQOSXKFCWR2
tela de criar/editar mural VERDE: https://invis.io/TJOSXL0G3MV
tela de criar/editar mural LARANJA: https://invis.io/28OSXLBTBUR
tela de criar/editar mural ROXO: https://invis.io/XJOSXLZ46SB

**Comment by luizapeixe** [comment]
ok! seguem as adaptações:

- cinza modo votação: https://invis.io/AVP81OKCZGM
- cinza movo novo comentário:
![captura de tela 2018-11-20 as 19 31 05](https://user-images.githubusercontent.com/6249788/48804167-05059b00-ecfb-11e8-8dc5-c2f3021dbd6b.png)

- rosa modo votação: https://invis.io/26P81QPNW3P
- rosa modo novo comentário: 
![captura de tela 2018-11-20 as 19 33 16](https://user-images.githubusercontent.com/6249788/48804251-4c8c2700-ecfb-11e8-9196-50a439efc4a3.png)

- verde modo votação: https://invis.io/PUP81TAQXWK
- verde modo novo comentário: 
![captura de tela 2018-11-20 as 19 34 33](https://user-images.githubusercontent.com/6249788/48804339-7b0a0200-ecfb-11e8-804b-fb8c64bac925.png)

- laranja modo votação: https://invis.io/GMP81TJBNHZ
- laranja modo novo comentário: 
![captura de tela 2018-11-20 as 19 36 07](https://user-images.githubusercontent.com/6249788/48804427-b6a4cc00-ecfb-11e8-9ba7-9711e5d19953.png)

- roxo modo votação: https://invis.io/H4P81UV8PN7
- roxo modo novo comentário: 
![captura de tela 2018-11-20 as 19 37 26](https://user-images.githubusercontent.com/6249788/48804487-e522a700-ecfb-11e8-8f4f-be47dd09be52.png)
