### ISSUE TITLE
Exibir no campo de comentários o limite de caracteres que o usuário pode digitar

### ISSUE THREAD

**Issue by fabiolamfleury** [ejplatform/ej-server#585]
Pablo sugeriu criar essa issue, não sei se já existe algo parecido.

Aparecer um contador enquanto o usuário digita, como na imagem abaixo

![image](https://user-images.githubusercontent.com/20935369/47446074-c4b10c80-d790-11e8-83ee-ee689a7a314b.png)

**Comment by ricardopoppi** [comment]
ótima ideia, vimos que isso era necessário mesmo

@Heloisecs pode derivar um dos wireframes do novo campo de comentário da barbara liskov e propor como podemos inserir esse contador?

**Comment by Heloisecs** [comment]
https://invis.io/GHN0FY1QFCK#/324346893_Conversa_-_Criar_Comenta-rio

**Comment by ricardopoppi** [comment]
@fabiolamfleury como vc vai mexer nessa tela pro fade do comentário, estou assignando essa pra vc tratar na mesma toada, ok?

**Comment by fabiolamfleury** [comment]
Ok!
