### ISSUE TITLE
Criar método de debug que grava erros em log mesmo com o debug desligado

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#593]
Qdo o debug está oculto, o ideal seria que o EJ gravasse erros num log

![photo_2018-10-29_21-15-51](https://user-images.githubusercontent.com/1162183/47687625-e3b00400-dbbf-11e8-96c2-22ad9874578c.jpg)

**Comment by pablodiegoss** [comment]
https://stackoverflow.com/q/238081
A criação de um middleware que capture os erros e salve em um arquivo parece uma solução ótima
