### ISSUE TITLE
Implementação da animação do form de comentário na página de detalhe da conversa

### ISSUE THREAD

**Issue by fabiolamfleury** [ejplatform/ej-server#596]
Essa issue é uma parte menor da issue #521 

Implementar a animação que desloca o form de comentário pro local do comentário a ser votado pra deixar claro ao usuário que ele está inserindo um novo comentário na conversa e não simplesmente uma resposta ao comentário anterior. A animação será um FADE:  https://user-images.githubusercontent.com/9471715/47521477-7de31580-d869-11e8-9de1-3076f0285c8b.gif

**Comment by fabiolamfleury** [comment]
@ricardopoppi essa animação também precisa ser adaptada para a versão do cpa?

**Comment by ricardopoppi** [comment]
@fabiolamfleury idealmente sim pois quando a gente rodar a build com o tema do CPA ele vai pegar da mesma base de código, confere?
