### ISSUE TITLE
Criar uma forma de promover eventos

### ISSUE THREAD

**Issue by pablodiegoss** [ejplatform/ej-server#598]
Nós temos na página principal da aplicação mas não há nenhuma indicação do que estão relacionadas as conversas promoted. Seria legal alguma forma de informar ao usuário, por exemplo, que está rolando na plataforma a semana da inovação e por isso, temos aquelas conversas promovidas na página principal.

@ricardopoppi
@Heloisecs 

Acho que vocês podem dar ideias, algum campo de texto, imagem, banner, para indicar estes eventos pontuais que podem acontecer na plataforma, o que acham?

**Comment by ricardopoppi** [comment]
@luizapeixe pode conceber isso? entraria como proposta na home de conversas do EJ, mas também na home institucional

**Comment by luizapeixe** [comment]
OK! Que tal essa proposta de destaque para os cards Promoted na lista de conversas? https://invis.io/CYOZXWZUQV5

Acham válido sinalizar o Promotedness na interna da conversa também? Se sim, já vai uma sugestão:
![captura de tela 2018-11-07 as 15 36 47](https://user-images.githubusercontent.com/6249788/48149402-1c786900-e2a3-11e8-89e1-272125a0be2b.png)

E sobre o banner de divulgação do evento na home comercial, posso fazer também! que informações exatamente vamos apresentar no banner?

**Comment by ricardopoppi** [comment]
@luizapeixe ficou legal a proposta, vamos deixar no backlog de desenvolvimento por enquanto pra priorizar mais perto do final. Sobre os banners na home, não faremos exatamente pra semana de inovação mas para umas necessidades de negócio do próprio EJ, estou construindo esse briefing com o @parrahenri e já te passamos
