### ISSUE TITLE
Gerar QRcode do evento da semana da ENAP

### ISSUE THREAD

**Issue by BrunaNayara** [ejplatform/ej-server#599]
Criar o QRcode do link [Semana ENAP](https://www.ejplatform.org/semanaenap/)

**Comment by BrunaNayara** [comment]
![qrcodeejenap](https://user-images.githubusercontent.com/4125846/47738509-07238f00-dc52-11e8-84be-e9b89dcab4b9.png)

**Comment by pablodiegoss** [comment]
Testado, funcionou!

**Comment by ricardopoppi** [comment]
vamos ter que regerar com o domínio de divulgação: http://www.ejparticipe.org/semanaenap

**Comment by BrunaNayara** [comment]
![frame](https://user-images.githubusercontent.com/4125846/48774306-f98d8200-ecb0-11e8-9f6d-cc1700e9c08c.png)

**Comment by ricardopoppi** [comment]
gerando com o novo link de divulgação: https://ejparticipe.org/semanadeinovacao

![frame](https://user-images.githubusercontent.com/1162183/48914011-53cd4500-ee61-11e8-842d-7a016fc2ee06.png)

**Comment by ricardopoppi** [comment]
fechando pois já foi realizado
