### ISSUE TITLE
Rotas www

### ISSUE THREAD

**Issue by BrunaNayara** [ejplatform/ej-server#600]
Atualmente, ao acessar [ejplatform.org](ejplatform.org) dá erro 404. É preciso colocar 'www' para conseguir acessar. 
Precisamos deixar acessível independente do uso de 'www'

**Comment by davidCarlos** [comment]
Fechando essa issue, uma vez que ao digitar ejplatform.org, o usuário é redirecionado para https://www.ejplatform.org/home/.
