### ISSUE TITLE
Trocar "Comentário" por "Respostas"

### ISSUE THREAD

**Issue by pablodiegoss** [ejplatform/ej-server#601]
O termo comentário tem levado os usuários a pensar em threads de conversa, além da nova forma de comentário utilizando fades na #596, a troca da palavra Comentário pode ajudar o usuário a criar respostas para a Pergunta-Mote, não para as outras respostas.

@ricardopoppi, alguma sugestão quanto ao termo Resposta?

**Comment by ricardopoppi** [comment]
A gente conseguindo implementar a issue #596 talvez não seja necessário o ajuste. Se não, a proposta de ajuste seria:

"Vote nas respostas" antes dos comentários pra votar
e "Acrescente mais respostas" antes do form de novo comentário

**Comment by ricardopoppi** [comment]
Por conta da novo ajuste do fading de comentários não faremos mais essa mudança
