### ISSUE TITLE
Revisar conteúdos

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#602]
- [ ] Sobre

- [ ] Perguntas frequentes

- [ ] Termos de uso

**Comment by parrahenri** [comment]
§ 1º O tratamento de dados pessoais de crianças deverá ser realizado com o consentimento específico e em destaque dado por pelo menos um dos pais ou pelo responsável legal. 

“Há de se observar, inclusive, a indicação do tempo pelo qual essas informações capitadas dos usuários pela Plataforma serão mantidas em poder do responsável pela segurança/armazenamento dos dados e de se resguardar a total privacidade dos utilizadores da Plataforma, nos termos especificados na Lei 13.709:

1. qual o tempo que indico?
2. questão do consentimento de maior fica em aberto ainda

**Comment by parrahenri** [comment]
@ricardopoppi retomando essa pra fechar.

Já tínhamos esse item:

7.1. Cabe à equipe de manutenção da PLATAFORMA estabelecer, a seu exclusivo critério, o período pelo qual as opiniões e outros conteúdos disponibilizados por USUÁRIOS ficarão publicados na PLATAFORMA e o período pelo qual serão armazenados. 

Acha que devo acrescentar um "À princípio todos os dados de participação e opinião ficarão armazenados permanentemente." ao final?

**Comment by ricardopoppi** [comment]
acho uma boa sim

**Comment by parrahenri** [comment]
[TERMOS_DE_USO_PlataformaCPA.docx](https://github.com/ejplatform/ej-server/files/2610857/TERMOS_DE_USO_PlataformaCPA.docx)

Termos de uso

**Comment by parrahenri** [comment]
SOBRE NÓS

A plataforma digital é uma iniciativa conjunta do CONANDA e do governo federal para ampliar a participação na defesa de direitos das crianças e adolescentes. Nela é possível propor e votar em ideias em conversas criadas pelo CPA, bem como se engajar em grupos de debate sobre temas específicos, que servirão para ampliar o contato entre participantes e construir ações coletivas.

CONANDA
Formado por 14 representantes do Governo Federal e por 14 representantes de entidades não-governamentais o Conselho Nacional dos Direitos da Criança e do Adolescente é deliberativo, fiscaliza as ações do governo, define diretrizes para a política nacional e faz a gestão do Fundo Nacional da Criança e do Adolescente (FNCA).

CPA
O Comitê de Participação de Adolescentes (CPA) é formado por quarenta e sete adolescentes escolhidos pelos Conselhos Estaduais dos Direitos da Criança e do Adolescente, por grupos sociais diversos e por meio da plataforma digital. Seu objetivo é acompanhar e participar dos trabalhos do Conanda, além de mobilizar e estimular a participação de crianças e adolescentes através da plataforma digital.




PERGUNTAS FREQUENTES

Como funciona?

Funciona assim: basta se cadastrar na plataforma (pelo login do Facebook, Twitter ou cadastro simples na própria plataforma) e participar das CONVERSAS e/ou dos GRUPOS DE DEBATE que debaterão diferentes assuntos. 

Participar é bem simples: seja pelo celular ou pelo computador, você pode incluir suas ideias e concordar ou discordar de opiniões que forem aparecendo num simples clique dentro das CONVERSAS. Nos grupos, poderá fazer comentários, mencionar e responder a outros participantes em uma comunicação direta entre os membros.


Quem pode participar?

Qualquer pessoa pode participar livremente, mas o foco está no engajamento de crianças e adolescentes.

E o que acontece depois?

Todo o material produzido a partir das conversas vai ser discutido pelo CPA, que irá propor debates ao CONANDA. Da mesma forma, o CPA vai propor a criação dos grupos de debate, sendo responsável pela facilitação e pela resposta aos participantes.

Quais sugestões feitas nas conversas serão respondidas diretamente?

Todas as opiniões inseridas nas CONVERSAS serão consideradas.

Além disso, todas as sugestões que receberem opinião (sim/não) de pelo menos 40% dos participantes da conversa receberão resposta diretamente pelo CPA, que também irá analisar todas as sugestões e produzir um balanço geral com as propostas.

O CPA também quer ouvir as minorias. Por isso vai responder os comentários consensuais dos grupos de opinião, por menores que sejam. Qualquer comentário que tiver mais de 60% de apoios ou rejeições na opinião dos participantes do grupo no último dia de cada conversa também será respondido.

Existe algum tipo de moderação?

Comentários de ódio e que atacarem os direitos humanos feitos nas CONVERSAS serão rejeitados e ficarão disponíveis para consulta pública como forma de garantir a transparência e a autenticidade desta moderação. Da mesma forma, os facilitadores dos GRUPOS DE DEBATE poderão pedir a exclusão de comentários com esse teor e mesmo excluir participantes que insistirem nesse tipo de postura.

Que dados pessoais eu preciso fornecer? O que será feito com eles?

O usuário se cadastra apenas com o seu nome e email. Quando o login for feito por mídias sociais (Facebook ou Twitter) nós vamos registrar apenas o nome, email e foto de perfil. Esses dados são fornecidos mediante autorização do próprio usuário, tanto no momento do registro quanto do login, e serão utilizados para sua própria interação na plataforma, com o nome e foto de perfil ficando visíveis na visualização dos grupos de opinião e na autoria dos seus comentários.

A plataforma só utilizará os dados de nome e foto de perfil em relatórios agregados para fins de pesquisa e sistematização, incluindo a emissão de relatórios estatísticos referentes a próprio uso da plataforma. Os e-mails só serão utilizados para fins de comunicação com o usuário, seja sobre eventos voltados ao aprimoramento da participação, seja com informações pertinentes aos grupos de opinião de que ele participa, sempre resguardado o direito de se retirar a qualquer momento.

Nunca forneceremos esses dados para terceiros. Nos comprometemos a apenas usar, armazenar e tratar dados pessoais vinculados à estrita finalidade a que se destina a plataforma.

Este software é livre?

Todos os softwares em que estão baseados a plataforma digital são livres. Livres no sentido de que qualquer pessoa pode utilizar, estudar, modificar e compartilhar com qualquer um.

**Comment by parrahenri** [comment]
Salve, @ricardopoppi! Termos de Uso e FAQ da EJ:
https://docs.google.com/document/d/1ZntrVq1MZNhXgI8bvH6J18cJh6hT3R3wGxLHLNPie58/edit
