### ISSUE TITLE
Resolver os bugs da clusterização

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#603]
O EJ não está fazendo clusterização automática e o endpoint /clusterize está quebrado. Django solta o seguinte erro:

FieldError at /conversations/saude-publica/clusterize/
Cannot resolve keyword 'username' into field. Choices are: auth_token, boards, clusters, commentqueue, comments, conversations, date_joined, display_name, email, emailaddress, favorite_conversations, groups, id, is_active, is_staff, is_superuser, last_login, logentry, name, password, passwordresettoken, raw_profile, socialaccount, stereotype, user_permissions, votes
Request Method:  GET
Request URL:  http://dev.ejplatform.org/conversations/saude-publica/clusterize/
Django Version:  2.1.2
Exception Type:  FieldError
Exception Value:  
Cannot resolve keyword 'username' into field. Choices are: auth_token, boards, clusters, commentqueue, comments, conversations, date_joined, display_name, email, emailaddress, favorite_conversations, groups, id, is_active, is_staff, is_superuser, last_login, logentry, name, password, passwordresettoken, raw_profile, socialaccount, stereotype, user_permissions, votes
Exception Location:  /pypackages/lib/python3.6/site-packages/django/db/models/sql/query.py in names_to_path, line 1389
Python Executable:  /usr/bin/python3
Python Version:  3.6.6
Python Path:  
['/app',
 '/usr/local/bin',
 '/app/src',
 '/app',
 '/pypackages/lib/python3.6/site-packages',
 '/usr/lib/python36.zip',
 '/usr/lib/python3.6',
 '/usr/lib/python3.6/lib-dynload',
 '/usr/local/lib/python3.6/dist-packages',
 '/usr/lib/python3/dist-packages',
 'src',
 '/app']
Server time:  Ter, 30 Out 2018 10:53:05 -0300

**Comment by fabiolamfleury** [comment]
@ricardopoppi acredito que esse bug foi resolvido no pr #575 . Uma função do math.py de clusters ainda acessava o campo username que não existe mais, e foi substituido pelo email do usuário!
