### ISSUE TITLE
Quando usuário comenta os indicadores de comentários em moderação e restantes não atualizam

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#611]
Para replicar:

1) Tente incluir um novo comentário
2) A página recarrega e os indicadores de comentários em moderação e faltantes abaixo não mudam (ver print)

@rodrigocam pode ser que tenha relação (ou tenha sido resolvido) pela issue #589 pode avaliar

![captura de tela de 2018-11-01 19-55-38](https://user-images.githubusercontent.com/1162183/47884650-56afb980-de10-11e8-92f1-1cd3683794e0.png)
![captura de tela de 2018-11-01 19-55-47](https://user-images.githubusercontent.com/1162183/47884651-57485000-de10-11e8-8eca-c5f898c96a51.png)

**Comment by rodrigocam** [comment]
Testei aqui e o PR #610 irá resolver este bug!

**Comment by ricardopoppi** [comment]
@rodrigocam muito bom!
