### ISSUE TITLE
Ativar certificado nos dominios do ejparticipe

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#613]
Estão sem certificado:
ejparticipe.org
www.ejparticipe.org

O redirect para www não está funcionando quando a url é acessada com algum slug. Ex:
ejplatform.org/semanaenap

**Comment by davidCarlos** [comment]
O ejparticipe.org sempre vai redirecionar para o www.ejparticipe.org, então não há necessidade de gerar certifocado para ele. Tanto o certificado do www.ejparticipe.org quanto o redirect da subrota está ok agora.
