### ISSUE TITLE
Contador de comentários nos cards de votação estão considerando comentarios REJEITADOS

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#620]
Atualmente, se a conversa tem comentários rejeitados, eles estão sendo somados no contador (ver print).

No caso eu testei com comentários que tinham sido inicialmente aceitos na conversa. Verificar se os comentários em moderação também não estão  influenciando nessa contagem. O correto é que a contagem seja feita APENAS com os comentários cujo status é "aprovado".

![captura de tela de 2018-11-06 15-15-57](https://user-images.githubusercontent.com/1162183/48081504-58de9300-e1d7-11e8-9219-df01da265545.png)

**Comment by fabiolamfleury** [comment]
Pelo código, a filtragem para contar está sendo feita apenas de comentários aprovados, tentei reproduzir localmente esse problema porém não consegui

**Comment by ricardopoppi** [comment]
hummm então acho que sei o que pode ser. porque na minha reprodução, os comentários eram da criadora da conversa, então entram já como aprovados. O que eu fiz foi rejeitar alguns desses comentários. Mas a contagem continuou considerando eles.

Vc pode tentar replicar fazendo o mesmo. Inserindo uns comentários como criadora de uma conversa. Depois indo no "moderate" e rejeitando eles com qq motivo. Aí inserindo alguns novos e ver se a contagem fica errada.

**Comment by fabiolamfleury** [comment]
Consegui reproduzir agora! Só aconteceu no caso do comentário já ter sido votado e depois disso ser rejeitado, vou investigar :)
