### ISSUE TITLE
Usuário sem permissão consegue criar conversa no board público pelo link /add

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#621]
Usuário comum, usando a url /conversations/add/ está conseguindo criar conversa no board público

**Comment by fabiolamfleury** [comment]
Acredito que o problema esteja em como o django boogie avalia as permissões das rotas (argumento perms). A permissão retorna de forma correta True ou False para quem pode adicionar conversar ou não no board público, mas de qualquer forma a rota aparece. 

Criei como teste uma rota que nenhum usuário teria permissão e mesmo assim consegui acessá-la. 
Peço ajuda do @fabiommendes para resolver essa issue

**Comment by rodrigocam** [comment]
Criei uma issue no repositório da biblioteca django-boogie e enquanto isso fiz um workaround para funcionar. Resolvido com o commit 038adbffbf9c783051dd552362195d322d5d1499

**Comment by ricardopoppi** [comment]
@fabiolamfleury @rodrigocam mandaram muito bem!
