### ISSUE TITLE
Propor solução para o usuário poder voltar para o board da conversa

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#622]
Atualmente quando o usuário acessa um board (exemplo: https://www.ejplatform.org/semanaenap) e entra na conversa, ele não tem como voltar ao board original. Atualmente isso só é possível clicando no botão de voltar. Como a logo do EJ leva para o board público (que é o correto), o usuário que entra por um board e acessa a conversa não tem como acessar o board novamente de forma visível.

A sugestão mais óbvia seria um "breadcrumb" que sempre indicasse o board no qual a conversa faz parte. Mas se houver outras soluções, tb são bem vindas.

@Heloisecs pode formular isso?

PROPOSTA DA @Heloisecs: O botão voltar dentro da conversa SEMPRE levar para o board da conversa, mesmo no caso de uma conversa no board público.

**Comment by Heloisecs** [comment]
@ricardopoppi o nosso botão de voltar não é o mesmo do android de voltar, certo? Eu sugeriria que mesmo que a pessoa entrasse direto na conversa, se necessariamente o caminho é o mesmo (vide breadcrumb), o botão de voltar deveria apontar para o board da conversa. Há algum impeditivo para isso?

Exemplo: Quando eu entro em uma seção específica do Instagram, o botão de voltar leva à seção anterior, mesmo que eu não tenha entrado na seção anterior.

**Comment by ricardopoppi** [comment]
eu achei uma ótima solução. não polui mais a conversa e já temos uma referencia bem importante desse tipo de interação que é o instagram. vamos por esse caminho, vou assignar a issue pra @fabiolamfleury
