### ISSUE TITLE
Verificar porque os conteúdos especificos do tema cpa não estão aplicados na instancia

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#628]
Os assets quando a build está carregada com o tema cpa devem vir da pasta do tema: lib/themes/cpa

Analisando nossa instancia cpa.dev: http://35.199.117.172

- [ ] A logo não é a da plataforma cpa (está a logo do ej genérico)

- [ ] Na home deslogada do cpa "/start", antes do componente de conversas vinha o texto: "Aqui é um espaço par aos adolescentes debaterem ações que promovam, garantam e defendam os seus direitos"

- [ ] A imagem default do "/profile" tb deve vir dos assets específicos do tema (img de referencia, ignorar a navbar dessa img pois está desatualizada): https://projects.invisionapp.com/share/QBNEGBW8SA2#/screens

- [ ] Os ícones da navbar tb deveriam ser específicos do tema

Imagens de referencia para HOME e NAVBAR:

Home deslogada (ignorar o rodapé que tiramos na implementação): https://projects.invisionapp.com/share/2KNHRQQRF5X#/screens

Home logada (ignorar o rodapé e o ícone de alertas já que não temos essa funcionalidade ainda. Observar tb que o ícone "Painel CPA" só aparecem para os usuários do grupo CPA): https://projects.invisionapp.com/share/ZTNJDBZEQCA#/screens

**Comment by ricardopoppi** [comment]
@pablodiegoss pode ajudar o @leandronunes nessa issue, principalmente orientando como ele faz pra ativar/ajustar os assets do tema CPA?

**Comment by pablodiegoss** [comment]
O Deploy de versões CPA foram feitas somente via Rancher, então o docker-compose que sobe uma versão específica do CPA está no nosso repositório do catalogo Rancher:

https://github.com/ejplatform/ej-rancher-catalog/blob/master/templates/cpa/0/docker-compose.yml

O docker-compose de deploy atual no repositório ej-server sobe apenas uma versão genérica.
Teria que checar como foi feito este deploy de dev CPA, se alteraram o arquivo de deploy com todos os parametros certos, nome da imagem e afins.
