### ISSUE TITLE
Implementar o front e estilos do white label para boards

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#646]
- [x] Incluir a opção de subir imagem que substitui o título do board

- [x] Implementar a opção de escolha de paletas de cores específicas para board

- [x] Repercutir a paleta:

  - [x] No thumbnail que aparece na página do board

  - [x] Na interna da conversa

  - [x] No menu hamburguer

Refs:

**Telas invision**
• Lista de conversas com logo aplicado: https://invis.io/WDORF1EMQBZ
• Criar ou Editar Mural: https://invis.io/ZKORF2EWPUM

Internas:
- Cinza modo votação: https://invis.io/AVP81OKCZGM
- Cinza movo novo comentário:
![captura de tela 2018-11-20 as 19 31 05](https://user-images.githubusercontent.com/6249788/48804167-05059b00-ecfb-11e8-8dc5-c2f3021dbd6b.png)

**Thumbnails:**

![captura de tela 2018-10-24 as 13 25 21](https://user-images.githubusercontent.com/6249788/47445899-6126df00-d790-11e8-95e4-2011c96d4d2d.png)

**Explicação da designer:**

Sobre a escolha das cores, me baseei no card de conversa atual e analisei o que ali pode ser cambiante e o que deve ser preservado do componente original, tanto pra manter padrão quando pra facilitar a aplicação pros DEVS. Penso que quanto menor a quantidade de elementos variando, melhor! Então cheguei a conclusão de manter fixos o padrão do balõezinhos, o botão de "participe agora" e a cor do texto  da conversa. Todos os demais elementos (podem adotar cores diferentes). Vejam o print pra ficar mais claro:

![captura de tela 2018-10-24 as 15 06 58](https://user-images.githubusercontent.com/6249788/47451676-be299180-d79e-11e8-83b2-9666b0aa827a.png)

então cheguei a conclusão que todas as paletas alternativas devem ter um tom mais escuro (que permita um boa leitura de um texto em branco) e um tom bem clarinho (que também tenha uma boa leitura sob o tom escuro). Daí, dada essa regra, busquei cores bem diferentes entre si pra dar uma diversidade interessante para as alternativas de paletas. Meu receio com tons pastéis é que eles podem dificultar a leitura do texto em branco (nesse seria necessário pensando paletas que modificariam também a cor do texto branco).

O HEXs das paletas é:

Azul (default): tom escuro #30BFD3 // tom claro #C4F2F4
Cinza: tom escuro #666666 // tom claro #EEEEEE
Rosa: tom escuro #FF3D72 // tom claro #FFE3EA
Verde: tom escuro #36C273 // tom claro #B4FDD4
Laranja: tom escuro #F5700A // tom claro #FFE1CA
Roxo: tom escuro #7758B3 // tom claro #E7DBFF

**Comment by valessiobrito** [comment]
@Heloisecs o nome dessas cores aqui.. segue a da documentação?

![captura de tela de 2018-11-27 17-16-42](https://user-images.githubusercontent.com/310049/49105652-55837800-f268-11e8-834d-146c73714082.png)
