### ISSUE TITLE
Tags ultrapassando limite do card

### ISSUE THREAD

**Issue by guilacerda** [ejplatform/ej-server#660]
Quando o moderador coloca várias _tags_ em uma conversa, elas ultrapassam o limite do _card_: 

![image](https://user-images.githubusercontent.com/26297247/49085189-95cb0200-f238-11e8-916e-cffbdf94fc8c.png)

Só que não existe a possibilidade de alterar as tags que já foram colocadas na criação da conversa, mesmo sendo o moderador da conversa.

**Comment by guilacerda** [comment]
Outro detalhe encontrado é que quando clica em "Participar Agora!" da conversa, mostra apenas 3 tags:

![image](https://user-images.githubusercontent.com/26297247/49087501-52739200-f23e-11e8-8161-4809d0e6305f.png)

E quando o moderador clica em "moderar conversa" aparece somente 1 tag:

![image](https://user-images.githubusercontent.com/26297247/49087584-80f16d00-f23e-11e8-81e5-0d037e21adda.png)

**Comment by fabiolamfleury** [comment]
@ricardopoppi estou trabalhando nessa issue, o usuário pode editar as tags da conversa? Lembro de em algum momento ser discutido que não, mas não tenho certeza

**Comment by ricardopoppi** [comment]
@fabiolamfleury é bom incluir a possibilidade de edição das tags sim, tivemos até demanda disso nos pilotos. O que fica sem possibilidade de editar é o slug (identificador). Esse sim, definiu uma vez, fica pra sempre, já que afeta a url da conversa.

Mas tags, sim, podemos permitir a edição, sem problemas e é uma boa feature, pode incluir nessa issue

**Comment by fabiolamfleury** [comment]
Beleza! Outra observação de como está sendo feita a implementação:

Esse card agora apresentará apenas uma tag da conversa, enquanto nas outras telas, serão exibidas todas as tags!

![imagem](https://user-images.githubusercontent.com/20935369/49153345-9dec7580-f2fc-11e8-97b6-9eb1d8a29929.png)

**Comment by ricardopoppi** [comment]
@fabiolamfleury ótimo!
