### ISSUE TITLE
Ao editar a conversa dá erro de encoding

### ISSUE THREAD

**Issue by BrunaNayara** [ejplatform/ej-server#661]
@davidCarlos pode descrever melhor? Colocar o log?

**Comment by guilacerda** [comment]
Após alterar o conteúdo da conversa e clicar em salvar, salva, mas é redirecionado para uma página de erro.

![image](https://user-images.githubusercontent.com/26297247/49087207-869a8300-f23d-11e8-994d-f98166731fa1.png)
