### ISSUE TITLE
Lightbox que aparece na interna de uma conversa não some

### ISSUE THREAD

**Issue by davidCarlos** [ejplatform/ej-server#663]
Mesmo após interagir com a Lightbox se eu volto pra mesma conversa ela continua aparecendo.

**Comment by LeoSilvaGomes** [comment]
O Lightbox apenas irá desaparecer quando a pessoa fazer uma votação em qualquer conversa, pois entendesse  que se ela não votou então ela não entendeu o que o Lightbox quer passar (isso irá variar de Lightbox para Lightbox), já que as modais servem para dar uma explicação do que está acontecendo.
@davidCarlos

**Comment by LeoSilvaGomes** [comment]
Resolvida a partir de outra issue
