### ISSUE TITLE
Implementar o menu de contexto

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#666]
O menu de contexto aparece nas principais telas:

Especificações do menu: https://projects.invisionapp.com/d/main#/console/14872865/332360301/preview

No board: https://projects.invisionapp.com/d/main#/console/14872865/332201238/preview
Na interna de conversa: https://projects.invisionapp.com/d/main#/console/14872865/332201236/preview
No perfil: https://projects.invisionapp.com/d/main#/console/14872865/332201239/preview

**Comment by fabiommendes** [comment]
Essa issue est'a com alguem?

**Comment by ricardopoppi** [comment]
@brunanayara tá com a missão de achar uma dona/dono

**Comment by fabiommendes** [comment]
Eu fiz um esqueleto de como podemos fazer a estrutura do ponto de vista do back. Falta aplicar estilos, js, etc. Tah na branch com o nome da issue
