### ISSUE TITLE
Rotas de participação e moderação das conversas não estão incluindo o slug do mural

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#683]
Após criar uma conversa com um usuário comum, tanto o acesso à moderação (rota /moderate) quanto o acesso à participação na conversa não estão incluindo o slug do mural.

Rotas que não estão usando o slug do mural:

- [x] /\<slug-da-conversa\>

- [x] /\<slug-da-conversa\>/moderate

- [x] /\<slug-da-conversa\>/edit

Rota que funciona tanto sem slug de mural quanto com slug de mural (estranho pode ser algum bug):

- [x] /\<slug-da-conversa\>/stereotypes

Para replicar:

1) Crie um mural e uma conversa com usuário comum
2) Acesse o mural e tente clicar no "participar agora" ou no "moderar conversa"
3) Observe que ambas as rotas não estão incluindo o /\<slug-do-mural\>/
4) Na tela de moderação, incluindo o \<slug-do-mural\> manualmente, o botão de "editar conversa" também está com essa falha

**Comment by fabiolamfleury** [comment]
Esses problemas surgirão na refatoração para utilizar url reverse das conversas, como a relação da conversa com boards sai um pouco do padrão, o erro acontece, não consegui entender muito bem a implementação que gera as urls, então vou tentar conversar com o professor Fábio.

**Comment by fabiolamfleury** [comment]
O pr https://github.com/ejplatform/ej-server/pull/689 resolve esses problemas e alguns outros com essa nova implementação de url que eu acabei esbarrando :) já está em revisão
