### ISSUE TITLE
Tela de criação de conversas

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#69]
Eu como um criador da conversa, quero cadastrar e modificar parametros da conversa em uma interface simples

Eu como usuário quero acessar as conversas de um único usuário atraves de um permalink

**Comment by luizapeixe** [comment]
A respeito dos wireframes que já temos criados (ainda não aprovados, apresentarei-os hj às 15h) relativos a essa questão, temos a tela de **Lista de Conversas**, que pro user padrão tem [essa visualização](https://projects.invisionapp.com/d/#/console/13881288/298420187/preview) e pro user CPA tem [essa visualização](https://projects.invisionapp.com/d/#/console/13881288/298420186/preview) (igual porém com recurso de adicionar nova conversa, uma vez o usar padrão não pode criar conversas, apenas comentar em conversas já existentes)

Daí, na página de perfil do usuário, ele poderá ter uma lista de todos os comentários que ele já fez em diferentes conversas, [veja aqui](https://projects.invisionapp.com/d/#/console/13881288/298420479/preview). E algo que não comentamos mas que eu gostaria de sugerir é que o usuário possa favoritar algumas conversas e essas favoritas também estariam listadas no seu perfil, [assim](https://projects.invisionapp.com/d/#/console/13881288/298420478/preview). Dessa maneira o user pode favoritar e acompanhar conversas específicas sem a necessidade de ele ter criado, comentado ou se quer votado na conversa.

Podemos debater esses assuntos em tempo real hj na call :)

**Comment by ricardopoppi** [comment]
Após a call, decidimos que além da home, o usuário terá uma home própria, com um link permanente, que agregará todas as conversas criadas por ele (os thumbnails). Para exibir essa tela, será usado o mesmo [wireframe da tela de listagem de conversas](https://projects.invisionapp.com/d/main#/console/13881288/298971644/preview), com a diferença que só vão ser exibidas as conversas criadas pelo usuário.

**Comment by ricardopoppi** [comment]
Sobre como formatar esse "permalink" público onde estão todas as conversas criadas pelo usuário, o @fabiommendes sugeriu na call que fosse gerado um link numérico estilo http://ejplatform.org/conversations/1 ou algo do tipo

**Comment by ricardopoppi** [comment]
Logo após a reunião de comunicação, fizemos eu, @fabiommendes e @parrahenri uma conversa sobre qual a melhor arquitetura de permalinks do EJ. Chegamos a seguinte conclusão:
1) usuário vai poder escolher o username que ocupará um namespace único no EJ. O link público do perfil do usuário será então ejplatform.org/<username>
2) A conversa dos usuários terá regra de slug usando um namespace livre dentro do contexto de cada usuário. Cada usuário poderá dar o título que quiser para as conversas e o slug será gerado a partir daí. Exemplo, se eu criar uma conversa sobre saúde o permalink dela será: ejplatform.org/poppi/saude
3) Os conteúdos dinâmicos (páginas fixas) e outras funções do ej deverão ser organizados dentro de um  namespace próprio. Exemplo: ejplatform.org/content/faq ou ejplatforma/profile/poppi e assim por diante.

cc @luanguimaraesla @rodrigocam @pablodiegoss

**Comment by luizapeixe** [comment]
pessoal, subi agora pouco uma primeira proposta de tela de [edição da conversa](https://invis.io/V9GNMI1BG2F#/301693278_Conversa_EDIT). Acredito que a tela de criação possa ser bastante parecida, porém com o campo de título da conversa em branco ou com algo a ser substituído, como "escreva o título da conversa aqui" e, obviamente, sem a lista de comentários, que ainda não existirão no caso da criação de uma nova conversa
