### ISSUE TITLE
Botão de upload da foto não esta funcionando corretamente

### ISSUE THREAD

**Issue by wparaujo** [ejplatform/ej-server#694]
## Descrição
Quando se clica no botão para atualizar a foto de perfil, não acontece nada. Por outro lado ao clicar na label acima do botão, a janela de seleção de arquivo aparece.

### Passos para reproduzir o bug
1 - Rode localmente o servidor
2 - Cadastra-se e vá na tela de perfil
3 - Tente clicar no botão **chose a file**

### Gif demonstrativo do bug

<img src='https://media.giphy.com/media/ycMsgeQFLsoNqTAZIw/giphy.gif' width=500>

**Comment by rodrigocam** [comment]
Duplicata com #662 e #684, correção em andamento no PR #668. Obrigado pelo report @wparaujo !
