### ISSUE TITLE
Erro na edição de data de nascimento. 

### ISSUE THREAD

**Issue by Lcunha** [ejplatform/ej-server#699]
## Descrição
Quando se salva os dados ao editar perfil não salva a data de nascimento preenchida.

## Passos para reproduzir o bug
1. Acessar [EJ](https://www.ejplatform.org/home/).
2. Efetuar Login.
3. Acessar [perfil](https://www.ejplatform.org/profile/).
4. Clicar em [Editar Perfil](https://www.ejplatform.org/profile/edit/).
5. Preencher os dados.
6. Clicar em Salvar.
7. Clicar em [Editar Perfil](https://www.ejplatform.org/profile/edit/).
8. Os dados da data de nascimento preenchidos anteriormente não aparece.

### Comentários
@RochaCarla

**Comment by KahCosta** [comment]
Issue resolvida! Fechar
