### ISSUE TITLE
Tag ultrapassando limite do card 

### ISSUE THREAD

**Issue by Wictorgirardi** [ejplatform/ej-server#700]
## Descrição do Bug
As tags se tornam ilegíveis quando ou muito grandes ou quando a fonte do site é aumentada dentro de acessibilidades.

## Como Reproduzir
<img width="1440" alt="captura de tela 2018-12-09 as 18 06 38" src="https://user-images.githubusercontent.com/40725728/49704196-f580c000-fbdd-11e8-8875-d0d6f4cfe097.png">
1.  Após realizar o login, entre na opção de acessibilidade dentro do menu lateral.
2. Aumentando a fonte o card não acompanha de maneira dinâmica para que o texto inserido nele seja legível e totalmente incluso.

## Comportamento esperado
Os cards teriam que se adaptar de acordo com o texto colocado neles, ou a formatação desse texto teria que ser feita de forma diferente para que mesmo sendo uma preview do tópico, o usuário conseguisse saber de forma fácil do que se trata o assunto.

@RochaCarla

**Comment by rodrigocam** [comment]
Obrigado pela contribuição @Wictorgirardi! Este bug foi corrigido no PR #664, atualmente em devel, deve ir para a master na próxima release!
