### ISSUE TITLE
Barra de acesso "Entrar" aparece na tela de login

### ISSUE THREAD

**Issue by EsioFreitas** [ejplatform/ej-server#704]
# :bug: Bug Report

O menu de acesso à tela de login aparece na tela de login. Além disso, o texto da barra está linhado errado.

# To Reproduce

![ej1](https://user-images.githubusercontent.com/34384624/49704780-92ebec00-fbfe-11e8-823e-9eebddc3644e.png)

Quando você acessa a tela de login, a barra de acesso à página aparece nela. Isso pode gerar confusão para o usuário, pois não há motivos de ter acesso de um login dentro da tela de login. além disso, o texto da barra de acesso do login não segue o padrão das outras páginas

# Expected Behavior

![rr](https://user-images.githubusercontent.com/34384624/49704885-dc890680-fbff-11e8-8696-eab00b1c8f89.png)

O mais adequado seria tirar a barra de login da página para não gerar dúvidas. Caso a barra de acesso seja necessária, basta centralizar o texto dela para que assim siga o padrão.

**Comment by rodrigocam** [comment]
Olá @EsioFreitas, obrigado pela contribuição! O repositório [ej-front](https://github.com/ejplatform/ej-fron) não é mais utilizado, movi sua issue para nosso repositório principal [ej-server](https://github.com/ejplatform/ej-server) :)

**Comment by EsioFreitas** [comment]
@rodrigocam eu percebi isso depois e acabei criando essa [issue](https://github.com/ejplatform/ej-server/issues/701) no [ej-server](https://github.com/ejplatform/ej-server). Poderia fechar essa para não ter repetidas por favor.

**Comment by rodrigocam** [comment]
Duplicata com #701
