### ISSUE TITLE
Ajustes no template

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#726]
O template está ótimo, creio que faltam apenas dois ajustes pra ele ficar mais fiel com a interface de conversa:

1) Estilo do texto da pergunta: Note que o texto da pergunta no email aparece com uma cor azul parecida com a dos outro elementos. Na versão web, sua cor é mais escura e sem negrito o que propicia uma melhor leitura

2) Texto de orientação. No lugar de "Este é um questionário de pesquisa e sua participação é importante. Responda abaixo. Agradecemos sua participação!" sugiro um conteúdo com instrução mais explícita:
"Sua participação é importante. Responda abaixo votando no comentário exibido. Você será levado à página da pesquisa para votar nos outros comentários também"

3) Não acho uma boa a gente exibir o indicador de comentários como "1/1". Se a API não estiver preparada para exibir a quantidade correta da conversa, acho que o melhor é retirar essa parte do template

4) A palavra "Comentários" entre a pergunta e os cards é exibida aparentemente em negrito na versão web. Não sei dizer se isso influencia mas talvez valha a pena alinhar o estilo dessa fonte no template com a versão web também

VERSÃO EMAIL
![Captura de tela de 2019-06-12 07-56-45](https://user-images.githubusercontent.com/1162183/59346207-2a361700-8ce8-11e9-9dae-6b397e5460b7.png)

VERSÃO WEB
![Captura de tela de 2019-06-12 07-56-50](https://user-images.githubusercontent.com/1162183/59346233-35894280-8ce8-11e9-8381-30ac3f32ed96.png)

**Comment by KahCosta** [comment]
Fazendo!
