### ISSUE TITLE
Ajustes na exportação bruta para possibilitar análises além dos clusters

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#728]
Para que possamos realizar análises além dos clusters, precisamos poder exportar algumas informações adicionais na exportação bruta hj realizada na página de /reports

(1) Adicionar a coluna de contato (email) do participante na exportação de participantes da EJ. Ex: https://www.ejparticipe.org/conversations/servicos-publicos-futuro/reports/data/votes.csv

(2) Adicionar a coluna de id do comentário na exportação bruta de comentários da conversa. Ex: https://www.ejparticipe.org/conversations/servicos-publicos-futuro/reports/data/comments.csv

**Comment by davidCarlos** [comment]
@ArthurJahn dá uma olhada nessa issue aqui pf

**Comment by ArthurJahn** [comment]
@ricardopoppi confere se os dados que adicionamos nos arquivos são suficientes pra gente fechar essa issue.

**Comment by ricardopoppi** [comment]
@arthurbdiniz conferido, tudo certo na exportação
