### ISSUE TITLE
Voto via template de email não repercute após login

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#741]
Para replicar:

Opção novo registro:
1) Vote no email
2) Registre um novo usuário
3) Observe que o voto não foi computado

Opção login com usuário já registrado:
1) Vote no email
2) Faça login 
3) Observe que o voto não foi computado

Porém, se o usuário vota no email e já está logado, o voto computa normalmente

**Comment by davidCarlos** [comment]
@ricardopoppi podemos fechar essa issue né?
