### ISSUE TITLE
Adicionar destaque para a seção de conquistas da gamificação

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#744]
Atualmente essa seção se encontra na área de "contribuições" do perfil: /profile/achievements/

Para dar mais destaque à gamificação, é necessário que um indicador dos troféus possa ser exibido de forma permanente durante a navegação do usuário

**Comment by KahCosta** [comment]
Feita! será merjada junto as demais alteração nesta sprint 2
