### ISSUE TITLE
Componentizar algum elemento de front que apareça em pelo menos 2 arquivos

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#746]
Identificar algum elemento de front que se repete em várias partes do código e componentizá-lo

**Comment by KahCosta** [comment]
@ricardopoppi, você poderia especificar melhor quais elementos componentizar na tela? Estávamos observando algumas estruturas do jinja e observamos que, por sua essência, ele já está componentizando os elementos utilizados. Dessa forma, a tela que chama esse componente só faz uma requisição das informações necessárias.

**Comment by ricardopoppi** [comment]
@KahCosta eu não saberia precisar qual parte do front ainda precisa ser componentizada, aproveito pra pingar o prof @fabiommendes pra saber se há alguma parte que valeria a pena atacar. Enquanto isso criei uma outra issue que é mais objetiva em valor de negócio a #748 dá uma olhada nela. Por enquanto deixamos essa aqui em hold.

**Comment by KahCosta** [comment]
combinado @ricardopoppi !
Muito Obrigada!
