### ISSUE TITLE
Implementar o fade do form de comentários conforme implementado na release Ada Lovelace

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#748]
O form de comentários na versão anterior da EJ tem um recurso de fade, que faz o form aparecem em cima do comentário. Essa é uma importante evolução de UX que por motivos de simplificação não foi implementada na versão atual.

O objetivo dessa issue é implementar isso na versão 2.0. Para ver como funciona basta acessar uma conversa na versão antiga do EJ, em produção: https://www.ejparticipe.org/osbrasil/conversations/atitudesosb/
(clicar no botão +criar comentário)

**Comment by filipetoyoshima** [comment]
Se refere a essa parte?

![image](https://user-images.githubusercontent.com/29482983/64866548-039eb980-d612-11e9-9b5c-0370bb4cbf87.png)

**Comment by ricardopoppi** [comment]
> Se refere a essa parte?
> 
> ![image](https://user-images.githubusercontent.com/29482983/64866548-039eb980-d612-11e9-9b5c-0370bb4cbf87.png)

Exatamente
