### ISSUE TITLE
Rodar um checklist de UX na interface atual do PVPA

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#76]
Rodar um checklist na interface atual do PVPA, procurando por elementos faltantes e erros de UX: https://ejplatform.org/ com base nos wireframes do CPA

**Comment by ricardopoppi** [comment]
Conversei com @luizapeixe e esse checklist será feito após a entrega do wireframes da issue #78

**Comment by luizapeixe** [comment]
Isso! No momento estou trabalhando na evolução dos wireframes a partir do mapa de interação e assim que tiver a nova leva de wireframes, subo no Invision já com caminhos clicáveis e comentários relevantes. A partir daí poderemos criar essa checklist de maneira mais assertiva

**Comment by luizapeixe** [comment]
Ois, subi os novos wireframes [lá no invision](https://projects.invisionapp.com/d/#/projects/prototypes/13881288). Já habilitei alguns caminhos clicáveis então fiquem a vontade pra explorar, comentar, sugerir, criticar... E amanhã (23/05) às 15h vou apresentar as telas numa reunião via hangout. Quem quiser participar, é só chegar junto no telegram que na hora do call que a gente solta o link lá 😘

**Comment by ricardopoppi** [comment]
Fechando essa issue pra esse momento, vamos reativar o diagnóstico após a implementação dos novos wireframes
