### ISSUE TITLE
Simplificar o deploy do ej-server utilizando recursos do Gitlab-CI e Docker cache

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#86]

**Comment by luanguimaraesla** [comment]
O deploy foi simplificado da seguinte maneira:

* Não há mais necessidade do desenvolvedor, manualmente, inserir na mensagem de commit uma flag para o _build_ das imagens base, que eram usadas para agilizar o processo de teste no CI.
* Todos os scripts de controle do CI foram removidos para simplificar o processo de deploy.
* Todas as imagens, exceto a imagem de produção e desenvolvimento foram removidas da arquitetura.
* Não utilizaremos mais a imagem de CI/CD específica do EJ. Para aproveitar o cache dos runners do Gitlab, retornamos ao modelo anterior utilizando imagens padrão tanto do `docker` quanto do `gitlab-rancher-deploy`.
* Foi removido temporariamente do _build_ a atualização do `flower` e do `worker`. Estava quebrando produção por conta das refatorações do módulo matemático.
* Não utilizaremos mais a tag `develop` no Dockerhub.
* O ambiente principal de integração, vinculado ao site https://dev.ejplatform.org/, passou a ser a _branch_ `master`. Apesar disso, sugiro manter a `develop` no fluxo como _branch_ instável de desenvolvimento.
* Agora, os deploys em produção são realizados através de `tags`. As tags criadas atualizarão o site https://ejplatform.org/, da mesma forma como acontecia na _branch_ `master` antes.
* Os scripts de desenvolvimento foram movidos do diretório **./docker/local/** para **./docker/develop**. assim, para executar o ambiente de desenvolvimento deve-se digitar:
```bash
sudo docker-compose -f ./docker/develop/start.yml up
```
* O ambiente de desenvolvimento passou a ser uma qualificação do ambiente de produção, com as dependências de teste e debug incluídas. Desta forma, qualquer atualização nas dependências de produção (`requirements/production.txt`) para fazer efeito em desenvolvimento deve ser seguida por um **rebuild** da imagem de produção:
```bash
sudo docker-compose -f ./docker/production/django/build.yml build
sudo docker-compose --no-cache -f ./docker/develop/start.yml build
```
* Não estamos utilizando estratégias de _cache_ do Gitlab CI. A justificativa é a falta de disponibilidade do sistema de cache nativo, que é exclusivo de cada _runner_. Acontece que diferentes _jobs_ podem não rodar no mesmo _runner_, ocasionando erros ao tentar encontrar os arquivos cacheados. Outra estratégia seria a utilização do sistema de artefatos. O problema com ele é que aumentou o tempo de build em 7 minutos, já que fazer o upload de uma imagem para um sistema web não preparado para dockers, é realmente muito custoso.
* O tempo para a execução dos testes no CI manteve uma média muito baixa, 1 minuto e 40 segundos. Para a execução do _pipeline_ inteiro, `test`, `push` e `deploy`, a média é 6 minutos.
* A documentação não foi atualizada (#90)

**Comment by ricardopoppi** [comment]
@fabiommendes @caiosba @leandronunes @rodrigocam @pablodiegoss @lucasssm vcs já viram essas novas instruções? fiquem atentos para atualizar seus ambientes locais, reportem aqui se deu tudo certo
