### ISSUE TITLE
Configurar flake e hooks do git

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#87]
* [x] Configurar Flake8
* [x] zerar erros de estilo
* [x] configurar commit hook para impedir aparecimento de novos erros.

Para mim falta só comunicar o time sobre como será com o commit hook. O flake tem um comando que instala automaticamente.

**Comment by fabiommendes** [comment]
Hooks do git não são compartilhados no controle de versão. Por isso criamos uma task que instala os hooks em cada máquina. Basta rodar "inv install-hooks"
