### ISSUE TITLE
Reescrever documentação de deploy para novo modelo arquitetural

### ISSUE THREAD

**Issue by luanguimaraesla** [ejplatform/ej-server#90]
Fizemos várias alterações na arquitetura de deploy utilizando o Gitlab CI e outras ferramentas.

Retiramos a necessidade de um pipeline parcialmente manual com imagens base. Agora temos apenas duas imagens, a de produção e a de desenvolvimento, que é uma qualificação pequena da primeira.

Por parte do desenvolvedor, continuamos com pratiamente o mesmo fluxo, mantendo os diferentes tipos de execução: `idle`, `test` e `start`.

Devemos dedicar um tempo para ajeitar a documentação referente a essas alterações.

**Comment by ricardopoppi** [comment]
Fechando em função de issue mais atual sobre documentação de deploy (issue #265)
