### ISSUE TITLE
Fazer deploy da versão inglês do EJ

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#91]
Fazer deploy de uma versão em inglês do EJ em en.ejplatform.org

**Comment by luanguimaraesla** [comment]
Qual é a prioridade desta tarefa?

**Comment by ricardopoppi** [comment]
Eu diria que ela pode tranquilamente escapar pra depois do milestone. A vantagem de fazer antes é que já poderíamos trabalhar esses conteúdos. Em conversa com o @fabiommendes me pareceu que essa infra de internacionalização já existe
