### ISSUE TITLE
hotsite EJ destacando business

### ISSUE THREAD

**Issue by parrahenri** [ejplatform/ej-server#95]
Página principal do EJ destacando seu valor como serviço e potencializando adoção por parte de governantes e gestores

**Comment by parrahenri** [comment]
Referências que tô analisando:

https://pol.is/home
https://trello.com/
https://www.rdstation.com/?_ga=2.182406881.750277960.1526947997-979423075.1526947997
https://stilingue.com.br/
http://democracyos.org/
https://pt.duolingo.com/
https://www.guiabolso.com.br/
https://www.runtastic.com/
https://pol.is/home
https://www.spotify.com/br/
https://www.mudamos.org/

**Comment by parrahenri** [comment]
@ricardopoppi todos praticamente iguais em termos de estrutura (coluna única). 

Cabeçalho fixo funciona bem, com opções de Inscrever/ Entrar e mais uma ou duas. (provavelmente teremos de botar um quem somos, já que não somos conhecidos). 

Praticamente todos têm apelo visual por foto ou imagem do app/tecnologia (foto funciona melhor porque humaniza e já ajuda a demonstrar quem usa).

Todos colocam ícones com pouco texto para explicar mais sobre o uso.

Spotfy termina mostrando os planos de assinatura. Como saíramos só com o Free, podemos usar o que os demais fazem, que é terminar mostrando empresas/ governos que usam o app. Podemos falar de: FPA, PCdoB, TI, LAPPIS-UNB, HACKLAB.

Spotfy e Guia de Bolso são os melhores em termos de terem textos que dizem do valor/ impacto que geram. Acho a melhor referência, já que funcionalidades principais podem ser resumidas com 3 ícones + 50 caracteres cada.

**Comment by parrahenri** [comment]
Coluna única (estrutura)

Cabeçalho fixo:
- Quem somos
- Inscrever-se
- Entrar

Seção 1
Logo + Frase principal (com fundo colorido já que não teremos foto) 
Frase: (foco no valor)
Botão call to action: 

Seção 2
3 ícones resumindo o que é

Seção 3
Imagem de celular e de computador com a tela do EJ
Mais 3 highlights sobre o valor do EJ
2o. botão call to action

Seção 4:
(logos de quem usa o EJ ou faz parte da comunidade)
FPA, PCdoB, TI, LAPPIS-UNB, HACKLAB, SNDCA, ENAP

Rodapé:
Pergunta: ICD aparece na 4? Colocaremos qual info institucional no Quem somos e qual no rodapé?

**Comment by ricardopoppi** [comment]
Estrutura da home comercial/landing page do EJ com conteúdo:

Coluna única (estrutura)

Cabeçalho fixo:
- Quem somos

O Empurrando Juntos (EJ) é um software livre inicialmente criado pelo Instituto Cidade Democrática (ICD) para oferecer uma ferramenta de pesquisa e consulta de opinião participativa para governos. Hoje o software é desenvolvido pelo ICD, Hacklab, Lappis-UnB e sua comunidade vem empreendendo grandes esforços para acolher iniciativas e pessoas interessadas em seu uso.

- Inscrever-se
- Entrar

Seção 1
Logo + Frase principal (com fundo colorido usando um dos padrões do EJ já que não teremos foto) 
Frase: Crie consultas de opinião. Conheça o que as pessoas estão pensando. Tome decisões melhores.
Botão call to action: Experimente

Seção 2
3 ícones resumindo o que é (mostrar distribuindo horizontalmente)

1. Crie uma conversa no EJ para receber ideias e opiniões sobre políticas, serviços ou equipamentos públicos.
2. Escute a população, identifique suas prioridades e os diferentes grupos de opinião existentes na sociedade.  
3. Tome decisões e faça os participantes saberem, comunicando diretamente e amplificando as respostas.


Seção 3
Imagem de celular e de computador com a tela do EJ
Mais 3 highlights sobre o valor do EJ (mostrar distribuindo verticalmente ao lado da imagem)

1. Muitas pessoas. Participação simplificada para realizar consultas com milhares de pessoas sem restrições.
2. Sem ataques ou fakes. Dinâmica protege o debate das campanhas de ódio e ação articulada com robôs e perfis falsos.
3. Nuances em vez de bolhas. Visualização dos pontos em comum que diferentes grupos de opinião têm.
4. Gratuito. Licença livre torna o software gratuito e garante melhorias contínuas produzidas pela comunidade de desenvolvedores.

2o. botão call to action: Crie uma conversa


Seção 4:
(logos de quem usa o EJ ou faz parte da comunidade)
ICD, HACKLAB, LAPPIS-UNB, FPA, PCdoB, TI, SNDCA, ENAP

Rodapé:
O EJ é um software livre licenciado em agplv3. Você pode ajudar a desenvolvê-lo. [link da org no github]

**Comment by luizapeixe** [comment]
Segue a primeira proposta concreta pra nossa Home Comercial:

https://projects.invisionapp.com/d/#/console/13863876/302456109/preview
