### ISSUE TITLE
Nomenclatura Unificada

### ISSUE THREAD

**Issue by Heloisecs** [ejplatform/ej-server#96]
Pessoal, conversando com o Pablo e Rodrigo  ainda senti a necessidade de configurar um documento de nomenclatura unificada, para evitar confusões dentro da equipe e fora no diálogo com o público. Criei um documento bem simples e ainda incompleto com algumas sugestões, peço que quem puder edite e/ou adicione itens.
https://docs.google.com/document/d/1v7eOr57icVVptglxtfYEPXWEFvZMYjCcs7XsDxY2wj0/edit?usp=sharing

**Comment by ricardopoppi** [comment]
@Heloisecs @pablodiegoss fiz considerações no documento

**Comment by ricardopoppi** [comment]
Gente, com os últimos comentários do @fabiommendes e @luanguimaraesla fechamos a nomenclatura (cc @Heloisecs @luizapeixe )

Inglês (principal)

Conversation [
Tag = main topic of the conversation
Slug = fragment of a permalink used by the platform to unique identify a conversation within a user profile or within the platform
Title = Call to action of the conversation defined by a sentence or a question
Text = Initial text to provide engagement and context to the discussion
Comments = Comments made within a conversation
Votes = agree/disagree/pass
]
Messages = Rocket chat messages
Messages panel = Rocket chat channels panel


Português (tradução)

Conversa [
Tag = temas principais  aos quais a conversa pertence
Slug = permalink usado pelo sistema para identificar unicamente a conversa, dentro de um perfil
Título = Chamada da conversa definido por uma frase e/ou pergunta.
Texto = Texto inicial para engajar e contextualizar uma discussão
Comentário = comentário pertencente a uma conversa (chamada?).
Votos = concordo/discordo/passo
]
Mensagens = Rocket
Painel de Mensagens = Painel Rocket
