### ISSUE TITLE
Aplicação da idv do EJ na última versão dos wireframes

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#97]
Aplicar a idv do EJ nos wireframes para orientar o trabalho do time de desenvolvimento

**Comment by ricardopoppi** [comment]
@Heloisecs pode anexar/linkar aqui a ultima versão da idv junto com a orientação pra @luizapeixe pegar de onde vc parou?

**Comment by luizapeixe** [comment]
As novas telas já estão disponíveis no invision no seguinte link: https://invis.io/V9GNMI1BG2F

## Percebam que as telas possuem 5 (CINCO) divisões:

**1. telas para user ADMIN**
telas com composição e elementos específicos para usuários ADMIN

**2. telas para user PADRÃO**
telas com composição e elementos específicos para usuários PADRAO

**3. telas para user DESLOGADE**
telas com composição e elementos específicos para usuários sem login

**4. EXPERIMENTOS AVANÇADOS**
alguns experimentos de design que diferem ligeiramente das determinações de design até então, principalmente nas páginas de [Lista de Conversas*](https://invis.io/V9GNMI1BG2F#/300669779_lista_De_Conversas_V2) e [Página da Conversa**](https://invis.io/V9GNMI1BG2F#/300665703_Conversa_V2_USER_PADRAO).

* ali sugiro que a gente explore o uso do padrão de balõezinhos como background da lista de conversas e manter o thumbnail com fundo branco, pra deixar a leitura mais confortável e a interação mais convidativa

** na faixa de "opiniões da comunidade" sugiro que a gente abra mão da foto do user criador da opinião, uma vez que é um detalhe irrelevante para a interação com a opinão. Mantive apenas o nome

**5. telas antigas**
telas anteriores que mantive ali apenas em caráter de comparação com as versões anteriores

## A respeito de headings, 
minimizei a variação de tamanhos nos corpos de textos, que agora seguem o seguinte padrão de variações:

tipografias: [Raleway](https://fonts.google.com/specimen/Raleway) e [Patua One](https://fonts.google.com/specimen/Patua+One)

- 26 } título de destaque na home (com raleway) + texto "venha somar" (com patua) + Nome do user na página de perfil (com patua)

- 24 } títulos nas faixas (com raleway)

- 18 } textos nos botões de "começar agora" e "entrar" para users deslogades

- 16 } textos de introdução das faixas +  textos dentro dos thumbnais

- 14 } textos dentro de botões + textos secundários, tipo dentro dos toggles da home

- 12 } textos em metadados + barra de filtro de categoria na página Lista de Conversas

**Comment by ricardopoppi** [comment]
@luizapeixe parabéns pelo trabalho, ficou sensacional. Considero que os wireframes já estão maduros para implementação. Faço aqui abaixo um comentário geral, sobre a funcionalidade de criação de conversas, com base em alinhamentos prévios com @parrahenri e @fabiommendes. Esse comentário vai exigir alguns ajustes mínimos pra o que estou chamando de "um desafio de UX", que vc vai perceber qual é:

(1) Premissa: O EJ é um lugar onde qq usuário vai ter permissão para criar conversas e com isso vai populando sua timeline pública de conversas. Esse recurso pode ser apropriado por um usuário comum querendo fazer uma "consulta" na sua sala de aula, quanto por uma prefeitura lançando uma consulta pública;

(2) Portanto: O que estamos chamando de home atualmente, é exatamente essa timeline do usuário. A home oficial do EJ será construída a partir dos conteúdos que vamos criar na issue #95, ou seja, uma página estática e mais "comercial";

(3) Consequência: não haverá 3 camadas de papéis, mas apenas duas: (i) usuário, que pode participar em conversas e criar novas conversas na sua timeline (das quais será admin) e (ii) superusuário, que é quem administra a plataforma e faz manutenção do sistema;
(para o caso específico do CPA, vai existir uma exceção ao papel (i) voltada aos participantes que não forem do CPA)

Diante disso, temos um desafio de UX: Como dar ao usuário essa consciência de que toda conversa que ele criar vai pra timeline DELE, e de que quando ele entrar na timeline de um OUTRO usuário (ou já dentro de uma conversa específica de OUTRO usuário), o foco dele deve ser participar com votos e comentários? Em outras palavras: Como fazer com que o usuário não tenha a falsa impressão, quando tiver acessando a timeline de outro usuário (ou a conversa) de que a criação de uma nova conversa faz parte de outro contexto?

Esse comentário da issue #69 que é sobre arquitetura, complementa essas informações tb.

**Comment by parrahenri** [comment]
@luizapeixe, @ricardopoppi e galera. Deixei comentários no invision. Poppi consolidou o que está pacificado (acima) e eu quero sugerir ajustes naquela área de conteúdos que temos. Hoje estamos replicando a lógica de fases do CPA no genérico. Minha sugestão é que a gente consolide em:

1. OPINIÃO
Possibilita a participação de milhares de pessoas através de comentários e da votação em comentários. É possível identificar grupos de opiniões, ideias convergentes e divergentes e definir estratégias de ação.

2. DIÁLOGO
Eventos e reuniões para reunir as diferentes opiniões identificadas no debate e estimular a participação popular. O diálogo ajuda a qualificar o debate iniciado na plataforma e introduzir novos pontos de vista desejados.

3. RESPOSTA
Viabiliza o contato direto com participantes e grupos de opinião para responder de que maneira suas opiniões foram ouvidas, consideradas ou implementadas, reforçando a confiança e o dialogo.

Ainda que a gente ajuste esses textos, já ficamos com a coisa mais engatilhada pensando no genérico.

**Comment by luizapeixe** [comment]
Muito obrigada pelos feedbacks tão precisos, pessoal! Reorganizei o [invision](https://projects.invisionapp.com/d/#/projects/prototypes/13863876) seguindo a lógica de usuários 1. ADMIN; 2. LOGADE e 3. DESLOGADE. Agora na tela de lista de conversa o user logade também tem a opção de "adicionar conversa" e retirei a opção "CANAIS" da barra de navegação. Também atualizei a tela do menu hamburguer e corrigi as nomenclaturas de OPINIOES para CONVERSAS e VOTOS para OPINIOES. Alterei também a home comercial, porém ainda acho que podemos melhorar muito mais sua composição. Acham que ainda temos tempo de trabalhar nela antes do pessoal do front pegar pra implementar?

### Sobre a HOME TIMELINE

• Quanto a navegação entre as listas Geral e Pessoal, segui o exemplo do wireframe citado na [issue #69](https://github.com/ejplatform/ej-server/issues/69), porém condensei a ferramenta de busca junto com a faixa de filtro por assunto: [Vejam a tela com o design aplicado](https://invis.io/V9GNMI1BG2F#/301116048_Home_Timeline_Op--o_1)
nesse caso, todas as abas 1. COMUNIDADE; 2. VOCÊ e 3. FAVORITAS mostrariam o mesmo estilo de thumbnail, a única diferença entre elas seria o recurso de "gerenciar conversa" presente apenas na aba de VOCÊ (no caso de usuário não-admin)

-> _sobre manter a aba FAVORITADAS no filtro da timeline_: Se adotarmos mesmo a aba FAVORITAS na Home Timeline, podemos excluir a lista de Favoritas do página de Perfil, né? E deixar apenas a lista de comentários com os counters de concordo, passo e discordo.

• Quando o usuário está visualizando a timeline de uma pessoa específica, essa info se organiza na mesma barra de navegação, porém apresentando apenas duas opções 1. VOLTAR À LISTA GERAL e 2. NOME DA PESSOA que o user está visualizando: [Vejam aqui a tela com design aplicado](https://invis.io/V9GNMI1BG2F#/301116053_Home_Timeline_Op--o_2)

• Para além das barras de navegação, outro fator desafiador foi a reformulação da thumbnail das conversas na lista. Como a autoria da conversa voltou a ser um dado relevante e a adição do recurso de "favoritar", acabamos somando uma quantidade considerável de metadados pra apresentar na thumbnail da conversa. Cheguei em duas soluções diferentes que apresento resumidamente abaixo:

- **opção 1**: [Thumbnail redondo](https://invis.io/V9GNMI1BG2F#/301116048_Home_Timeline_Op--o_1)
essa opção faz uma relação mais direta com a identidade visual do EJ Genérico
a delimitação circular do thumbnail pede um limite de 210 caracteres no título da conversa. E não couberam todos os metadados com suas respectivas nomenclaturas, então abri mão do metadado de quantidade de FAVORITADAS e deixei apenas os counters de COMENTÁRIOS e OPINIÕES, além da AUTORIA da conversa. Um solução seria abrir mão de alguns caracteres no título para tentar abrir espaço e incluir o metadado ali.
Outra solução para fazer caber o metadado de FAVORITADAS (e a opção de favoritar) nos thumbnails foi iconizar* as nomenclaturas. Vejam nos nos exemplos 3 e 4 de thumbnails na tela da [opção1](https://invis.io/V9GNMI1BG2F#/301116048_Home_Timeline_Op--o_1).

-> _*_: iconizar as nomenclaturas nos thumbs, faz que precisemos aplicar esses icones também na página da interna da conversa, juntamente com as nomenclaturas, para o usuário criar uma identificação direta, caso a solução gráfica não seja suficientemente intuitiva pra todes.

- **opção 2**: [Thumbnail unboxed](https://invis.io/V9GNMI1BG2F#/301116053_Home_Timeline_Op--o_2)
essa opção se parece mais com o estilo de lista dos toggles na página de perfil do user.
nesse estilo de thumbnail temos mais espaço para compor os elementos e então fica possível apresentar os 3 metadados quantitativos mais a autoria e um botão mais obvio pro usuário favoritar a conversa a partir do próprio thumb.
as opções 3 e 4 de thumbs nessa tela também exemplificam a aplicação de ícones, caso a ideia agrade por aí :P

Por enquanto é isso. Tenho apenas duas dúvias que gostaria de sanar com vocês:

1ª dúvida: os usuários poderão acessar a página de perfil dos outros usuários? Ou apenas a lista de conversas criadas pelos users? 

2ª dúvida: que opções de gerencialmento os usuários comuns poderão ter com suas conversas? só editar ou também solicitar relatórios?

Seguimos!

**Comment by ricardopoppi** [comment]
@luizapeixe muito obrigado pela agilidade e explicação detalhada. Fizemos uma avaliação conjunta eu @fabiommendes e @parrahenri e fazemos apenas pedidos de ajustes pontuais:

1) Fechamos a nomenclatura. Conversas (ok), Comentários (ok), Opiniões viram VOTOS. Isso porque consideramos que as opiniões são compostas pelos dois elementos somados: comentários + votos. Então quando exibirmos os votos, chamaremos de VOTOS mesmo. Aqui a [versão final da nomenclatura](https://github.com/ejplatform/ej-server/issues/96#issuecomment-394733109) para referencia.

2) Vamos decidir pelo thumb REDONDO. Ele pode causar um estranhamento no inicio mas ele reflete melhor o conceito da idv do EJ e do tipo de conversa que o EJ proporciona: as conversas clusterizadas. Ficamos com essa opção então! Sobre os ícones, vamos ficar com a solução de iconizar as nomenclaturas refletida nos exemplos 3 e 4 de thumbnails na tela da opção1. Optamos por ela pois ela gera menos texto no thumbnail. Importante considerar também a aplicação desses mesmos icones na página da interna da conversa, como vc mencionou no texto de apresentação das telas.

3) Sobre a barra da home-timeline queremos os seguintes ajustes:

(i) Não termos nesse momento as opções COMUNIDADE/VOCE/FAVORITAS, suprimindo essa barra do layout;

(ii) Manter apenas a indicação do contexto que o usuário está:
- Quando for a timeline geral não indicar nada, 
- Quando for a timeline do usuário indicar algo como "Suas conversas" e 
- Quando for a timeline específica de um usuário indicar o nome do perfil do usuário específico. 
Isso vai ser importante pro tipo de uso que os early adopters do EJ vão fazer;

(iii) Com isso, as conversas favoritas voltam pro perfil do usuário;

(iv) Suprimir também a busca (mesmo condensada) pois não vamos implementar agora. Mantemos apenas as tags.

(v) A opção de "ADICIONAR CONVERSA" deve ser exibida APENAS quando o usuário está na sua própria timeline, pra não gerar confusão;

(vi) O recurso de "gerenciar conversa" segue presente apenas quando o usuário está na sua própria timeline (no caso de usuário não-admin). Isso já está ok;

(vii) Faltou a opção de moderar comentários quando o usuário está visualizando as suas próprias conversas.

4) Sobre as dúvidas:

1ª dúvida: os usuários poderão acessar a página de perfil dos outros usuários? Ou apenas a lista de conversas criadas pelos users?
Resposta: Não. Apenas a lista de conversas mesmo, a timeline de conversas do usuário será pública.

2ª dúvida: que opções de gerenciamento os usuários comuns poderão ter com suas conversas? só editar ou também solicitar relatórios?
Resposta: Nas suas conversas, o usuário comum pode tudo. Moderar comentários, gerenciar esteriótipos, solicitar relatórios

**Comment by luizapeixe** [comment]
Boa noite pessoal!

Ao longo do dia subi as telas revisadas no Invision e vou introduzir brevemente algumas considerações aqui.

• Homes Timeline:
Segui suas orientações porém achei que quando tiramos o menu pro user selecionar TODAS ou VOCÊ, o acesso para as conversas pessoais ficou um pouco escondido, então acabei incluindo acessos mais diretos no [menu](https://invis.io/V9GNMI1BG2F#/301115932_menu_LOGADES_-_PADRAO) e também nas próprias páginas de timeline [geral](https://invis.io/V9GNMI1BG2F#/301116048_Home_Timeline_P-blicas), [pessoal](https://invis.io/V9GNMI1BG2F#/301630843_Home_Timeline_PESSOAL) e de [outros users](https://invis.io/V9GNMI1BG2F#/301630842_Home_Timeline_USER_X).

• Ícones na página da conversa:
Feito! Vejam os resultados aplicados nas 3 variações dessa página. Users [deslogados](https://invis.io/V9GNMI1BG2F#/299689436_Conversa_DESLOGADES), User [logado](https://invis.io/V9GNMI1BG2F#/299689435_Conversa_USER_LOGADO) e [Autore](https://invis.io/V9GNMI1BG2F#/301698675_Conversa_USER_ADMIN) da conversa

• Página de edição da conversa:
Comentei na issue 69, mas reforço aqui. Temos uma primeira proposta de tela de [edição da conversa](https://invis.io/V9GNMI1BG2F#/301693278_Conversa_EDIT). Acredito que a tela de criação possa ser bastante parecida, porém com o campo de título da conversa em branco ou com algo a ser substituído, como "escreva o título da conversa aqui" e, obviamente, sem a lista de comentários, que ainda não existirão no caso da criação de uma nova conversa

• Tela de lista de notificações:
Percebi a falta também de algo que apresentasse as [notificações](https://invis.io/V9GNMI1BG2F#/301696002_lightbox_NOTIFICACOES), então eis uma primeira proposta de solução para essa questão

Acredito que isso seja tudo por enquanto. Qualquer dúvida ou sugestão, estou por aqui.

**Comment by ricardopoppi** [comment]
@luizapeixe aprovado com louvor! temos a versão final pra dev, nenhum ajuste adicional é necessário nesse momento, vamos implementar pra testar em campo e a partir daí pensar em eventuais ajustes que forem necessários.

@caiosba @leandronunes @lucasssm telas prontas pra implementação. Vcs devem acessar esse link do protótipo: https://projects.invisionapp.com/d/main#/projects/prototypes/13863876

Considerar as seções iniciais:
Telas novas (5 telas)
telas para users LOGADES (7 telas)
telas para users DESLOGADES (3 telas)
telas pra users ADMIN (1 tela)

Podem brocar!

**Comment by luizapeixe** [comment]
Boa noite pessoal, que tal assim a [navbar com o icone de _notificações_](https://projects.invisionapp.com/d/#/console/13863876/301696002/preview) separado do perfil?

**Comment by parrahenri** [comment]
Eu curto pq é mais direto e a área de notificações tende a ficar importante do ponto de vista dos push futuros!
