### ISSUE TITLE
Organizar os papéis de usuário na plataforma em 3 roles

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#98]
A plataforma deve suportar 3 papéis de usuários:
(i) usuário comum: só vota em conversas ou cria comentários
(ii) superusuário: vota, cria comentários e CRIA CONVERSAS, ADMINISTRA AS PRÓPRIAS CONVERSAS
(iii) superadmin: vota, cria comentários, CRIA CONVERSAS, ADMINISTRA QUALQUER CONVERSA

**Comment by luanguimaraesla** [comment]
@ricardopoppi Ok.

**Comment by fabiommendes** [comment]
Acho que não devemos falar em papeis, mas sim em permissões. Cada usuário pode ter conjuntos de permissões distintas e não precisa necessariamente cair em uma de 3 categorias distintas. O Django trabalha com um sistema de grupos/permissões inspirado no Linux. Podemos dar permissões para usuários ou grupos e o usuário herda todas as permissões de seus grupos.

Também é possível definir permissões mais ou menos arbitrárias como "o autor de uma conversa sempre tem permissão para editá-la". Os usuários comuns não tem permissão específica para nada e os usuários "superuser" tem implicitamente as permissões para fazer qualquer coisa

Assim, minha sugestão é criar as seguintes permissões:
1) Criar conversas em seu mural
2) Criar conversas globais

Pro caso 1, minha sugestão é que a permissão seja setada globalmente através de um setting. Assim, algumas instalações podem permitir conversas individuais e outras não.

Pro caso 2, criamos uma permissão explicita no banco de dados. No caso do CPA, o admin Django pode atribuí-la ao grupo CPA e todos os membros do grupo vão ter acesso a essa permissão

**Comment by ricardopoppi** [comment]
Me parece uma proposta excelente

**Comment by ricardopoppi** [comment]
@rodrigocam @pablodiegoss observem [o comentário](https://github.com/ejplatform/ej-server/issues/98#issuecomment-392611046) do @fabiommendes logo acima, e validem se esse lógica foi realmente criada e se podemos fechar essa issue

**Comment by rodrigocam** [comment]
Observando os arquivos permissions.py, parece que esse sistema de permissão foi criado, mas não sei se estão sendo utilizados e se essa parte do setting global está funcionando. Pode dar uma luz @fabiommendes ?

**Comment by ricardopoppi** [comment]
Update (cc @fabiommendes):

O usuário comum, que estiver no grupo sem a permissão de criar de conversas no EJ, o grupo mais básico, ele tem que ter uma restrição para não ser criado automaticamente um usuário pra ele no rocket.

**Comment by fabiommendes** [comment]
Outros comentários
* Conf no constance para o número de timelines disponíveis para o usuário padrão
* Timeline contem uma relação many to many com conversas
* Permissão para criação de quantas timelines necessárias para usuários comuns

**Comment by rodrigocam** [comment]
Agora com as timelines fiquei meio confuso haha. Atualmente um usuário comum pode criar várias timelines e criar conversas nelas, uma conversa pode pertencer a uma única timeline. Com esses novos requisitos fiquei meio confuso com o lance das permissões.

**Comment by ricardopoppi** [comment]
@rodrigocam @fabiommendes é um pouco confuso mesmo a principio. Nesse momento podemos simplificar as permissões, definindo que cada usuário só cria ou edita conversa nas timelines que criou. Aí ficaria algo assim:

Usuario > timeline (mais de uma) > conversas (mais de uma por timeline)

Sobre os outros requisitos de permissão, eles se mantem:
1) usuário não CPA não ganham usuário rocket, nem botão de painel
2) usuário CPA pode promover conversas para o /conversations

**Comment by ricardopoppi** [comment]
Essa issue tava muito caótica, então organizei os conteúdos relevantes dela nessa nova issue #317  - fechando essa então
