### ISSUE TITLE
Wireframes ajustados

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#99]
Fizemos a reunião de apresentação dos wireframes e combinamos que a @luizapeixe  faria apenas ajustes mínimos pra não atrasarmos a entrega. Ficou mapeado:

- retirada da busca; 
- eliminação de redundâncias de ux
- subir o dropdown de "meus comentários" e "conversas favoritas na tela de perfil

@luizapeixe  avisa aqui qdo tiver atualizado e pode passar pra #97 que depende dessa aqui :-)

**Comment by luizapeixe** [comment]
Feito!

• retirada da busca: 
- menu do user CPA https://projects.invisionapp.com/d/#/console/13881288/298423390/preview
- menu user padrão https://projects.invisionapp.com/d/#/console/13881288/298423391/preview
- lista de conversas https://projects.invisionapp.com/d/#/console/13881288/298961886/preview

• eliminação da redundancia:
- para contornar a questão dos demasiados convites ao login nas telas do user deslogade, tirei o botão de "ENTRAR" do call to action em todas as páginas e, na home, troquei o botão da primeira faixa de "ENTRAR" para "acessar conversas"
-> https://projects.invisionapp.com/d/#/console/13881288/298419440/preview

• subir dropdown das listas para antes das abas
- perfil 1 https://projects.invisionapp.com/d/#/console/13881288/298420480/preview
- perfil 2 https://projects.invisionapp.com/d/#/console/13881288/298420478/preview
- perfil 3 https://projects.invisionapp.com/d/#/console/13881288/298420479/preview
